<a href="https://colab.research.google.com/github/yuli206/mi-proyecto/blob/main/hola_la_bienvenida_a_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Proyecto: Estimación de condiciones de pobreza usando variables alternativas al IPM en colombia 2024
###Yuli Fernanda Ezquivel Martinez
###María José González serrano

#1.Exportacion de datos

   Datos sacados de:

* https://www.dane.gov.co/index.php/estadisticas-por-tema/pobreza-y-condiciones-de-vida/pobreza-multidimensional
* https://www.dane.gov.co/index.php/estadisticas-por-tema/salud/calidad-de-vida-ecv/encuesta-nacional-de-calidad-de-vida-ecv-2024

In [ ]:
import pandas as pd

# Nombres exactos de tus archivos en Colab
archivo_variables = 'anex-ECV-Series-2024.xlsx'
archivo_ipm = 'anex-PMultidimensional-Departamental-2024.xlsx'

# Leer archivos Excel
xls_variables = pd.ExcelFile(archivo_variables)
xls_ipm = pd.ExcelFile(archivo_ipm)

# Ver hojas que tienen
print("Hojas en archivo variables:")
print(xls_variables.sheet_names)

print("\nHojas en archivo IPM:")
print(xls_ipm.sheet_names)

Hojas en archivo variables:
['Índice', 'Cuadro 1', 'Cuadro 2', 'Cuadro 3', 'Cuadro 4', 'Cuadro 5', 'Cuadro 6', 'Cuadro 7', 'Cuadro 8', 'Cuadro 9', 'Cuadro 10', 'Cuadro 11', 'Cuadro 12', 'Cuadro 13', 'Cuadro 14', 'Cuadro 15', 'Cuadro 16', 'Cuadro 17', 'Cuadro 18', 'Cuadro 19', 'Cuadro 20', 'Cuadro 21', 'Cuadro 22']

Hojas en archivo IPM:
['Índice', 'IPM_Regiones', 'IPM_Departamentos', 'IPM_Variables_Región', 'IPM_Variables_Departamento ', 'IC_IPM', 'Intensidad_IPM', 'Incidencia_Ajustada_IPM', 'Contribuciones IA_IPM', 'IPM_Sexo', 'IC_IPM_Sexo', 'IPM_Sexo Jefe', 'IC_IPM_Sexo Jefe ']

In [ ]:
# dejar hojas de interes
df_variables = pd.read_excel(archivo_variables, sheet_name=['Cuadro 3','Cuadro 4','Cuadro 5','Cuadro 6','Cuadro 11'] )
df_ipm = pd.read_excel(archivo_ipm, sheet_name='IPM_Departamentos')

# 2.Limpieza de datos

# 2.1.IPM

In [ ]:
df_ipm

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Incidencia de Pobreza Multidimensional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Incidencia de Pobreza Multidimensional\nDepart...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Cifras en porcentaje,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Departamento,2018,NaN,NaN,2019,NaN,NaN,2020**,NaN,NaN,...,NaN,2022,NaN,NaN,2023,NaN,NaN,2024,NaN,NaN
11,NaN,Total,Cabeceras,Centros poblados \ny rural disperso,Total,Cabeceras,Centros poblados \ny rural disperso,Total,Cabeceras,Centros poblados \ny rural disperso,...,Centros poblados \ny rural disperso,Total,Cabeceras,Centros poblados \ny rural disperso,Total,Cabeceras,Centros poblados \ny rural disperso,Total,Cabeceras,Centros poblados \ny rural disperso
12,Antioquia,15.3,9.6,35.4,15.7,10.2,35.9,14.9,10.2,32.7,...,28,10.7,7,25.8,9.5,5.9,24.2,10.9,8.4,21.2
13,Atlántico,21.1,20,39.5,14.9,13.7,38,14.1,13.1,33.9,...,29.6,10.2,9.4,25,12,11.3,25.7,9.5,8.6,26.4
14,Bogotá D.C.,4.1,4.1,19.2,7.1,7.1,16.5,7.5,7.5,15.4,...,19.4,3.8,3.8,10.1,3.6,3.6,11.7,5.4,5.4,10.8
15,Bolívar,31.9,25.6,50.5,26.9,21.4,42.9,28.1,21.5,47.1,...,41.8,19.4,13.9,34.6,18.4,14.9,28,15.6,13.5,21.5
16,Boyacá,16.5,7.9,28.5,12.8,5,23.9,11.7,4.3,22.4,...,19.1,9.6,6.1,15.1,9.9,5.4,17,6.9,3.7,12.1
17,Caldas,13.8,10.1,24.6,14.3,10.4,25.8,14.5,8.7,32.8,...,20.4,10.5,7.8,19.5,7.4,4.8,16.3,9.2,6,20.3
18,Caquetá,26.9,20.5,38.6,25.7,19.2,37.7,26.1,18.4,40.5,...,36.6,19.6,16.4,25.6,17.2,11.3,28.6,13.9,8.6,24.2
19,Cauca,27.7,13.2,36.2,24,10.6,31.8,28.2,12.3,37.4,...,23.2,18.3,8.8,23.6,15.8,6.8,20.9,14,7.5,17.6
20,Cesar,31.7,26.5,47.6,25.5,20.5,40.7,27.2,20.7,46.8,...,39.1,19.1,14.2,34.1,17.7,13.2,30.9,13.4,10.7,21.3
21,Córdoba,34.4,21.1,49.2,34.7,23.2,47.2,31.8,21.8,42.6,...,40.6,26.9,16.5,38,21.4,12.6,30.6,25.7,13,38.9
22,Cundinamarca,10.5,6.8,20,12.3,9.4,20.5,11.4,9.4,17.1,...,13.3,7.3,6.3,10.4,7.6,7.8,7.1,7.4,6.8,9.4
23,Chocó,46.3,29.4,60.3,42.3,26.7,55.1,49,33.5,61.5,...,44.4,36.8,25.2,45.8,37.4,25.5,46.4,33.9,18.8,45.2
24,Huila,18,12.1,27,18.3,12.5,27.1,23.4,13.1,39,...,26.1,13.3,9,19.7,11.9,7.2,19.1,10.9,7.6,15.8
25,La Guajira,53.3,31.3,72.9,48.8,28.1,68.2,51.7,30.1,72.7,...,70.7,42.9,20.7,65,42.6,23.6,61.7,39.3,17.4,61.3
26,Magdalena,36.4,31.1,48.5,31.6,24.6,47.8,33.4,27.3,47,...,43.7,23,17.5,34.9,21.4,15.9,33,19.2,15,28.1
27,Meta,15.6,10.7,31.4,19.1,17.8,23.1,14.1,9.7,28.2,...,26.4,11.3,8.5,20.3,12.9,10.6,20.2,10.4,8,18.2
28,Nariño,33.1,22,41.7,23.2,18.4,26.9,27.3,15,36.8,...,28.9,17.6,12.7,21.4,16.6,11.6,20.5,18.1,10,24.5
29,Norte de Santander,29.5,25.9,43,24.2,19.3,42.8,26.1,20.8,46.2,...,44,18.5,13,39.8,20.5,16.4,36.2,15.2,8.5,41.1
30,Quindío,14.2,13.5,19,10.2,9.1,18,12.9,11.8,21,...,17.1,10,9.3,15.3,7.5,6.7,13.5,7.4,6.8,11.3
31,Risaralda,11.6,7,28,11.1,6.5,28.2,13.1,8.9,29.5,...,21.5,10,6.6,23.9,11.8,8.8,24,9.5,6.3,23
32,Santander,12.6,8.2,26.8,12.4,8.8,24.1,12.5,8.2,26.6,...,27.3,10.4,7.4,20.6,9.8,6.6,20.7,6.8,4.9,13.6
33,Sucre,41.7,32.8,56.8,33.3,25.4,46.6,38.1,29.5,52.2,...,41,26,19.8,36,23.1,15.9,34.6,21.8,12.4,36.4
34,Tolima,22.2,11.8,44.7,15.2,8.4,30,19,12.1,34,...,29,10.5,5.4,22,12.9,8,23.9,12.6,7.2,24.7
35,Valle del Cauca,14.1,12.5,23.2,10.8,9.3,19.4,11.1,8.9,24.1,...,18.6,9.7,8,19.4,7.2,5.8,15.8,6.2,4.6,15.9
36,Arauca,27.6,24.6,33.3,23.3,20.5,28.6,26.1,23.4,31.1,...,28.7,22.6,22.4,22.9,22.8,20.7,26.6,17.7,17.4,18.3
37,Casanare,19,14.5,29.6,18.3,15.1,26.2,19.6,14.3,32.8,...,27.3,13.3,10.7,20,15,12.5,21.4,11.3,9.1,17.1
38,Putumayo,24.1,17.5,30.8,25.4,22.1,28.7,27.8,22.6,33.2,...,29.4,20.8,14.7,27.2,13.2,10.5,16.1,11.8,8.8,15.1
39,San Andrés,8.5,8.5,NaN,8.2,8.2,NaN,11.9,11.9,NaN,...,NaN,8.8,8.8,NaN,5,5,NaN,6,6,NaN
40,Amazonas,35.4,27.4,42.1,35.6,19.5,49.6,39,24.3,53.5,...,28.4,27.9,23.5,32.3,25.4,18.6,32.6,15.6,13.8,17.6
41,Guainía,60.6,44,72.6,67,39.9,87.7,65.9,43.1,84.5,...,67.1,46.5,39.9,52.2,52.1,46.4,57,49,40.1,56.9
42,Guaviare,31.4,22.8,42.1,30.9,26.5,36.7,34.6,27.5,43.8,...,40,26.9,21.7,33.7,30.6,18.5,46.5,21.3,17.5,26.3
43,Vaupés,68.5,27.4,82.9,66.5,25.4,80.1,65.6,26.8,81.3,...,64.8,47.1,15,59.7,55.7,16.6,70.9,37.4,16.2,45.5
44,Vichada,63.5,33.7,73,72.2,35.7,84,75.6,46.6,85.1,...,73.4,75.4,36.1,87.9,65.4,33.6,75.4,70.2,30,82.7
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Fuente: DANE - Encuesta Nacional de Calidad de...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Datos expandidos con proyecciones de población...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Nota: (**) Para el año 2020 el indicador de In...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Nota: (***) En 2021 el operativo de campo de l...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,"Nota: Para el cálculo total nacional, total ca...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Actualizado el 22 de abril de 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Eliminar filas del 1 al 10 y del 45 hacia abajo en df_ipm
indices_a_eliminar = list(range(1, 11)) + list(range(45, len(df_ipm)))
df_ipm = df_ipm.drop(indices_a_eliminar).reset_index(drop=True)

print(f"df_ipm ahora tiene {len(df_ipm)} filas")

df_ipm ahora tiene 35 filas

In [ ]:
# Eliminar solo la fila 0
df_ipm = df_ipm.drop([0]).reset_index(drop=True)

print(f"df_ipm final: {len(df_ipm)} filas")

df_ipm final: 34 filas

In [ ]:
# Crear nombres de columnas correctos
años = ['2018', '2019', '2020', '2021', '2022', '2023', '2024']
categorias = ['Total', 'Cabeceras', 'Rural']
nuevos_nombres = ['Departamento']

for año in años:
    for categoria in categorias:
        nuevos_nombres.append(f'{año}_{categoria}')

df_ipm.columns = nuevos_nombres

# Convertir a numérico
for col in df_ipm.columns[1:]:
    df_ipm[col] = pd.to_numeric(df_ipm[col], errors='coerce')

print("df_ipm está listo y limpio!")

df_ipm está listo y limpio!

In [ ]:
 # Eliminar solo la fila 0
df_ipm = df_ipm.drop([0]).reset_index(drop=True)

print(f"df_ipm final: {len(df_ipm)} filas")

df_ipm final: 33 filas

In [ ]:
print(df_ipm.columns.tolist())

['Departamento', '2018_Total', '2018_Cabeceras', '2018_Rural', '2019_Total', '2019_Cabeceras', '2019_Rural', '2020_Total', '2020_Cabeceras', '2020_Rural', '2021_Total', '2021_Cabeceras', '2021_Rural', '2022_Total', '2022_Cabeceras', '2022_Rural', '2023_Total', '2023_Cabeceras', '2023_Rural', '2024_Total', '2024_Cabeceras', '2024_Rural']

In [ ]:
# Colocar el nombre de las columnas en el orden que quiero que queden
df_ipm = df_ipm[['Departamento', '2024_Total', '2024_Cabeceras', '2024_Rural' ]]
df_ipm.head(2)

  Departamento  2024_Total  2024_Cabeceras  2024_Rural
0    Antioquia        10.9             8.4        21.2
1    Atlántico         9.5             8.6        26.4

In [ ]:
#Encontrar duplicados
df_ipm.duplicated().sum()

np.int64(0)

In [ ]:
# Llenar los valores nulos con cero
df_ipm['2024_Rural'] = df_ipm['2024_Rural'].fillna(0)
df_ipm.tail()

   Departamento  2024_Total  2024_Cabeceras  2024_Rural
28     Amazonas        15.6            13.8        17.6
29      Guainía        49.0            40.1        56.9
30     Guaviare        21.3            17.5        26.3
31       Vaupés        37.4            16.2        45.5
32      Vichada        70.2            30.0        82.7

In [ ]:
# Ver la cantidad de valores nulos en cada columna
df_ipm.isna().sum()

Departamento      0
2024_Total        0
2024_Cabeceras    0
2024_Rural        0
dtype: int64

In [ ]:
df_ipm= df_ipm.drop(columns=['2024_Cabeceras'])

In [ ]:
df_ipm= df_ipm.drop(columns=['2024_Rural'])

In [ ]:
df_ipm

          Departamento  2024_Total
0            Antioquia        10.9
1            Atlántico         9.5
2          Bogotá D.C.         5.4
3              Bolívar        15.6
4               Boyacá         6.9
5               Caldas         9.2
6              Caquetá        13.9
7                Cauca        14.0
8                Cesar        13.4
9              Córdoba        25.7
10        Cundinamarca         7.4
11               Chocó        33.9
12               Huila        10.9
13          La Guajira        39.3
14           Magdalena        19.2
15                Meta        10.4
16              Nariño        18.1
17  Norte de Santander        15.2
18             Quindío         7.4
19           Risaralda         9.5
20           Santander         6.8
21               Sucre        21.8
22              Tolima        12.6
23     Valle del Cauca         6.2
24              Arauca        17.7
25            Casanare        11.3
26            Putumayo        11.8
27          San Andrés         6.0
28            Amazonas        15.6
29             Guainía        49.0
30            Guaviare        21.3
31              Vaupés        37.4
32             Vichada        70.2

#2.2.Variables

# 2.2.1.Jefatura femenina o masculina

In [ ]:
df_variables['Cuadro 3']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Dominio,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,Total hogares,Hogares por sexo del jefe/a,NaN,NaN,NaN,Hogares con jefa mujer sin cónyuge,NaN,NaN,NaN,...,NaN,NaN,Hogares con jefa mujer sin cónyuge,NaN,NaN,NaN,Hogares con jefe hombre sin cónyuge,NaN,NaN,NaN
11,NaN,NaN,Hombre,NaN,Mujer,NaN,Hogares con jefa mujer sin cónyuge,NaN,Hogares con jefa mujer sin cónyuge y con hijos...,NaN,...,Mujer,NaN,Hogares con jefa mujer sin cónyuge,NaN,Hogares con jefa mujer sin cónyuge y con hijos...,NaN,Hogares con jefe hombre sin cónyuge,NaN,Hogares con jefe hombre sin cónyuge y con hijo...,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,Total,%,Total,%,Total,%,Total,%,...,Total,%,Total,%,Total,%,Total,%,Total,%
14,Total nacional,15403,9652,62.662527,5751,37.337473,4402,76.542429,1404,31.887169,...,8593,46.477847,5911,68.780891,1994,33.729394,3105,31.373996,203,6.550664
15,Cabecera,11742,6988,59.507071,4755,40.492929,3655,76.861116,1119,30.618136,...,7030,49.013551,4922,70.012789,1555,31.598253,2339,31.990547,132,5.647322
16,Centros poblados y rural disperso,3660,2664,72.785775,996,27.214225,747,75.021162,285,38.09353,...,1563,37.706384,989,63.241661,438,44.338066,765,29.62836,71,9.312202
17,Amazonas,22,15,69.077018,7,30.922982,5,82.042741,3,52.820259,...,9,33.278112,7,72.968739,3,43.732217,5,28.193519,1,15.431578
18,Antioquia,2107,1224,58.098534,883,41.901466,670,75.888216,195,29.141183,...,1241,48.423565,878,70.724586,244,27.765659,422,31.892789,18,4.194267
19,Arauca,92,56,60.063902,37,39.936098,28,76.482218,12,43.210934,...,63,50.513424,41,65.221692,17,41.953086,31,50.379868,2,7.161013
20,Atlántico,647,421,65.028481,226,34.971519,165,72.746446,47,28.390828,...,376,45.958421,242,64.4236,76,31.410833,100,22.619067,8,7.865624
21,Bogotá D.C.,2601,1593,61.246944,1008,38.753056,774,76.811157,200,25.874928,...,1488,48.018984,1029,69.170125,281,27.261156,563,34.98063,14,2.423666
22,Bolívar,582,365,62.691911,217,37.308089,143,65.877392,51,35.495045,...,323,45.537365,192,59.511064,74,38.444537,101,26.076176,8,7.926883
23,Boyacá,424,281,66.113552,144,33.886448,116,80.464285,34,29.417809,...,213,46.769544,135,63.249373,47,34.756354,71,29.209895,4,6.124148
24,Caldas,340,207,60.988991,133,39.011009,106,79.78167,27,25.786802,...,175,46.153385,122,69.513025,32,26.194412,63,30.999091,4,6.737258
25,Caquetá,133,87,65.051763,46,34.948237,37,79.20492,17,46.911888,...,68,44.345117,46,68.613186,20,41.986347,28,32.945251,2,6.514431
26,Casanare,140,93,66.945352,46,33.054648,36,78.424288,17,46.652534,...,77,46.997677,53,67.79484,21,39.435747,34,39.335285,2,6.451873
27,Cauca,456,306,67.088803,150,32.911197,119,78.940033,42,35.310451,...,252,41.702825,196,77.783252,79,40.16445,133,37.878782,9,6.37669
28,Cesar,341,218,64.012535,123,35.987465,95,77.11125,44,46.678999,...,194,44.209332,138,71.077568,64,46.671084,70,28.591417,6,9.017692
29,Córdoba,495,325,65.709842,170,34.290158,124,72.924838,41,33.069399,...,286,45.208577,194,67.86233,73,37.900261,97,28.12516,11,11.145953
30,Cundinamarca,974,637,65.350353,338,34.649647,251,74.285691,82,32.756943,...,627,46.305709,418,66.589904,152,36.465418,255,35.028037,19,7.620516
31,Chocó,165,92,55.70513,73,44.29487,50,69.008494,23,44.658888,...,84,45.38904,61,72.311708,27,44.992355,29,29.070327,5,15.295403
32,Guainía,13,10,77.410793,3,22.589207,2,71.853815,1,56.932801,...,5,29.959962,4,72.643866,2,49.410389,4,31.236603,0,9.837394
33,Guaviare,28,20,71.035327,8,28.964673,6,76.771751,3,46.170715,...,14,39.686339,9,64.836677,4,44.956342,10,45.269825,1,9.149883
34,Huila,349,236,67.639764,113,32.360236,88,77.512857,35,40.204059,...,153,39.161964,107,70.403764,45,41.945916,61,25.848758,6,10.069204
35,La Guajira,258,140,54.296448,118,45.703552,83,70.069688,42,50.857222,...,170,51.746302,115,67.769821,60,51.799298,57,35.642319,9,16.032031
36,Magdalena,366,236,64.490107,130,35.509893,87,66.69673,31,35.189412,...,228,51.719136,114,49.983878,48,42.251064,61,28.520459,6,9.139573
37,Meta,344,225,65.496425,119,34.503575,88,73.907434,35,40.483185,...,180,45.55386,119,65.971922,45,38.237737,78,36.193094,7,8.641512
38,Nariño,510,333,65.378703,177,34.621297,150,85.112121,57,37.842264,...,271,44.333626,209,77.168483,86,41.319787,101,29.750746,5,5.208923
39,Norte de Santander,460,295,64.131722,165,35.868278,131,79.245356,45,34.256298,...,223,42.564624,152,68.335833,50,32.945844,68,22.647071,4,6.033476
40,Putumayo,117,74,63.565304,43,36.434696,31,73.612002,17,53.588121,...,65,40.03461,54,83.256849,28,51.308682,42,43.574663,2,5.739338
41,Quindío,190,116,60.818142,74,39.181858,64,85.521374,17,26.823661,...,103,47.93417,71,68.78188,17,24.552606,40,35.919598,3,6.808519
42,Risaralda,325,201,61.804533,124,38.195467,102,81.923935,27,26.242679,...,166,46.582932,117,70.318112,28,23.998433,56,29.352428,3,4.952955
43,San Andrés,16,11,65.715723,6,34.284277,5,87.52408,2,32.420102,...,7,44.39953,5,70.661347,1,27.275343,3,33.918287,0,2.994004
44,Santander,714,480,67.257221,234,32.742779,186,79.519711,54,29.290291,...,390,47.540545,253,64.846389,82,32.234378,122,28.30449,10,8.065303
45,Sucre,247,159,64.222115,88,35.777885,62,69.817915,22,35.644102,...,137,45.805584,85,62.407888,35,40.884081,44,26.964995,3,7.211383
46,Tolima,444,289,65.075623,155,34.924377,124,79.913881,38,30.674852,...,216,42.775263,160,74.37124,50,31.218081,96,33.328821,7,7.144413
47,Valle,1460,875,59.916016,585,40.083984,468,80.064229,139,29.630581,...,775,48.139307,573,73.95917,195,34.083523,247,29.544466,22,8.959873
48,Vaupés,9,7,81.91626,2,18.08374,1,86.729501,1,65.705696,...,3,19.810952,2,77.089492,1,49.916871,3,21.617993,1,21.505896
49,Vichada,31,24,77.064122,7,22.935878,6,85.646477,3,46.312981,...,11,27.590209,9,81.102522,6,62.081723,10,32.98653,2,23.053323
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Fuente: DANE - Encuesta Nacional de Calidad de...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Notas: \n- Datos expandidos con proyecciones d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,Actualizado el 24 de abril de 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Eliminar filas del 1 al 10 y del 45 hacia abajo en df_ipm
indices_a_eliminar = list(range(1, 14)) + list(range(50, len(df_variables['Cuadro 3'])))
df_variables['Cuadro 3'] = df_variables['Cuadro 3'].drop(indices_a_eliminar).reset_index(drop=True)

print(f"df_variables[Cuadro 3] ahora tiene {len(df_variables['Cuadro 3'])} filas")

df_variables[Cuadro 3] ahora tiene 37 filas

In [ ]:
# Eliminar solo la fila 0
df_variables['Cuadro 3'] = df_variables['Cuadro 3'].drop([0,1]).reset_index(drop=True)

print(f"df_variables[Cuadro 3] final: {len(df_ipm)} filas")

df_variables[Cuadro 3] final: 33 filas

In [ ]:
# Redondear todas las columnas numéricas a 1 decimal
df_variables['Cuadro 3'] = df_variables['Cuadro 3'].round(1)

# Mostrar resultado
df_variables['Cuadro 3'].head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97
0,Cabecera,11742,6988,59.507071,4755,40.492929,3655,76.861116,1119,30.618136,...,7030,49.013551,4922,70.012789,1555,31.598253,2339,31.990547,132,5.647322
1,Centros poblados y rural disperso,3660,2664,72.785775,996,27.214225,747,75.021162,285,38.09353,...,1563,37.706384,989,63.241661,438,44.338066,765,29.62836,71,9.312202
2,Amazonas,22,15,69.077018,7,30.922982,5,82.042741,3,52.820259,...,9,33.278112,7,72.968739,3,43.732217,5,28.193519,1,15.431578
3,Antioquia,2107,1224,58.098534,883,41.901466,670,75.888216,195,29.141183,...,1241,48.423565,878,70.724586,244,27.765659,422,31.892789,18,4.194267
4,Arauca,92,56,60.063902,37,39.936098,28,76.482218,12,43.210934,...,63,50.513424,41,65.221692,17,41.953086,31,50.379868,2,7.161013

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

df_variables['Cuadro 3']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97
0,Cabecera,11742,6988,59.507071,4755,40.492929,3655,76.861116,1119,30.618136,1618,23.149885,130,8.065128,NaN,12221,7142,58.434589,5080,41.565411,3790,74.613515,1178,31.091045,1713,23.992301,130,7.583814,NaN,12551,7216,57.495075,5335,42.504925,3927,73.607252,1240,31.572935,1819,25.203561,135,7.404907,NaN,13160,7075,53.764696,6085,46.235304,4282,70.375219,1369,31.965575,2041,28.839682,137,6.699947,NaN,13554,7223,53.289135,6331,46.710865,4493,70.959588,1471,32.741112,2118,29.321376,142,6.683143,NaN,13952,7270,52.105642,6682,47.894358,4689,70.16526,1465,31.243728,2253,30.987337,185,8.214872,NaN,14343,7313,50.986449,7030,49.013551,4922,70.012789,1555,31.598253,2339,31.990547,132,5.647322
1,Centros poblados y rural disperso,3660,2664,72.785775,996,27.214225,747,75.021162,285,38.09353,630,23.653296,50,7.861898,NaN,3778,2710,71.720634,1068,28.279366,775,72.562632,292,37.622484,674,24.867591,50,7.376157,NaN,3865,2664,68.936582,1201,31.063418,826,68.837633,336,40.63974,657,24.656996,55,8.379617,NaN,3908,2643,67.626346,1265,32.373654,855,67.601067,357,41.745118,686,25.95747,63,9.149848,NaN,3972,2550,64.200731,1422,35.799269,913,64.238187,392,42.954597,701,27.502913,65,9.217079,NaN,4057,2570,63.343451,1487,36.656549,949,63.798199,400,42.126256,727,28.293087,74,10.238306,NaN,4146,2583,62.293616,1563,37.706384,989,63.241661,438,44.338066,765,29.62836,71,9.312202
2,Amazonas,22,15,69.077018,7,30.922982,5,82.042741,3,52.820259,4,26.372993,1,17.164404,NaN,22,16,71.058435,6,28.941565,5,84.036236,3,47.660548,4,27.887091,1,12.3857,NaN,25,17,66.873042,8,33.126958,6,76.665351,3,47.423356,6,32.659583,1,15.674205,NaN,21,15,69.68074,6,30.31926,5,73.181395,2,44.786601,3,19.606858,1,21.264928,NaN,22,15,69.471929,7,30.528071,5,71.539656,2,43.174431,4,23.847321,1,17.589556,NaN,27,17,62.536596,10,37.463404,8,75.30291,3,38.302209,6,35.91914,1,11.896833,NaN,27,18,66.721888,9,33.278112,7,72.968739,3,43.732217,5,28.193519,1,15.431578
3,Antioquia,2107,1224,58.098534,883,41.901466,670,75.888216,195,29.141183,330,26.946069,15,4.416366,NaN,2133,1191,55.855627,941,44.144373,675,71.71009,214,31.640008,312,26.206878,19,6.232362,NaN,2180,1263,57.958379,916,42.041621,670,73.132427,205,30.551976,318,25.143967,13,4.240272,NaN,2328,1258,54.018425,1071,45.981575,736,68.708405,206,28.06924,382,30.371449,17,4.566457,NaN,2406,1245,51.761362,1161,48.238638,810,69.802223,245,30.226834,395,31.725666,25,6.346777,NaN,2485,1335,53.73997,1149,46.26003,836,72.74755,232,27.766873,378,28.278512,19,5.145713,NaN,2563,1322,51.576435,1241,48.423565,878,70.724586,244,27.765659,422,31.892789,18,4.194267
4,Arauca,92,56,60.063902,37,39.936098,28,76.482218,12,43.210934,18,33.303308,2,9.749076,NaN,103,60,58.577973,43,41.422027,30,69.811312,13,43.315084,19,32.229883,2,8.067231,NaN,108,58,53.375379,50,46.624621,33,65.194745,15,46.722525,22,38.556127,2,10.035702,NaN,109,59,53.808251,50,46.191749,33,64.596496,16,48.453437,23,39.161986,2,8.45843,NaN,113,57,50.563329,56,49.436671,35,63.43469,15,41.707951,23,40.555379,2,6.499071,NaN,114,56,48.83207,58,51.16793,34,57.684958,15,44.479711,24,43.48188,2,9.303378,NaN,125,62,49.486576,63,50.513424,41,65.221692,17,41.953086,31,50.379868,2,7.161013
5,Atlántico,647,421,65.028481,226,34.971519,165,72.746446,47,28.390828,65,15.376672,8,12.410521,NaN,679,423,62.289883,256,37.710117,179,69.814,54,30.206513,73,17.301821,5,7.474306,NaN,720,430,59.699231,290,40.300769,191,65.686534,59,31.151442,68,15.893281,5,7.460789,NaN,754,456,60.41273,299,39.58727,201,67.207701,57,28.544625,91,20.028686,9,9.667608,NaN,774,400,51.639058,374,48.360942,213,56.963255,69,32.566521,94,23.451348,7,7.761587,NaN,795,442,55.577966,353,44.422034,224,63.311813,78,34.709217,100,22.632775,11,11.427317,NaN,817,442,54.041579,376,45.958421,242,64.4236,76,31.410833,100,22.619067,8,7.865624
6,Bogotá D.C.,2601,1593,61.246944,1008,38.753056,774,76.811157,200,25.874928,375,23.567372,26,7.006432,NaN,2692,1621,60.221779,1071,39.778221,825,77.033486,225,27.246523,394,24.305377,26,6.57717,NaN,2692,1540,57.219574,1152,42.780426,825,71.633619,235,28.5169,430,27.907448,39,9.085094,NaN,2865,1503,52.46305,1362,47.53695,926,67.962256,290,31.284884,502,33.38562,35,7.048259,NaN,2940,1587,53.986723,1353,46.013277,934,69.024303,286,30.579429,480,30.209184,22,4.519218,NaN,3018,1552,51.418522,1466,48.581478,997,68.003241,259,25.942178,559,36.052926,50,8.931475,NaN,3098,1611,51.981016,1488,48.018984,1029,69.170125,281,27.261156,563,34.98063,14,2.423666
7,Bolívar,582,365,62.691911,217,37.308089,143,65.877392,51,35.495045,78,21.362599,8,9.619404,NaN,601,355,58.981235,247,41.018765,151,61.115117,50,32.899755,77,21.798112,7,9.426285,NaN,656,398,60.635817,258,39.364183,167,64.524983,62,37.140359,87,21.990909,8,8.767116,NaN,656,376,57.3041,280,42.6959,182,65.119159,69,37.874989,81,21.593689,7,9.173477,NaN,674,354,52.533058,320,47.466942,188,58.755229,76,40.455277,83,23.514935,8,9.619643,NaN,692,355,51.386166,336,48.613834,192,57.052968,69,35.839663,102,28.772676,9,9.18825,NaN,710,387,54.462635,323,45.537365,192,59.511064,74,38.444537,101,26.076176,8,7.926883
8,Boyacá,424,281,66.113552,144,33.886448,116,80.464285,34,29.417809,68,24.296027,5,6.892048,NaN,447,296,66.107787,152,33.892213,126,83.137689,44,34.643182,77,26.194742,4,5.603065,NaN,423,274,64.76308,149,35.23692,117,78.741374,38,32.373522,64,23.248285,3,5.318027,NaN,433,269,62.048386,164,37.951614,122,74.086164,40,33.230778,63,23.482714,3,5.073968,NaN,441,265,60.133672,176,39.866328,128,72.60245,44,34.150735,67,25.350895,4,6.35027,NaN,448,256,57.119672,192,42.880328,137,71.507836,47,34.084265,68,26.412854,6,8.201266,NaN,455,242,53.230456,213,46.769544,135,63.249373,47,34.756354,71,29.209895,4,6.124148
9,Caldas,340,207,60.988991,133,39.011009,106,79.78167,27,25.786802,50,23.989104,2,4.700162,NaN,350,216,61.795285,134,38.204715,107,79.702381,25,23.563248,56,25.855519,3,5.332635,NaN,367,219,59.656776,148,40.343224,118,80.03083,33,27.84215,64,29.39753,2,3.776277,NaN,355,200,56.14601,156,43.85399,118,75.698346,31,26.601349,54,27.246559,2,3.990313,NaN,363,200,55.052943,163,44.947057,117,71.811698,28,24.056576,54,27.191723,2,3.359157,NaN,371,209,56.232803,162,43.767197,117,71.964744,27,23.056185,58,27.602075,3,5.109673,NaN,380,204,53.846615,175,46.153385,122,69.513025,32,26.194412,63,30.999091,4,6.737258
10,Caquetá,133,87,65.051763,46,34.948237,37,79.20492,17,46.911888,22,25.488696,3,13.963108,NaN,134,88,66.044739,45,33.955261,37,81.203492,17,45.296273,23,26.447482,2,9.406141,NaN,131,85,64.638929,46,35.361071,36,77.537979,16,43.650943,20,23.699293,3,12.924687,NaN,139,81,57.876607,59,42.123393,42,70.849973,19,44.573478,23,28.208316,3,13.096289,NaN,144,87,60.80506,56,39.19494,42,75.132327,17,41.125586,25,28.396981,4,17.652295,NaN,148,84,56.90526,64,43.09474,45,70.688569,20,43.585472,26,30.69278,4,15.363059,NaN,153,85,55.654883,68,44.345117,46,68.613186,20,41.986347,28,32.945251,2,6.514431
11,Casanare,140,93,66.945352,46,33.054648,36,78.424288,17,46.652534,26,27.425682,2,8.082029,NaN,146,97,66.486306,49,33.513694,37,75.60472,15,41.273049,27,27.903585,2,6.847068,NaN,148,96,64.957104,52,35.042896,39,74.971289,17,44.225864,27,28.403237,3,10.285188,NaN,154,91,59.37986,62,40.62014,45,72.123076,21,46.084821,31,34.132699,3,10.7868,NaN,157,88,55.957712,69,44.042288,46,66.716593,21,45.750387,32,36.673301,2,6.346136,NaN,161,92,57.269657,69,42.730343,47,68.3805,21,44.677568,34,36.676999,3,10.186556,NaN,165,87,53.002323,77,46.997677,53,67.79484,21,39.435747,34,39.335285,2,6.451873
12,Cauca,456,306,67.088803,150,32.911197,119,78.940033,42,35.310451,69,22.419675,7,10.021052,NaN,481,322,67.06588,158,32.93412,132,83.425763,44,33.284112,82,25.436354,4,5.166732,NaN,480,296,61.737972,184,38.262028,139,75.820709,48,34.294318,74,24.866917,5,6.980042,NaN,559,339,60.567917,220,39.432083,174,79.049506,66,37.76685,115,33.993397,8,7.34872,NaN,574,347,60.458224,227,39.541776,180,79.276376,68,37.571896,119,34.122258,9,7.945855,NaN,590,327,55.529789,262,44.470211,196,74.701127,72,36.654634,129,39.309909,11,8.837694,NaN,604,352,58.297175,252,41.702825,196,77.783252,79,40.16445,133,37.878782,9,6.37669
13,Cesar,341,218,64.012535,123,35.987465,95,77.11125,44,46.678999,45,20.623232,3,7.503542,NaN,365,217,59.291675,149,40.708325,99,66.764217,47,47.392499,49,22.45423,5,10.717025,NaN,376,238,63.247874,138,36.752126,100,72.125474,41,41.473361,53,22.30846,5,9.534224,NaN,400,248,62.063859,152,37.936141,113,74.457084,49,43.555689,60,24.010199,5,7.981207,NaN,412,236,57.35031,176,42.64969,121,68.692416,56,46.597156,65,27.443845,5,7.907607,NaN,425,230,54.050868,195,45.949132,131,67.122684,58,44.370062,66,28.894144,6,8.356335,NaN,438,244,55.790668,194,44.209332,138,71.077568,64,46.671084,70,28.591417,6,9.017692
14,Córdoba,495,325,65.709842,170,34.290158,124,72.924838,41,33.069399,53,16.263457,5,8.738693,NaN,510,364,71.531142,145,28.468858,110,75.643767,37,33.33095,54,14.701183,5,9.924512,NaN,532,342,64.197276,191,35.802724,133,69.517078,44,32.920673,57,16.671467,3,5.628207,NaN,589,370,62.880848,218,37.119152,153,70.21135,54,34.923141,78,21.005715,7,9.111256,NaN,603,350,57.991844,253,42.008156,169,66.849462,70,41.053335,79,22.73149,6,8.028677,NaN,618,354,57.372925,263,42.627075,184,70.042951,71,38.385843,98,27.633167,12,11.854013,NaN,632,346,54.791423,286,45.208577,194,67.86233,73,37.900261,97,28.12516,11,11.145953
15,Cundinamarca,974,637,65.350353,338,34.649647,251,74.285691,82,32.756943,139,21.854063,9,6.19964,NaN,1054,710,67.360742,344,32.639258,265,77.116284,87,32.749831,168,23.624358,13,7.949269,NaN,1100,684,62.206229,416,37.793771,281,67.486128,100,35.804948,167,24.444427,13,7.649904,NaN,1190,733,61.602075,457,38.397925,322,70.475443,111,34.519102,192,26.210112,16,8.46839,NaN,1244,721,57.97151,523,42.02849,345,66.054095,125,36.238472,209,28.911251,15,7.394358,NaN,1299,747,57.498176,552,42.501824,374,67.668117,131,35.107355,231,30.936151,18,7.705459,NaN,1355,728,53.694291,627,46.305709,418,66.589904,152,36.465418,255,35.028037,19,7.620516
16,Chocó,165,92,55.70513,73,44.29487,50,69.008494,23,44.658888,28,30.577981,2,8.023891,NaN,170,94,55.187729,76,44.812271,53,69.540149,25,47.92947,28,30.141063,2,7.027572,NaN,182,99,54.215648,83,45.784352,59,70.788913,29,48.980985,32,32.560557,3,8.132042,NaN,172,96,55.794998,76,44.205002,52,68.945353,24,46.173901,27,27.744853,5,18.516982,NaN,176,90,51.162076,86,48.837924,58,66.907699,28,48.62659,28,31.112486,3,11.878239,NaN,181,95,52.80183,85,47.19817,58,67.464786,28,48.701572,26,26.772531,4,13.934652,NaN,185,101,54.61096,84,45.38904,61,72.311708,27,44.992355,29,29.070327,5,15.295403
17,Guainía,13,10,77.410793,3,22.589207,2,71.853815,1,56.932801,2,16.603885,0,17.306275,NaN,14,10,73.455415,4,26.544585,3,77.295549,1,50.094873,3,24.167173,0,7.235278,NaN,16,11,69.084236,5,30.915764,4,76.262842,2,49.674443,3,32.211987,0,12.992588,NaN,15,11,75.967641,4,24.032359,3,79.011669,1,50.514938,3,23.518904,0,8.654213,NaN,15,11,75.51074,4,24.48926,3,86.308877,2,55.467937,3,23.95656,0,15.206681,NaN,15,11,72.805257,4,27.194743,3,66.856177,1,49.787762,3,24.612119,0,9.287114,NaN,17,12,70.040038,5,29.959962,4,72.643866,2,49.410389,4,31.236603,0,9.837394
18,Guaviare,28,20,71.035327,8,28.964673,6,76.771751,3,46.170715,7,37.421446,1,13.166901,NaN,31,21,70.110934,9,29.889066,7,78.221236,3,43.857641,9,43.180796,1,5.916747,NaN,30,21,68.173643,10,31.826356,7,77.418456,4,50.895015,8,40.200036,2,19.004943,NaN,31,20,65.034865,11,34.965135,8,72.670237,4,51.875792,8,41.32406,1,9.498142,NaN,32,20,61.206728,12,38.793272,8,61.086887,4,47.825009,8,42.74207,1,7.495798,NaN,30,18,58.785876,12,41.214124,8,63.505804,3,42.453471,7,38.706797,1,10.671272,NaN,35,21,60.313661,14,39.686339,9,64.836677,4,44.956342,10,45.269825,1,9.149883
19,Huila,349,236,67.639764,113,32.360236,88,77.512857,35,40.204059,51,21.496843,5,9.488058,NaN,351,232,66.164459,119,33.835541,93,78.317973,38,40.550955,52,22.42023,4,8.141413,NaN,351,232,66.088177,119,33.911823,90,75.157866,34,38.311144,51,21.979954,6,10.975044,NaN,366,240,65.731151,125,34.268849,95,76.198161,38,39.715072,57,23.665778,3,6.081021,NaN,374,234,62.435266,141,37.564734,102,72.590977,43,42.312481,53,22.622424,5,10.163141,NaN,382,234,61.264438,148,38.735562,100,67.852381,43,42.437792,59,25.033216,7,11.895177,NaN,390,237,60.838036,153,39.161964,107,70.403764,45,41.945916,61,25.848758,6,10.069204
20,La Guajira,258,140,54.296448,118,45.703552,83,70.069688,42,50.857222,44,31.162421,5,10.528145,NaN,282,158,56.177706,124,43.822294,90,72.767794,48,52.999882,47,29.767575,4,7.713741,NaN,296,155,52.388654,141,47.611346,98,69.818636,53,53.733306,48,31.110822,5,10.885453,NaN,295,143,48.501565,152,51.498435,99,65.0373,56,56.379535,48,33.581488,7,13.767745,NaN,307,151,49.168088,156,50.831912,103,65.851725,54,52.332479,51,34.026683,7,13.527777,NaN,318,146,45.984373,172,54.015627,106,61.426229,54,51.101338,48,33.130676,10,21.494469,NaN,329,159,48.253698,170,51.746302,115,67.769821,60,51.799298,57,35.642319,9,16.032031
21,Magdalena,366,236,64.490107,130,35.509893,87,66.69673,31,35.189412,47,19.887775,5,11.682976,NaN,396,234,59.030489,162,40.969511,94,57.998137,37,39.221308,46,19.710051,7,15.338011,NaN,404,258,63.994061,145,36.005939,97,66.658381,36,36.669084,50,19.232963,4,8.938923,NaN,411,232,56.347818,179,43.652182,104,57.923194,39,37.554429,56,23.99301,4,7.364852,NaN,422,244,57.986427,177,42.013573,113,63.603505,45,40.23883,60,24.363201,6,9.881553,NaN,432,245,56.801931,186,43.198069,112,59.866599,42,37.340295,60,24.419215,7,11.75068,NaN,442,213,48.280864,228,51.719136,114,49.983878,48,42.251064,61,28.520459,6,9.139573
22,Meta,344,225,65.496425,119,34.503575,88,73.907434,35,40.483185,63,28.180222,6,9.473428,NaN,354,218,61.585149,136,38.414851,93,68.665896,35,37.129333,72,33.139523,4,6.061781,NaN,364,233,64.070373,131,35.929627,97,74.514611,38,39.538294,73,31.339527,8,10.315301,NaN,370,221,59.881794,148,40.118206,105,70.63932,39,36.755554,72,32.439208,6,8.73253,NaN,378,218,57.592267,160,42.407733,111,68.928573,41,37.206287,75,34.456015,6,8.525127,NaN,386,221,57.167829,166,42.832171,111,66.783866,39,35.267695,72,32.526135,6,8.436231,NaN,395,215,54.44614,180,45.55386,119,65.971922,45,38.237737,78,36.193094,7,8.641512
23,Nariño,510,333,65.378703,177,34.621297,150,85.112121,57,37.842264,70,21.038803,5,6.450339,NaN,538,347,64.582583,191,35.417417,156,82.066728,58,37.290073,75,21.63509,4,4.822277,NaN,534,343,64.199444,191,35.800556,157,82.362664,62,39.269223,68,19.691323,4,6.399878,NaN,577,353,61.105768,224,38.894232,182,81.168619,74,40.788867,88,24.870248,3,3.903173,NaN,588,350,59.408752,239,40.591248,197,82.611635,80,40.776795,95,27.232061,6,6.176084,NaN,600,347,57.867542,253,42.132458,196,77.585021,80,41.020772,94,27.141758,6,6.176194,NaN,611,340,55.666374,271,44.333626,209,77.168483,86,41.319787,101,29.750746,5,5.208923
24,Norte de Santander,460,295,64.131722,165,35.868278,131,79.245356,45,34.256298,64,21.711206,5,8.522881,NaN,476,297,62.482426,179,37.517574,132,73.879773,42,31.999839,70,23.593319,5,6.418728,NaN,508,310,61.055375,198,38.944625,142,71.837216,51,36.140242,77,24.936779,5,6.263917,NaN,494,278,56.332522,216,43.667478,138,64.117227,49,35.55686,75,27.060998,3,3.902204,NaN,504,291,57.890364,212,42.109636,145,68.186954,54,37.359788,78,26.634052,4,5.204916,NaN,514,290,56.49069,223,43.50931,150,67.14871,54,35.974349,72,24.910529,5,6.279815,NaN,524,301,57.435376,223,42.564624,152,68.335833,50,32.945844,68,22.647071,4,6.033476
25,Putumayo,117,74,63.565304,43,36.434696,31,73.612002,17,53.588121,21,28.056981,3,14.092362,NaN,125,82,65.211297,44,34.788703,34,77.26182,16,46.895211,25,31.15016,3,11.538028,NaN,125,76,61.350345,48,38.649655,36,75.111225,19,52.057874,21,28.085811,2,9.017288,NaN,146,85,58.478984,60,41.521016,50,82.847604,25,50.113229,33,39.128189,3,8.310839,NaN,151,87,57.84067,63,42.15933,51,80.471327,26,51.406324,35,40.403808,4,11.299292,NaN,156,93,59.575234,63,40.424766,51,80.849452,24,47.451868,37,40.196113,3,7.31479,NaN,161,97,59.96539,65,40.03461,54,83.256849,28,51.308682,42,43.574663,2,5.739338
26,Quindío,190,116,60.818142,74,39.181858,64,85.521374,17,26.823661,30,25.90919,2,5.093553,NaN,195,117,60.116239,78,39.883761,64,82.072816,15,23.883771,34,28.855567,2,4.972978,NaN,210,119,56.826795,91,43.173205,71,78.732628,18,24.71058,40,33.184498,2,6.230551,NaN,199,112,56.091581,87,43.908419,64,73.146484,17,26.978787,33,29.411237,2,5.598619,NaN,204,106,51.964884,98,48.035116,70,71.50657,17,24.668953,33,31.368126,2,5.645491,NaN,209,108,51.540319,101,48.459681,70,69.21817,17,24.677214,38,35.091559,2,4.65236,NaN,215,112,52.06583,103,47.93417,71,68.78188,17,24.552606,40,35.919598,3,6.808519
27,Risaralda,325,201,61.804533,124,38.195467,102,81.923935,27,26.242679,51,25.488441,3,6.602011,NaN,335,201,60.146703,133,39.853297,102,76.281331,24,23.826432,52,25.826133,3,5.475631,NaN,349,190,54.436903,159,45.563097,119,75.078963,32,26.927482,63,32.958963,3,4.832147,NaN,333,196,58.670051,138,41.329949,111,80.462105,27,24.359631,45,22.869105,4,8.471965,NaN,341,202,59.078169,140,40.921831,107,77.014566,30,27.535282,60,29.916427,4,6.62241,NaN,349,188,53.740334,162,46.259666,116,72.001776,27,23.051402,59,31.462564,3,5.034904,NaN,357,191,53.417068,166,46.582932,117,70.318112,28,23.998433,56,29.352428,3,4.952955
28,San Andrés,16,11,65.715723,6,34.284277,5,87.52408,2,32.420102,3,31.454554,0,4.951892,NaN,15,9,60.973272,6,39.026728,4,74.049746,2,34.035982,3,30.916902,0,5.63624,NaN,16,9,57.24403,7,42.75597,5,73.416974,2,31.295512,3,32.22536,0,5.386405,NaN,15,9,58.608898,6,41.391102,5,75.545483,1,25.187103,2,25.960661,0,5.904974,NaN,16,9,54.679767,7,45.320233,5,70.602847,1,23.865696,3,30.232504,0,5.747694,NaN,16,9,57.491327,7,42.508673,5,74.591785,1,27.669258,2,26.506983,0,4.762377,NaN,17,9,55.60047,7,44.39953,5,70.661347,1,27.275343,3,33.918287,0,2.994004
29,Santander,714,480,67.257221,234,32.742779,186,79.519711,54,29.290291,103,21.538797,5,5.280456,NaN,738,448,60.652033,290,39.347967,210,72.273677,59,28.28482,108,24.008833,9,8.16733,NaN,755,466,61.660069,290,38.339931,206,71.085748,64,30.997563,112,23.982433,9,8.191862,NaN,769,413,53.734507,356,46.265493,226,63.615535,62,27.450512,114,27.593097,7,6.563822,NaN,786,439,55.863638,347,44.136362,227,65.495465,75,32.871857,121,27.488242,7,5.93681,NaN,803,447,55.644813,356,44.355187,234,65.588607,73,31.156139,126,28.292975,13,9.958716,NaN,821,431,52.459455,390,47.540545,253,64.846389,82,32.234378,122,28.30449,10,8.065303

In [ ]:
print(df_variables['Cuadro 3'].columns.tolist())

['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97']

In [ ]:
# Colocar el nombre de las columnas en el orden que quiero que queden
df_variables['Cuadro 3'] = df_variables['Cuadro 3'][['Unnamed: 0', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 88' ]]
df_variables['Cuadro 3'].head(2)

                          Unnamed: 0 Unnamed: 85 Unnamed: 86 Unnamed: 88
0                           Cabecera       14343        7313        7030
1  Centros poblados y rural disperso        4146        2583        1563

In [ ]:
# Renombrar columnas
df_variables['Cuadro 3'] = df_variables['Cuadro 3'].rename(columns={
    'Unnamed: 0': 'Departamento',
    'Unnamed: 85': 'total hogares',
    'Unnamed: 86': 'hogares con jefe hombre',
    'Unnamed: 88': 'hogares con jefe mujer'
})

# Verificar resultado
df_variables['Cuadro 3'].head(2)

,Departamento,total hogares,hogares con jefe hombre,hogares con jefe mujer
0,Cabecera,14343,7313,7030
1,Centros poblados y rural disperso,4146,2583,1563

In [ ]:
# Eliminar solo la filas
df_variables['Cuadro 3'] = df_variables['Cuadro 3'].drop([0,1]).reset_index(drop=True)

print(f"df_variables[Cuadro 3] final: {len(df_ipm)} filas")

df_variables[Cuadro 3] final: 33 filas

In [ ]:
#Encontrar duplicados
df_variables['Cuadro 3'].duplicated().sum()

np.int64(0)

In [ ]:
# Ver la cantidad de valores nulos en cada columna
df_variables['Cuadro 3'].isna().sum()

Departamento               0
total hogares              0
hogares con jefe hombre    0
hogares con jefe mujer     0
dtype: int64

In [ ]:
df_variables['Cuadro 3']

,Departamento,total hogares,hogares con jefe hombre,hogares con jefe mujer
0,Amazonas,27,18,9
1,Antioquia,2563,1322,1241
2,Arauca,125,62,63
3,Atlántico,817,442,376
4,Bogotá D.C.,3098,1611,1488
5,Bolívar,710,387,323
6,Boyacá,455,242,213
7,Caldas,380,204,175
8,Caquetá,153,85,68
9,Casanare,165,87,77
10,Cauca,604,352,252
11,Cesar,438,244,194
12,Córdoba,632,346,286
13,Cundinamarca,1355,728,627
14,Chocó,185,101,84
15,Guainía,17,12,5
16,Guaviare,35,21,14
17,Huila,390,237,153
18,La Guajira,329,159,170
19,Magdalena,442,213,228
20,Meta,395,215,180
21,Nariño,611,340,271
22,Norte de Santander,524,301,223
23,Putumayo,161,97,65
24,Quindío,215,112,103
25,Risaralda,357,191,166
26,San Andrés,17,9,7
27,Santander,821,431,390
28,Sucre,299,162,137
29,Tolima,504,288,216
30,Valle,1610,835,775
31,Vaupés,15,12,3
32,Vichada,41,30,11

 # 2.2.2.Hogares por acceso a servicioos públicos

In [ ]:
df_variables['Cuadro 4']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Volver al inicio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Dominio,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,Total hogares,Energía,NaN,Gas natural,NaN,Acueducto,NaN,Alcantarillado,NaN,Recolección de basura,NaN,Teléfono fijo,NaN,Ningún servicio,NaN,NaN,Total hogares,Energía,NaN,Gas natural,NaN,Acueducto,NaN,Alcantarillado,NaN,Recolección de basura,NaN,Teléfono fijo,NaN,Ningún servicio,NaN,NaN,Total hogares,Energía,NaN,Gas natural,NaN,Acueducto,NaN,Alcantarillado,NaN,Recolección de basura,NaN,Teléfono fijo,NaN,Ningún servicio,NaN,NaN,Total hogares,Energía,NaN,Gas natural,NaN,Acueducto,NaN,Alcantarillado,NaN,Recolección de basura,NaN,Teléfono fijo,NaN,Ningún servicio,NaN,NaN,Total hogares,Energía,NaN,Gas natural,NaN,Acueducto,NaN,Alcantarillado,NaN,Recolección de basura,NaN,Teléfono fijo,NaN,Ningún servicio,NaN,NaN,Total hogares,Energía,NaN,Gas natural,NaN,Acueducto,NaN,Alcantarillado,NaN,Recolección de basura,NaN,Teléfono fijo,NaN,Ningún servicio,NaN,NaN,Total hogares,Energía,NaN,Gas natural,NaN,Acueducto,NaN,Alcantarillado,NaN,Recolección de basura,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,Total,%,Total,%,Total,%,Total,%,Total,%,Total,%,Total,%,NaN,NaN,Total,%,Total,%,Total,%,Total,%,Total,%,Total,%,Total,%,NaN,NaN,Total,%,Total,%,Total,%,Total,%,Total,%,Total,%,Total,%,NaN,NaN,Total,%,Total,%,Total,%,Total,%,Total,%,Total,%,Total,%,NaN,NaN,Total,%,Total,%,Total,%,Total,%,Total,%,Total,%,Total,%,NaN,NaN,Total,%,Total,%,Total,%,Total,%,Total,%,Total,%,Total,%,NaN,NaN,Total,%,Total,%,Total,%,Total,%,Total,%
13,Total nacional,15403,15048,97.69807,9921,64.413553,13367,86.784091,11403,74.035345,12515,81.250403,4440,28.824385,294,1.906761,NaN,15999,15694,98.088931,10320,64.501033,13916,86.977928,11896,74.351285,13084,81.776544,4039,25.246624,249,1.556235,NaN,16417,16126,98.232925,10795,65.754976,14671,89.367388,12329,75.10289,13558,82.5891,3906,23.792778,249,1.515709,NaN,17068,16622,97.384592,11475,67.23338,14890,87.2363,12808,75.037779,14085,82.522329,3753,21.990679,400,2.342801,NaN,17526,17278,98.586595,12021,68.590518,15578,88.886643,13218,75.422333,14516,82.829063,3256,18.579669,214,1.219887,NaN,18009,17776,98.70203,12551,69.694435,16210,90.009633,13693,76.031084,15018,83.392318,2882,16.000968,208,1.153165,NaN,18489,18279,98.86242,13101,70.856585,16667,90.142428,14089,76.19949,15465,83.639957
14,Cabecera,11742,11714,99.757967,9515,81.030391,11397,97.055478,10877,92.627401,11537,98.247223,4379,37.293155,7,0.059151,NaN,12221,12200,99.824844,9856,80.644211,11876,97.17213,11338,92.769187,12037,98.489681,3970,32.481163,4,0.02906,NaN,12551,12537,99.881923,10245,81.622035,12234,97.470955,11680,93.060158,12345,98.35152,3855,30.716321,4,0.035851,NaN,13160,13141,99.855728,10909,82.896558,12837,97.543937,12223,92.880921,12918,98.157597,3716,28.237062,5,0.037449,NaN,13554,13536,99.868064,11431,84.334179,13251,97.763868,12630,93.186024,13333,98.371697,3223,23.775562,4,0.030218,NaN,13952,13928,99.823354,11847,84.912047,13669,97.966652,13046,93.506292,13722,98.349167,2853,20.445745,13,0.094097,NaN,14343,14323,99.863381,12346,86.074776,14087,98.212631,13450,93.771648,14166,98.767364
15,Centros poblados y rural disperso,3660,3334,91.089563,406,11.103863,1970,53.831704,527,14.388812,978,26.721666,61,1.655105,287,7.834212,NaN,3778,3494,92.473217,464,12.277533,2040,53.999481,558,14.769006,1047,27.709213,70,1.842749,245,6.496678,NaN,3865,3590,92.877972,550,14.228349,2437,63.051894,649,16.788526,1214,31.402276,51,1.309291,244,6.321396,NaN,3908,3481,89.063074,566,14.48784,2053,52.525473,584,14.951237,1167,29.870775,37,0.956067,395,10.106041,NaN,3972,3742,94.213525,590,14.86456,2327,58.592712,588,14.802932,1183,29.78912,34,0.848449,210,5.279687,NaN,4057,3848,94.845787,704,17.360924,2542,62.64537,646,15.933679,1296,31.955573,29,0.715339,195,4.795307,NaN,4146,3956,95.399911,755,18.214095,2580,62.226128,639,15.414201,1298,31.311508
16,Amazonas,22,18,84.775373,0,0,5,24.714111,5,22.606574,9,41.689856,0,1.095645,3,13.973816,NaN,22,19,84.739833,0,0,8,34.232493,4,20.120939,11,50.408573,0,0.654533,3,13.458602,NaN,25,21,83.185346,0,0,12,45.693424,9,35.842857,14,54.21727,0,1.324161,4,14.123484,NaN,21,17,81.658053,0,0,11,51.690644,7,33.572958,11,53.242601,0,0.082343,3,14.671259,NaN,22,18,83.189868,0,0,9,43.295595,9,42.31667,12,53.297217,0,0.438473,3,13.644207,NaN,27,24,89.81654,0,0,11,41.669085,10,38.664363,15,57.627583,0,0.547153,2,8.287656,NaN,27,26,95.680352,0,0,12,45.313996,8,30.561509,14,52.353126
17,Antioquia,2107,2097,99.515343,1219,57.842454,1834,87.014696,1648,78.208897,1853,87.953745,914,43.362966,6,0.28363,NaN,2133,2128,99.77298,1327,62.213251,1949,91.380361,1786,83.771091,1933,90.632939,863,40.460299,3,0.142762,NaN,2180,2173,99.676108,1292,59.295509,2040,93.594901,1785,81.870767,1992,91.388589,664,30.459011,4,0.16116,NaN,2328,2319,99.617013,1455,62.47882,2134,91.638061,1905,81.825793,2146,92.153376,628,26.964929,4,0.152185,NaN,2406,2405,99.942551,1551,64.471532,2239,93.068042,1945,80.854308,2203,91.570975,583,24.240132,1,0.029654,NaN,2485,2482,99.903999,1634,65.750123,2344,94.32906,2027,81.560507,2288,92.060694,533,21.454382,1,0.059011,NaN,2563,2560,99.882231,1751,68.325579,2368,92.390274,2090,81.572539,2364,92.258793
18,Arauca,92,89,96.173138,5,5.222817,70,75.657706,53,57.610288,65,69.851717,4,3.968952,2,2.509328,NaN,103,101,97.959604,5,5.105166,75,72.781188,61,59.550304,72,69.889598,4,3.984894,2,1.475576,NaN,108,106,98.286121,7,6.912284,80,73.872865,62,57.298992,74,68.710669,4,4.043016,1,1.331659,NaN,109,104,95.044368,11,9.992295,73,66.53952,59,54.377264,71,65.090415,2,1.52311,5,4.666036,NaN,113,112,99.45641,14,12.643195,83,73.045475,62,54.863919,73,64.350057,2,1.38499,1,0.447576,NaN,114,112,98.362116,28,24.780959,81,70.856675,58,51.325237,76,66.767589,1,0.59207,2,1.439502,NaN,125,122,97.913493,28,22.491817,81,65.215469,65,52.059358,84,67.126713
19,Atlántico,647,645,99.709568,579,89.51612,637,98.485062,533,82.410245,617,95.367536,212,32.735443,1,0.203681,NaN,679,677,99.661182,596,87.739493,664,97.823963,576,84.790441,654,96.291359,177,26.125967,2,0.275254,NaN,720,718,99.772579,647,89.900485,699,97.056507,639,88.734723,687,95.510442,234,32.534642,1,0.161263,NaN,754,754,99.910334,676,89.575833,738,97.837789,669,88.756484,720,95.417522,225,29.851781,1,0.079989,NaN,774,774,99.902606,721,93.101875,757,97.747026,674,87.036464,743,95.998007,205,26.424879,1,0.082239,NaN,795,795,99.921189,733,92.201186,766,96.309859,713,89.696759,758,95.364325,168,21.067912,0,0.022579,NaN,817,816,99.867014,741,90.694115,799,97.781066,698,85.400496,790,96.68685
20,Bogotá D.C.,2601,2598,99.886449,2407,92.528686,2590,99.574587,2585,99.368704,2582,99.247791,1492,57.351556,0,0.001527,NaN,2692,2692,99.996926,2434,90.445978,2689,99.906487,2684,99.708267,2687,99.845265,1359,50.478771,0,0.000656,NaN,2692,2692,99.998431,2520,93.633383,2675,99.376016,2671,99.230858,2688,99.843347,1373,51.007417,0,0.000431,NaN,2865,2864,99.973595,2659,92.823493,2838,99.068639,2828,98.722324,2847,99.35897,1390,48.510222,1,0.024136,NaN,2940,2940,99.996254,2750,93.523532,2927,99.552525,2914,99.093271,2927,99.55689,1209,41.124078,0,0.000437,NaN,3018,3018,99.998042,2797,92.689922,3001,99.432475,2997,99.295378,3015,99.88631,1051,34.832339,0,0.000211,NaN,3098,3095,99.899412,2945,95.053505,3094,99.865296,3077,99.295359,3092,99.777664
21,Bolívar,582,561,96.320887,400,68.724973,446,76.547353,267,45.894185,421,72.319714,88,15.189648,20,3.375555,NaN,601,591,98.346625,411,68.289814,490,81.437795,273,45.409377,427,70.962926,84,13.990988,9,1.561486,NaN,656,638,97.281531,417,63.521104,524,79.927472,296,45.178758,483,73.606928,104,15.854093,16,2.408687,NaN,656,629,95.901965,423,64.535852,529,80.66879,307,46.860594,458,69.74234,102,15.496134,23,3.569894,NaN,674,664,98.503569,453,67.207584,580,86.124585,342,50.771559,510,75.708507,59,8.773831,6,0.956859,NaN,692,688,99.407567,469,67.825996,600,86.781592,334,48.212712,512,74.067938,80,11.570415,4,0.571712,NaN,710,703,99.009708,481,67.772394,607,85.487942,370,52.082151,533,75.13392
22,Boyacá,424,418,98.575592,209,49.208881,347,81.752312,256,60.293453,264,62.20617,30,7.045438,5,1.102089,NaN,447,440,98.377521,248,55.41737,382,85.503172,277,61.925636,285,63.733971,18,4.027302,5,1.139312,NaN,423,421,99.491768,245,57.822122,394,93.155395,267,63.181445,278,65.705389,22,5.239214,1,0.18283,NaN,433,428,98.919665,261,60.349751,384,88.611837,271,62.513673,285,65.819128,18,4.093791,3,0.771093,NaN,441,438,99.410337,279,63.252341,394,89.52016,289,65.566539,296,67.104993,10,2.322554,1,0.258359,NaN,448,447,99.713731,291,65.035423,427,95.287465,294,65.641219,311,69.480456,11,2.447835,0,0.060929,NaN,455,454,99.604914,293,64.269419,427,93.689994,296,65.046865,315,69.257378
23,Caldas,340,339,99.770298,218,64.192446,308,90.786985,283,83.144603,292,85.859853,86,25.454912,0,0.118737,NaN,350,349,99.802574,223,63.719593,311,88.751681,285,81.33296,300,85.663567,73,20.81389,0,0.057147,NaN,367,366,99.870994,243,66.233077,338,92.128085,306,83.607071,326,89.015949,80,21.745019,0,0.129006,NaN,355,353,99.238294,246,69.072229,320,89.92773,296,83.30033,304,85.50193,72,20.129164,3,0.704553,NaN,363,362,99.787384,256,70.590102,334,92.059725,304,83.607811,315,86.634589,74,20.422565,0,0.109032,NaN,371,370,99.803673,262,70.465166,347,93.507489,310,83.629245,325,87.552752,53,14.364962,0,0.053509,NaN,380,380,99.98223,274,72.267349,352,92.846003,310,81.582154,339,89.288298
24,Caquetá,133,122,91.677039,45,33.720014,96,72.091353,84,63.136519,92,69.196399,8,5.813855,9,7.025621,NaN,134,123,92.218192,45,33.429494,96,71.768036,81,60.476715,94,70.1447,6,4.127643,10,7.129428,NaN,131,124,94.502055,58,44.020402,101,77.261662,85,65.091413,98,74.890937,4,2.706035,6,4.735707,NaN,139,128,91.6051,67,48.059998,102,72.900049,89,63.808918,103,73.785833,3,1.82937,11,7.789417,NaN,144,140,97.411876,67,46.355233,116,80.575629,92,64.140989,108,74.935458,3,2.394407,3,2.196774,NaN,148,146,98.46854,82,55.554021,117,79.201567,98,66.185863,112,75.491031,2,1.587504,2,1.32328,NaN,153,151,98.649544,88,57.393394,116,76.021829,105,68.913177,112,73.486462
25,Casanare,140,136,97.696656,102,73.007035,118,84.437217,99,70.882354,108,77.587278,4,2.960478,2,1.521949,NaN,146,141,96.582842,108,74.326077,121,82.752084,102,69.645716,112,76.757413,4,2.568108,3,2.247592,NaN,148,143,96.458213,112,75.993413,121,81.866713,102,69.162219,114,77.072946,3,2.074781,3,2.17813,NaN,154,147,95.956867,121,78.680355,125,81.070843,110,71.627817,120,77.961258,2,1.581545,4,2.474979,NaN,157,153,97.165361,132,83.847812,129,82.244543,111,70.798128,123,78.511157,2,1.504287,3,1.739619,NaN,161,157,97.787343,137,85.45823,134,83.210751,116,72.206101,127,78.909512,3,1.755521,2,1.430174,NaN,165,162,98.296433,141,85.692793,140,84.72816,116,70.299659,133,80.693438
26,Cauca,456,445,97.467075,134,29.468401,358,78.434516,203,44.406955,205,45.041608,23,5.071207,9,1.941086,NaN,481,471,98.077531,139,28.89345,379,78.885438,201,41.761709,205,42.731189,19,4.038533,6,1.198808,NaN,480,467,97.338431,132,27.562324,395,82.312396,202,42.040524,208,43.395529,27,5.556111,9,1.967605,NaN,559,509,91.072924,156,27.858425,406,72.553361,228,40.769737,247,44.199847,19,3.324713,43,7.671377,NaN,574,559,97.325349,152,26.506118,430,74.784235,233,40.518532,245,42.644688,27,4.750444,13,2.294925,NaN,590,583,98.817728,171,28.935068,465,78.912517,253,42.914185,265,45.000022,17,2.809088,5,0.856605,NaN,604,601,99.384159,166,27.441586,513,84.790356,257,42.483242,264,43.71138
27,Cesar,341,328,96.393587,219,64.411567,298,87.471469,257,75.507374,270,79.293499,39,11.41557,11,3.147524,NaN,365,353,96.528647,246,67.219575,316,86.529788,267,73.080198,288,78.825475,31,8.601755,11,2.890425,NaN,376,366,97.51768,238,63.389457,337,89.674095,270,71.854526,304,80.850087,29,7.707055,8,2.159853,NaN,400,390,97.572656,276,68.959345,350,87.48386,309,77.443808,321,80.455802,37,9.202304,8,2.125336,NaN,412,405,98.228811,282,68.518551,362,87.836644,305,74.095407,322,78.065892,38,9.256384,7,1.648655,NaN,425,416,97.99421,296,69.772794,379,89.231062,322,75.919554,338,79.628874,22,5.234306,8,1.785288,NaN,438,436,99.599924,323,73.868398,398,90.948821,337,76.977094,359,82.054932
28,Córdoba,495,485,98.025156,234,47.392233,376,75.965681,192,38.909355,275,55.60177,31,6.26796,9,1.854566,NaN,510,502,98.454332,240,47.195566,349,68.462298,205,40.240412,287,56.389974,35,6.921458,5,1.00341,NaN,532,530,99.482013,253,47.589232,391,73.458235,228,42.882332,290,54.563021,21,3.895573,2,0.321376,NaN,589,580,98.593051,296,50.292131,417,70.87546,250,42.521759,337,57.258899,23,3.963979,8,1.323971,NaN,603,601,99.718636,295,48.966513,428,70.97981,260,43.120871,337,55.865339,22,3.619394,1,0.236711,NaN,618,615,99.569846,319,51.712671,464,75.126013,287,46.488923,361,58.410462,12,1.871456,2,0.321976,NaN,632,629,99.572846,315,49.795439,455,72.03863,273,43.266617,382,60.395016
29,Cundinamarca,974,968,99.326439,673,69.035859,892,91.496433,752,77.197916,807,82.790223,192,19.739345,4,0.395282,NaN,1054,1051,99.664561,693,65.709203,946,89.704096,786,74.539644,896,84.990603,149,14.120851,2,0.193856,NaN,1100,1095,99.510408,788,71.628165,1056,96.027954,847,77.019997,947,86.094666,144,13.119034,2,0.184769,NaN,1190,1179,99.089371,891,74.889642,1106,92.988827,940,78.970969,1051,88.356713,167,13.998943,8,0.654432,NaN,1244,1241,99.715618,963,77.398693,1198,96.226227,996,80.010525,1084,87.126208,148,11.924943,2,0.121892,NaN,1299,1297,99.82231,1048,80.667215,1262,97.097887,1042,80.181472,1153,88.728356,148,11.371618,1,0.046817,NaN,1355,1350,99.655594,1082,79.815438,1316,97.120999,1104,81.508361,1194,88.09234

In [ ]:
# Eliminar filas del 1 al 10 y del 45 hacia abajo en df_ipm
indices_a_eliminar = list(range(0, 15)) + list(range(49, len(df_variables['Cuadro 4'])))
df_variables['Cuadro 4'] = df_variables['Cuadro 4'].drop(indices_a_eliminar).reset_index(drop=True)

print(f"df_variables[Cuadro 4] ahora tiene {len(df_variables['Cuadro 4'])} filas")

df_variables[Cuadro 4] ahora tiene 34 filas

In [ ]:
# Eliminar solo la fila 0
df_variables['Cuadro 4'] = df_variables['Cuadro 4'].drop([0]).reset_index(drop=True)

print(f"df_variables[Cuadro 4] final: {len(df_variables['Cuadro 4'])} filas")

df_variables[Cuadro 4] final: 33 filas

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

df_variables['Cuadro 4']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107
0,Amazonas,22,18,84.775373,0,0,5,24.714111,5,22.606574,9,41.689856,0,1.095645,3,13.973816,NaN,22,19,84.739833,0,0,8,34.232493,4,20.120939,11,50.408573,0,0.654533,3,13.458602,NaN,25,21,83.185346,0,0,12,45.693424,9,35.842857,14,54.21727,0,1.324161,4,14.123484,NaN,21,17,81.658053,0,0,11,51.690644,7,33.572958,11,53.242601,0,0.082343,3,14.671259,NaN,22,18,83.189868,0,0,9,43.295595,9,42.31667,12,53.297217,0,0.438473,3,13.644207,NaN,27,24,89.81654,0,0,11,41.669085,10,38.664363,15,57.627583,0,0.547153,2,8.287656,NaN,27,26,95.680352,0,0,12,45.313996,8,30.561509,14,52.353126
1,Antioquia,2107,2097,99.515343,1219,57.842454,1834,87.014696,1648,78.208897,1853,87.953745,914,43.362966,6,0.28363,NaN,2133,2128,99.77298,1327,62.213251,1949,91.380361,1786,83.771091,1933,90.632939,863,40.460299,3,0.142762,NaN,2180,2173,99.676108,1292,59.295509,2040,93.594901,1785,81.870767,1992,91.388589,664,30.459011,4,0.16116,NaN,2328,2319,99.617013,1455,62.47882,2134,91.638061,1905,81.825793,2146,92.153376,628,26.964929,4,0.152185,NaN,2406,2405,99.942551,1551,64.471532,2239,93.068042,1945,80.854308,2203,91.570975,583,24.240132,1,0.029654,NaN,2485,2482,99.903999,1634,65.750123,2344,94.32906,2027,81.560507,2288,92.060694,533,21.454382,1,0.059011,NaN,2563,2560,99.882231,1751,68.325579,2368,92.390274,2090,81.572539,2364,92.258793
2,Arauca,92,89,96.173138,5,5.222817,70,75.657706,53,57.610288,65,69.851717,4,3.968952,2,2.509328,NaN,103,101,97.959604,5,5.105166,75,72.781188,61,59.550304,72,69.889598,4,3.984894,2,1.475576,NaN,108,106,98.286121,7,6.912284,80,73.872865,62,57.298992,74,68.710669,4,4.043016,1,1.331659,NaN,109,104,95.044368,11,9.992295,73,66.53952,59,54.377264,71,65.090415,2,1.52311,5,4.666036,NaN,113,112,99.45641,14,12.643195,83,73.045475,62,54.863919,73,64.350057,2,1.38499,1,0.447576,NaN,114,112,98.362116,28,24.780959,81,70.856675,58,51.325237,76,66.767589,1,0.59207,2,1.439502,NaN,125,122,97.913493,28,22.491817,81,65.215469,65,52.059358,84,67.126713
3,Atlántico,647,645,99.709568,579,89.51612,637,98.485062,533,82.410245,617,95.367536,212,32.735443,1,0.203681,NaN,679,677,99.661182,596,87.739493,664,97.823963,576,84.790441,654,96.291359,177,26.125967,2,0.275254,NaN,720,718,99.772579,647,89.900485,699,97.056507,639,88.734723,687,95.510442,234,32.534642,1,0.161263,NaN,754,754,99.910334,676,89.575833,738,97.837789,669,88.756484,720,95.417522,225,29.851781,1,0.079989,NaN,774,774,99.902606,721,93.101875,757,97.747026,674,87.036464,743,95.998007,205,26.424879,1,0.082239,NaN,795,795,99.921189,733,92.201186,766,96.309859,713,89.696759,758,95.364325,168,21.067912,0,0.022579,NaN,817,816,99.867014,741,90.694115,799,97.781066,698,85.400496,790,96.68685
4,Bogotá D.C.,2601,2598,99.886449,2407,92.528686,2590,99.574587,2585,99.368704,2582,99.247791,1492,57.351556,0,0.001527,NaN,2692,2692,99.996926,2434,90.445978,2689,99.906487,2684,99.708267,2687,99.845265,1359,50.478771,0,0.000656,NaN,2692,2692,99.998431,2520,93.633383,2675,99.376016,2671,99.230858,2688,99.843347,1373,51.007417,0,0.000431,NaN,2865,2864,99.973595,2659,92.823493,2838,99.068639,2828,98.722324,2847,99.35897,1390,48.510222,1,0.024136,NaN,2940,2940,99.996254,2750,93.523532,2927,99.552525,2914,99.093271,2927,99.55689,1209,41.124078,0,0.000437,NaN,3018,3018,99.998042,2797,92.689922,3001,99.432475,2997,99.295378,3015,99.88631,1051,34.832339,0,0.000211,NaN,3098,3095,99.899412,2945,95.053505,3094,99.865296,3077,99.295359,3092,99.777664
5,Bolívar,582,561,96.320887,400,68.724973,446,76.547353,267,45.894185,421,72.319714,88,15.189648,20,3.375555,NaN,601,591,98.346625,411,68.289814,490,81.437795,273,45.409377,427,70.962926,84,13.990988,9,1.561486,NaN,656,638,97.281531,417,63.521104,524,79.927472,296,45.178758,483,73.606928,104,15.854093,16,2.408687,NaN,656,629,95.901965,423,64.535852,529,80.66879,307,46.860594,458,69.74234,102,15.496134,23,3.569894,NaN,674,664,98.503569,453,67.207584,580,86.124585,342,50.771559,510,75.708507,59,8.773831,6,0.956859,NaN,692,688,99.407567,469,67.825996,600,86.781592,334,48.212712,512,74.067938,80,11.570415,4,0.571712,NaN,710,703,99.009708,481,67.772394,607,85.487942,370,52.082151,533,75.13392
6,Boyacá,424,418,98.575592,209,49.208881,347,81.752312,256,60.293453,264,62.20617,30,7.045438,5,1.102089,NaN,447,440,98.377521,248,55.41737,382,85.503172,277,61.925636,285,63.733971,18,4.027302,5,1.139312,NaN,423,421,99.491768,245,57.822122,394,93.155395,267,63.181445,278,65.705389,22,5.239214,1,0.18283,NaN,433,428,98.919665,261,60.349751,384,88.611837,271,62.513673,285,65.819128,18,4.093791,3,0.771093,NaN,441,438,99.410337,279,63.252341,394,89.52016,289,65.566539,296,67.104993,10,2.322554,1,0.258359,NaN,448,447,99.713731,291,65.035423,427,95.287465,294,65.641219,311,69.480456,11,2.447835,0,0.060929,NaN,455,454,99.604914,293,64.269419,427,93.689994,296,65.046865,315,69.257378
7,Caldas,340,339,99.770298,218,64.192446,308,90.786985,283,83.144603,292,85.859853,86,25.454912,0,0.118737,NaN,350,349,99.802574,223,63.719593,311,88.751681,285,81.33296,300,85.663567,73,20.81389,0,0.057147,NaN,367,366,99.870994,243,66.233077,338,92.128085,306,83.607071,326,89.015949,80,21.745019,0,0.129006,NaN,355,353,99.238294,246,69.072229,320,89.92773,296,83.30033,304,85.50193,72,20.129164,3,0.704553,NaN,363,362,99.787384,256,70.590102,334,92.059725,304,83.607811,315,86.634589,74,20.422565,0,0.109032,NaN,371,370,99.803673,262,70.465166,347,93.507489,310,83.629245,325,87.552752,53,14.364962,0,0.053509,NaN,380,380,99.98223,274,72.267349,352,92.846003,310,81.582154,339,89.288298
8,Caquetá,133,122,91.677039,45,33.720014,96,72.091353,84,63.136519,92,69.196399,8,5.813855,9,7.025621,NaN,134,123,92.218192,45,33.429494,96,71.768036,81,60.476715,94,70.1447,6,4.127643,10,7.129428,NaN,131,124,94.502055,58,44.020402,101,77.261662,85,65.091413,98,74.890937,4,2.706035,6,4.735707,NaN,139,128,91.6051,67,48.059998,102,72.900049,89,63.808918,103,73.785833,3,1.82937,11,7.789417,NaN,144,140,97.411876,67,46.355233,116,80.575629,92,64.140989,108,74.935458,3,2.394407,3,2.196774,NaN,148,146,98.46854,82,55.554021,117,79.201567,98,66.185863,112,75.491031,2,1.587504,2,1.32328,NaN,153,151,98.649544,88,57.393394,116,76.021829,105,68.913177,112,73.486462
9,Casanare,140,136,97.696656,102,73.007035,118,84.437217,99,70.882354,108,77.587278,4,2.960478,2,1.521949,NaN,146,141,96.582842,108,74.326077,121,82.752084,102,69.645716,112,76.757413,4,2.568108,3,2.247592,NaN,148,143,96.458213,112,75.993413,121,81.866713,102,69.162219,114,77.072946,3,2.074781,3,2.17813,NaN,154,147,95.956867,121,78.680355,125,81.070843,110,71.627817,120,77.961258,2,1.581545,4,2.474979,NaN,157,153,97.165361,132,83.847812,129,82.244543,111,70.798128,123,78.511157,2,1.504287,3,1.739619,NaN,161,157,97.787343,137,85.45823,134,83.210751,116,72.206101,127,78.909512,3,1.755521,2,1.430174,NaN,165,162,98.296433,141,85.692793,140,84.72816,116,70.299659,133,80.693438
10,Cauca,456,445,97.467075,134,29.468401,358,78.434516,203,44.406955,205,45.041608,23,5.071207,9,1.941086,NaN,481,471,98.077531,139,28.89345,379,78.885438,201,41.761709,205,42.731189,19,4.038533,6,1.198808,NaN,480,467,97.338431,132,27.562324,395,82.312396,202,42.040524,208,43.395529,27,5.556111,9,1.967605,NaN,559,509,91.072924,156,27.858425,406,72.553361,228,40.769737,247,44.199847,19,3.324713,43,7.671377,NaN,574,559,97.325349,152,26.506118,430,74.784235,233,40.518532,245,42.644688,27,4.750444,13,2.294925,NaN,590,583,98.817728,171,28.935068,465,78.912517,253,42.914185,265,45.000022,17,2.809088,5,0.856605,NaN,604,601,99.384159,166,27.441586,513,84.790356,257,42.483242,264,43.71138
11,Cesar,341,328,96.393587,219,64.411567,298,87.471469,257,75.507374,270,79.293499,39,11.41557,11,3.147524,NaN,365,353,96.528647,246,67.219575,316,86.529788,267,73.080198,288,78.825475,31,8.601755,11,2.890425,NaN,376,366,97.51768,238,63.389457,337,89.674095,270,71.854526,304,80.850087,29,7.707055,8,2.159853,NaN,400,390,97.572656,276,68.959345,350,87.48386,309,77.443808,321,80.455802,37,9.202304,8,2.125336,NaN,412,405,98.228811,282,68.518551,362,87.836644,305,74.095407,322,78.065892,38,9.256384,7,1.648655,NaN,425,416,97.99421,296,69.772794,379,89.231062,322,75.919554,338,79.628874,22,5.234306,8,1.785288,NaN,438,436,99.599924,323,73.868398,398,90.948821,337,76.977094,359,82.054932
12,Córdoba,495,485,98.025156,234,47.392233,376,75.965681,192,38.909355,275,55.60177,31,6.26796,9,1.854566,NaN,510,502,98.454332,240,47.195566,349,68.462298,205,40.240412,287,56.389974,35,6.921458,5,1.00341,NaN,532,530,99.482013,253,47.589232,391,73.458235,228,42.882332,290,54.563021,21,3.895573,2,0.321376,NaN,589,580,98.593051,296,50.292131,417,70.87546,250,42.521759,337,57.258899,23,3.963979,8,1.323971,NaN,603,601,99.718636,295,48.966513,428,70.97981,260,43.120871,337,55.865339,22,3.619394,1,0.236711,NaN,618,615,99.569846,319,51.712671,464,75.126013,287,46.488923,361,58.410462,12,1.871456,2,0.321976,NaN,632,629,99.572846,315,49.795439,455,72.03863,273,43.266617,382,60.395016
13,Cundinamarca,974,968,99.326439,673,69.035859,892,91.496433,752,77.197916,807,82.790223,192,19.739345,4,0.395282,NaN,1054,1051,99.664561,693,65.709203,946,89.704096,786,74.539644,896,84.990603,149,14.120851,2,0.193856,NaN,1100,1095,99.510408,788,71.628165,1056,96.027954,847,77.019997,947,86.094666,144,13.119034,2,0.184769,NaN,1190,1179,99.089371,891,74.889642,1106,92.988827,940,78.970969,1051,88.356713,167,13.998943,8,0.654432,NaN,1244,1241,99.715618,963,77.398693,1198,96.226227,996,80.010525,1084,87.126208,148,11.924943,2,0.121892,NaN,1299,1297,99.82231,1048,80.667215,1262,97.097887,1042,80.181472,1153,88.728356,148,11.371618,1,0.046817,NaN,1355,1350,99.655594,1082,79.815438,1316,97.120999,1104,81.508361,1194,88.09234
14,Chocó,165,133,80.357327,1,0.723466,56,33.873914,28,17.147601,76,46.259368,7,4.348366,26,15.659304,NaN,170,163,95.867382,2,1.19539,60,35.087832,36,21.384608,88,51.835196,6,3.338772,7,3.937877,NaN,182,164,89.851518,0,0,51,27.806773,26,14.303029,87,47.63622,2,1.158294,18,9.765829,NaN,172,140,81.760555,0,0,47,27.560117,24,13.858942,79,45.775124,3,1.691366,30,17.749205,NaN,176,161,91.445087,0,0,72,41.097386,38,21.756294,90,50.947706,3,1.650429,14,8.133116,NaN,181,173,95.478725,0,0,51,28.373024,29,16.194169,89,49.458189,1,0.603871,8,4.400361,NaN,185,179,96.55565,0,0,77,41.649333,31,16.715345,102,55.038846
15,Guainía,13,8,66.325744,0,0,3,23.501164,3,25.117794,5,37.88005,0,0.406347,4,28.858912,NaN,14,10,70.201433,0,0,3,21.140999,4,25.373308,5,38.333362,0,0.269593,4,29.042914,NaN,16,10,61.561723,0,0,3,19.535545,4,24.056327,6,35.687304,0,0.062812,5,34.985656,NaN,15,10,65.015455,0,0,3,22.94526,3,19.436489,5,32.198873,0,0.233268,5,32.302298,NaN,15,12,76.517847,0,0,4,24.417834,4,26.510153,6,37.619908,0,0.059299,3,22.073589,NaN,15,12,82.599583,0,0,5,35.089744,4,29.322166,5,34.149716,0,0.156308,2,15.614838,NaN,17,14,80.101273,0,0,4,21.664565,4,21.921511,5,28.140301
16,Guaviare,28,23,83.363316,5,16.998707,12,42.465176,12,41.017855,17,60.583139,0,0.793331,4,15.047217,NaN,31,26,85.783759,5,15.067613,12,39.737168,12,40.822881,18,57.931314,1,1.677758,4,12.800917,NaN,30,27,89.686617,5,16.117659,13,43.905282,13,43.768993,19,63.111836,0,0.845445,3,9.598868,NaN,31,26,86.267455,5,17.694606,14,46.041574,13,44.035218,18,60.4583,0,0.319812,4,12.626444,NaN,32,30,93.037546,5,15.910856,16,50.899567,15,47.306644,19,60.379917,0,0.324738,2,6.418881,NaN,30,28,94.503289,6,18.950539,18,59.065366,15,51.266945,20,67.430964,0,0.138822,1,4.531713,NaN,35,34,96.78954,8,24.009355,19,54.165302,17,48.529885,21,61.062541
17,Huila,349,346,99.090813,229,65.521962,296,84.754887,240,68.750155,244,69.748456,58,16.578885,2,0.610702,NaN,351,347,99.046164,229,65.230003,303,86.509806,233,66.486057,248,70.798404,50,14.32553,2,0.46168,NaN,351,348,99.100413,247,70.392993,323,92.014106,249,70.729617,253,71.883069,45,12.738673,1,0.279186,NaN,366,362,98.953012,245,66.96807,312,85.3771,250,68.385357,254,69.366466,48,13.191323,2,0.580335,NaN,374,373,99.633343,246,65.75569,329,87.817266,252,67.350903,259,69.22229,28,7.449654,1,0.250415,NaN,382,380,99.375942,261,68.378609,344,90.049545,260,68.142151,265,69.248884,36,9.319739,1,0.286729,NaN,390,389,99.67239,277,71.060836,358,91.72998,264,67.635736,273,70.015039
18,La Guajira,258,167,64.650376,91,35.38465,133,51.351925,95,36.623945,117,45.221617,8,2.909851,84,32.596165,NaN,282,185,65.600644,113,40.088513,143,50.804518,115,40.912909,139,49.387569,12,4.088854,91,32.277339,NaN,296,201,67.770291,111,37.454746,153,51.583094,127,42.753088,150,50.781885,5,1.647173,92,31.104426,NaN,295,179,60.742563,110,37.336536,138,46.769156,125,42.204933,150,50.756913,4,1.451066,115,38.995214,NaN,307,210,68.388383,125,40.656302,153,49.74174,128,41.607971,164,53.425656,6,1.951678,96,31.355653,NaN,318,220,69.110405,135,42.544202,174,54.641821,139,43.569966,163,51.148673,4,1.278347,95,29.915453,NaN,329,233,70.640208,146,44.214255,174,52.837821,156,47.25498,178,53.905208
19,Magdalena,366,350,95.459112,222,60.695606,290,79.146221,177,48.270845,275,75.194523,48,12.968872,16,4.339699,NaN,396,388,97.995937,230,58.151779,312,78.685249,188,47.417329,289,72.940133,41,10.263766,7,1.858186,NaN,404,394,97.520565,240,59.447735,327,80.922573,205,50.886872,298,73.938503,48,11.806112,9,2.27565,NaN,411,396,96.315134,277,67.251873,343,83.301129,220,53.555517,302,73.401559,23,5.677393,14,3.496076,NaN,422,416,98.725463,279,66.28985,360,85.394813,217,51.464669,319,75.704246,14,3.377908,4,1.015617,NaN,432,431,99.769807,288,66.806702,378,87.601195,234,54.12835,339,78.445389,23,5.297821,1,0.203871,NaN,442,437,99.060313,311,70.396964,390,88.305638,252,56.965887,325,73.618748
20,Meta,344,335,97.38647,225,65.311917,269,78.145242,270,78.622129,286,83.139019,47,13.534375,8,2.252376,NaN,354,340,96.177208,231,65.390758,278,78.5633,264,74.588839,288,81.356132,38,10.780345,8,2.340714,NaN,364,357,98.204421,237,65.277683,299,82.253735,284,78.051457,301,82.768795,45,12.417384,6,1.545736,NaN,370,358,96.750288,248,67.111384,306,82.823403,290,78.549362,315,85.173786,49,13.196941,11,2.862527,NaN,378,373,98.556568,260,68.650928,313,82.798064,293,77.440503,324,85.579452,20,5.20569,5,1.318648,NaN,386,380,98.36865,270,69.803613,324,83.815607,301,77.790069,332,85.91695,22,5.577011,4,1.156019,NaN,395,391,98.913949,280,70.865895,332,83.974144,315,79.872666,339,85.87484
21,Nariño,510,501,98.209729,23,4.561263,388,75.983703,200,39.146968,258,50.528016,37,7.191409,7,1.435827,NaN,538,530,98.603519,31,5.768594,393,73.001906,228,42.401386,285,53.024413,36,6.730363,6,1.031745,NaN,534,524,98.161545,28,5.226157,419,78.445894,243,45.463246,315,58.991118,34,6.449561,8,1.521847,NaN,577,563,97.635267,38,6.635377,408,70.636299,249,43.181382,327,56.747078,32,5.59737,12,2.1538,NaN,588,585,99.457394,47,7.911561,427,72.618854,262,44.497939,321,54.474129,36,6.047827,2,0.337822,NaN,600,587,97.924822,82,13.656173,447,74.477057,260,43.422289,353,58.840826,24,3.93102,12,2.043491,NaN,611,610,99.893532,83,13.60071,464,75.962322,255,41.813537,333,54.506294
22,Norte de Santander,460,451,98.079963,224,48.615696,397,86.205338,366,79.537428,386,83.925951,72,15.563225,7,1.463451,NaN,476,473,99.361805,220,46.295645,400,84.120629,374,78.481241,400,84.020478,87,18.185999,2,0.353205,NaN,508,503,99.155064,226,44.546808,440,86.629771,397,78.22453,425,83.743946,79,15.472358,2,0.449086,NaN,494,490,99.190542,256,51.911893,424,85.950384,399,80.930876,418,84.64573,65,13.182489,3,0.560511,NaN,504,500,99.265188,306,60.856347,434,86.235892,420,83.461339,429,85.24687,45,8.951174,3,0.524182,NaN,514,511,99.514231,315,61.258544,448,87.174405,432,84.019969,441,85.858862,42,8.240027,2,0.414593,NaN,524,523,99.775558,311,59.410002,459,87.571767,437,83.426532,448,85.527627
23,Putumayo,117,99,84.42118,14,11.777095,58,49.21256,60,50.894495,65,55.286534,2,1.613385,15,12.893807,NaN,125,110,87.862167,18,14.233804,60,48.103381,61,48.424284,71,57.005574,2,1.346273,13,10.46474,NaN,125,109,87.30198,19,14.973015,72,57.742044,67,53.421458,75,59.788644,1,0.728423,14,11.580428,NaN,146,116,79.882369,18,12.61023,67,45.859857,75,51.568281,88,60.427123,1,0.66994,29,19.759608,NaN,151,132,87.889742,20,13.229941,82,54.409582,82,54.609741,96,63.726242,1,0.51335,16,10.505242,NaN,156,147,94.541121,27,17.082128,85,54.468976,86,55.296634,98,63.189187,0,0.258524,8,5.223354,NaN,161,147,91.052919,25,15.20525,90,56.036488,84,51.895691,98,60.600804
24,Quindío,190,188,99.08598,147,77.541187,185,97.345922,168,88.352611,180,94.811121,58,30.51445,1,0.438785,NaN,195,194,99.654965,151,77.482007,190,97.356995,178,91.091898,185,94.975425,48,24.615369,0,0.038358,NaN,210,209,99.482706,170,80.850773,205,97.810555,190,90.688402,199,94.657651,47,22.226272,1,0.254336,NaN,199,198,99.473054,165,82.766563,194,97.396708,181,91.063265,188,94.657622,35,17.729343,0,0.187856,NaN,204,203,99.668025,166,81.355558,200,97.833318,181,88.735438,195,95.58951,31,15.230127,0,0.040335,NaN,209,209,99.631119,178,84.828229,204,97.672509,185,88.489049,199,94.950442,34,16.349151,0,0.037167,NaN,215,214,99.756854,178,82.875582,210,98.038255,191,88.859846,205,95.780475
25,Risaralda,325,324,99.724906,231,71.127554,308,94.811442,272,83.616983,289,88.860767,96,29.426859,1,0.19535,NaN,335,334,99.770704,239,71.285316,321,95.879564,272,81.308565,297,88.850357,93,27.637822,0,0.079356,NaN,349,346,99.23335,264,75.77616,336,96.399694,297,84.995874,315,90.255495,92,26.368431,2,0.6413,NaN,333,331,99.429729,258,77.326487,319,95.656673,287,86.044276,301,90.228345,112,33.662554,1,0.406119,NaN,341,340,99.743747,274,80.30927,327,95.981251,293,85.918386,311,91.14204,70,20.489356,0,0.076777,NaN,349,348,99.580083,287,82.278498,338,96.718103,300,85.973501,320,91.519644,96,27.354629,1,0.305304,NaN,357,355,99.521517,293,82.159887,333,93.121357,307,85.997327,323,90.46009
26,San Andrés,16,16,99.797779,0,0,8,51.120404,5,28.904406,16,99.820315,2,15.175474,0,0,NaN,15,15,100,0,0,5,30.333614,3,19.208336,15,99.873523,1,9.625458,0,0,NaN,16,16,100,0,0,7,42.900388,3,19.936287,16,99.658331,1,7.337035,0,0,NaN,15,15,100,0,0,6,37.433978,4,27.523911,15,99.5558,0,2.719407,0,0,NaN,16,16,99.491744,0,0,7,43.187508,6,37.963916,15,97.265559,1,7.941088,0,0.09375,NaN,16,16,99.781831,0,0,8,50.797954,7,44.812124,16,100,0,2.156755,0,0,NaN,17,17,99.796985,0,0,7,40.601255,6,38.433812,16,99.434288

In [ ]:
print(df_variables['Cuadro 4'].columns.tolist())

['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97', 'Unnamed: 98', 'Unnamed: 99', 'Unnamed: 100', 'Unnamed: 101', 'Unnamed: 102', 'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107']

In [ ]:
# Colocar el nombre de las columnas en el orden que quiero que queden
df_variables['Cuadro 4'] = df_variables['Cuadro 4'][['Unnamed: 0', 'Unnamed: 97', 'Unnamed: 98', 'Unnamed: 100','Unnamed: 102','Unnamed: 104','Unnamed: 106' ]]
df_variables['Cuadro 4'].head(2)

,Unnamed: 0,Unnamed: 97,Unnamed: 98,Unnamed: 100,Unnamed: 102,Unnamed: 104,Unnamed: 106
0,Amazonas,27,26,0,12,8,14
1,Antioquia,2563,2560,1751,2368,2090,2364

In [ ]:
# Renombrar columnas
df_variables['Cuadro 4'] = df_variables['Cuadro 4'].rename(columns={
    'Unnamed: 0': 'Departamentos',
    'Unnamed: 97': 'total Hogares',
    'Unnamed: 98': 'total Energia',
    'Unnamed: 100': 'total Gas Natural',
    'Unnamed: 102': 'Total Acueducto',
    'Unnamed: 104': 'Total Alcantarillado',
    'Unnamed: 106': 'Total Recolección de Basura'
})

# Verificar resultado
df_variables['Cuadro 4'].head(2)

,Departamentos,total Hogares,total Energia,total Gas Natural,Total Acueducto,Total Alcantarillado,Total Recolección de Basura
0,Amazonas,27,26,0,12,8,14
1,Antioquia,2563,2560,1751,2368,2090,2364

In [ ]:
#Encontrar duplicados
df_variables['Cuadro 4'].duplicated().sum()

np.int64(0)

In [ ]:
# Ver la cantidad de valores nulos en cada columna
df_variables['Cuadro 4'].isna().sum()

Departamentos                  0
total Hogares                  0
total Energia                  0
total Gas Natural              0
Total Acueducto                0
Total Alcantarillado           0
Total Recolección de Basura    0
dtype: int64

In [ ]:
df_variables['Cuadro 4']

,Departamentos,total Hogares,total Energia,total Gas Natural,Total Acueducto,Total Alcantarillado,Total Recolección de Basura
0,Amazonas,27,26,0,12,8,14
1,Antioquia,2563,2560,1751,2368,2090,2364
2,Arauca,125,122,28,81,65,84
3,Atlántico,817,816,741,799,698,790
4,Bogotá D.C.,3098,3095,2945,3094,3077,3092
5,Bolívar,710,703,481,607,370,533
6,Boyacá,455,454,293,427,296,315
7,Caldas,380,380,274,352,310,339
8,Caquetá,153,151,88,116,105,112
9,Casanare,165,162,141,140,116,133
10,Cauca,604,601,166,513,257,264
11,Cesar,438,436,323,398,337,359
12,Córdoba,632,629,315,455,273,382
13,Cundinamarca,1355,1350,1082,1316,1104,1194
14,Chocó,185,179,0,77,31,102
15,Guainía,17,14,0,4,4,5
16,Guaviare,35,34,8,19,17,21
17,Huila,390,389,277,358,264,273
18,La Guajira,329,233,146,174,156,178
19,Magdalena,442,437,311,390,252,325
20,Meta,395,391,280,332,315,339
21,Nariño,611,610,83,464,255,333
22,Norte de Santander,524,523,311,459,437,448
23,Putumayo,161,147,25,90,84,98
24,Quindío,215,214,178,210,191,205
25,Risaralda,357,355,293,333,307,323
26,San Andrés,17,17,0,7,6,16
27,Santander,821,818,646,763,651,679
28,Sucre,299,297,170,261,163,192
29,Tolima,504,502,399,456,379,390
30,Valle,1610,1605,1347,1570,1467,1548
31,Vaupés,15,14,0,4,4,4
32,Vichada,41,18,0,20,0,10

# 2.2.3.Hogares con acceso a internet

In [ ]:
df_variables['Cuadro 5']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Volver al inicio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Dominio,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,Total hogares,Hogares con acceso a internet,NaN,Hogares con acceso a internet por tipo de conexión,NaN,NaN,NaN,NaN,NaN,NaN,Total hogares,Hogares con acceso a internet,NaN,Hogares con acceso a internet por tipo de conexión,NaN,NaN,NaN,NaN,NaN,NaN,Total hogares,Hogares con acceso a internet,NaN,Hogares con acceso a internet por tipo de conexión,NaN,NaN,NaN,NaN,NaN,NaN,Total hogares,Hogares con acceso a internet,NaN,Hogares con acceso a internet por tipo de conexión,NaN,NaN,NaN,NaN,NaN,NaN,Total hogares,Hogares con acceso a internet,NaN,Hogares con acceso a internet por tipo de conexión,NaN,NaN,NaN,NaN,NaN,NaN,Total hogares,Hogares con acceso a internet,NaN,Hogares con acceso a internet por tipo de conexión,NaN,NaN,NaN,NaN,NaN,NaN,Total hogares,Hogares con acceso a internet,NaN,Hogares con acceso a internet por tipo de conexión,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,Fijo,NaN,Móvil,NaN,Fijo - Móvil,NaN,NaN,NaN,NaN,NaN,Fijo,NaN,Móvil,NaN,Fijo - Móvil,NaN,NaN,NaN,NaN,NaN,Fijo,NaN,Móvil,NaN,Fijo - Móvil,NaN,NaN,NaN,NaN,NaN,Fijo,NaN,Móvil,NaN,Fijo - Móvil,NaN,NaN,NaN,NaN,NaN,Fijo,NaN,Móvil,NaN,Fijo - Móvil,NaN,NaN,NaN,NaN,NaN,Fijo,NaN,Móvil,NaN,Fijo - Móvil,NaN,NaN,NaN,NaN,NaN,Fijo,NaN,Móvil,NaN,Fijo - Móvil,NaN
13,NaN,NaN,Total,%,Total,%,Total,%,Total,%,NaN,NaN,Total,%,Total,%,Total,%,Total,%,NaN,NaN,Total,%,Total,%,Total,%,Total,%,NaN,NaN,Total,%,Total,%,Total,%,Total,%,NaN,NaN,Total,%,Total,%,Total,%,Total,%,NaN,NaN,Total,%,Total,%,Total,%,Total,%,NaN,NaN,Total,%,Total,%,Total,%,Total,%
14,Total nacional,15403,8049,52.259692,6189,76.892883,4481,55.669364,2621,32.562246,NaN,15999,8312,51.949639,6327,76.116741,4185,50.354985,2200,26.471726,NaN,16417,9280,56.526243,7581,81.691082,4358,46.959819,2659,28.650901,NaN,17068,10334,60.547223,8070,78.092407,5111,49.46085,2847,27.553257,NaN,17526,10422,59.465579,7667,73.566496,5837,56.006443,3082,29.57294,NaN,18009,11514,63.935914,8283,71.932944,7040,61.138997,3808,33.071941,NaN,18489,12138,65.648787,8930,73.56688,7624,62.810074,4415,36.376955
15,Cabecera,11742,7422,63.204218,6008,80.956661,3984,53.67473,2570,34.631391,NaN,12221,7531,61.621645,6093,80.899056,3556,47.218426,2118,28.117482,NaN,12551,8357,66.582737,7194,86.082122,3730,44.628534,2567,30.710656,NaN,13160,9211,69.988417,7574,82.230837,4344,47.164125,2707,29.394962,NaN,13554,9142,67.450245,7175,78.488055,4871,53.27949,2904,31.767545,NaN,13952,9833,70.475733,7688,78.186812,5693,57.89397,3548,36.080783,NaN,14343,10399,72.50387,8196,78.811145,6327,60.844047,4124,39.655192
16,Centros poblados y rural disperso,3660,628,17.14776,181,28.839232,497,79.255645,51,8.094877,NaN,3778,781,20.660505,234,29.973567,629,80.618735,83,10.592302,NaN,3865,923,23.868823,387,41.913966,628,68.078232,92,9.992198,NaN,3908,1124,28.754127,496,44.171501,767,68.286099,140,12.457601,NaN,3972,1280,32.217543,491,38.404606,966,75.489058,178,13.893664,NaN,4057,1681,41.445254,595,35.360831,1347,80.11565,260,15.476481,NaN,4146,1739,41.93581,734,42.202685,1297,74.568227,292,16.770912
17,Amazonas,22,1,5.363327,0,27.452033,1,89.192105,0,16.644139,NaN,22,2,10.012139,0,7.849513,2,93.70931,0,1.558823,NaN,25,4,15.594533,1,12.767802,4,96.664712,0,9.432514,NaN,21,4,16.674161,0,0,4,100,0,0,NaN,22,8,37.560034,1,11.183842,8,93.779925,0,4.963768,NaN,27,8,29.079445,1,13.441315,7,89.484176,0,2.925491,NaN,27,11,41.313456,3,26.468764,10,92.451942,2,18.920706
18,Antioquia,2107,1168,55.447024,989,84.664267,528,45.158538,348,29.822804,NaN,2133,1259,59.042475,980,77.862226,539,42.804545,260,20.666771,NaN,2180,1264,57.966474,1157,91.53785,474,37.522659,367,29.060509,NaN,2328,1415,60.761921,1233,87.160844,422,29.812472,240,16.973315,NaN,2406,1461,60.699925,1142,78.162587,738,50.513269,419,28.675856,NaN,2485,1755,70.610256,1319,75.189123,861,49.056659,425,24.245783,NaN,2563,1715,66.913331,1521,88.712266,823,47.987991,629,36.700257
19,Arauca,92,19,20.023546,10,52.276923,13,71.813915,4,24.090838,NaN,103,27,25.777475,13,48.211189,18,65.944638,4,14.155827,NaN,108,39,36.01285,20,51.375994,26,66.765951,7,18.141945,NaN,109,47,43.167855,17,37.044161,36,77.232633,7,14.276794,NaN,113,47,41.683967,20,43.000701,34,72.874613,7,15.875315,NaN,114,42,36.738633,21,49.61617,29,68.788329,8,18.404499,NaN,125,43,34.269963,25,57.959559,32,74.647113,14,32.606672
20,Atlántico,647,352,54.407485,262,74.383471,180,51.132815,90,25.516285,NaN,679,340,50.126201,255,74.901634,156,45.837222,71,20.738856,NaN,720,422,58.628048,359,84.988933,216,51.15105,153,36.139983,NaN,754,458,60.706475,379,82.692265,175,38.311945,96,21.00421,NaN,774,413,53.310646,368,89.241108,157,37.93325,112,27.174358,NaN,795,470,59.074706,384,81.669865,284,60.429807,198,42.099672,NaN,817,481,58.857319,396,82.382344,261,54.301557,176,36.683901
21,Bogotá D.C.,2601,1983,76.246487,1760,88.709869,1075,54.195647,851,42.905516,NaN,2692,2017,74.919903,1863,92.38039,872,43.221902,718,35.602292,NaN,2692,2099,77.987176,1980,94.315373,822,39.176875,703,33.492248,NaN,2865,2336,81.524891,2080,89.063237,1010,43.241981,755,32.305217,NaN,2940,2336,79.430787,1954,83.681511,1256,53.785287,875,37.466799,NaN,3018,2335,77.3828,2059,88.17428,1128,48.297821,852,36.472101,NaN,3098,2562,82.676456,2075,81.013297,1634,63.794889,1148,44.808186
22,Bolívar,582,167,28.608228,128,77.11144,75,45.20481,37,22.31625,NaN,601,186,30.908516,148,79.546862,82,44.034361,44,23.581224,NaN,656,201,30.670127,165,81.787357,81,40.067273,44,21.85463,NaN,656,302,46.081743,216,71.405085,183,60.549985,97,31.95507,NaN,674,325,48.256676,192,59.101687,185,56.968303,52,16.06999,NaN,692,337,48.76978,213,63.122543,213,63.026026,88,26.148569,NaN,710,428,60.216858,274,64.126039,301,70.48495,148,34.610989
23,Boyacá,424,202,47.499035,108,53.493562,144,71.617269,51,25.11083,NaN,447,159,35.461137,99,62.612531,102,64.19141,43,26.803941,NaN,423,252,59.543251,135,53.453012,192,76.191317,75,29.644329,NaN,433,278,64.26758,154,55.464925,200,71.833203,76,27.298129,NaN,441,238,54.103832,138,57.819418,159,66.865052,59,24.684469,NaN,448,274,61.121876,146,53.345249,206,75.338864,79,28.684112,NaN,455,276,60.588365,176,63.823101,189,68.559285,89,32.382385
24,Caldas,340,159,46.69202,144,91.065906,69,43.613601,55,34.679507,NaN,350,162,46.319606,134,82.726002,65,39.922779,37,22.648781,NaN,367,211,57.575927,182,86.135462,73,34.741738,44,20.8772,NaN,355,237,66.784896,190,79.897203,95,39.951437,47,19.848641,NaN,363,227,62.558364,184,80.81059,96,42.421111,53,23.231701,NaN,371,224,60.279301,198,88.48388,92,41.21889,66,29.70277,NaN,380,254,66.928288,209,82.178092,183,72.04881,138,54.226902
25,Caquetá,133,45,33.949255,19,42.209194,37,82.640169,11,24.849363,NaN,134,52,38.700867,24,47.251445,35,68.30361,8,15.555054,NaN,131,56,42.464858,32,58.028737,29,52.166705,6,10.195443,NaN,139,84,60.544816,30,35.145433,71,84.212052,16,19.357485,NaN,144,73,50.859047,31,42.428106,53,72.481209,11,14.909315,NaN,148,101,67.929829,39,38.824089,86,85.794279,25,24.618368,NaN,153,95,62.046296,39,40.88465,80,84.534595,24,25.419246
26,Casanare,140,63,45.381028,30,47.683741,42,65.498324,8,13.182065,NaN,146,57,39.328868,31,54.55939,39,67.876875,13,22.436265,NaN,148,81,54.831176,50,61.601081,59,72.433893,28,34.034975,NaN,154,82,53.104324,45,55.708216,49,59.666221,13,15.374437,NaN,157,95,60.181405,45,47.335153,67,70.768932,17,18.104085,NaN,161,78,48.591871,45,57.800959,57,73.372949,24,31.173907,NaN,165,117,70.978841,52,44.511233,110,93.984592,45,38.495825
27,Cauca,456,135,29.66365,91,67.223924,78,57.47036,33,24.694284,NaN,481,148,30.835464,91,61.556537,73,49.513721,16,11.070258,NaN,480,162,33.755929,141,86.943815,47,28.840196,26,15.784011,NaN,559,177,31.664158,153,86.183407,38,21.622637,14,7.806044,NaN,574,185,32.117124,139,75.519932,102,55.393127,57,30.913059,NaN,590,265,44.916373,169,63.801389,183,69.003078,87,32.804467,NaN,604,296,49.04174,186,62.88564,194,65.471198,84,28.356838
28,Cesar,341,136,39.840421,84,61.828119,70,51.576782,18,13.404901,NaN,365,130,35.672764,86,65.989605,57,43.810942,13,9.800547,NaN,376,175,46.457606,111,63.719413,89,50.804494,25,14.523907,NaN,400,179,44.781554,105,58.477563,100,55.678728,25,14.156292,NaN,412,214,51.852477,121,56.565864,149,69.667735,56,26.233599,NaN,425,248,58.363058,122,49.225779,179,72.387666,54,21.613445,NaN,438,282,64.45018,151,53.364748,225,79.820686,94,33.185434
29,Córdoba,495,112,22.561968,86,76.935852,58,52.005662,32,28.941514,NaN,510,146,28.740435,91,62.191024,79,53.970708,24,16.161732,NaN,532,161,30.247443,91,56.352443,98,60.974218,28,17.326661,NaN,589,178,30.26603,126,70.942576,83,46.78577,32,17.728346,NaN,603,162,26.864916,100,61.519888,94,57.951319,32,19.471207,NaN,618,276,44.73057,124,44.726892,194,70.216188,41,14.94308,NaN,632,298,47.214104,155,52.017587,190,63.718361,47,15.735948
30,Cundinamarca,974,501,51.46756,380,75.731304,306,61.044135,184,36.775439,NaN,1054,513,48.660147,345,67.290598,329,64.224095,162,31.514692,NaN,1100,628,57.12009,493,78.498039,296,47.169976,161,25.668015,NaN,1190,724,60.837047,580,80.09731,381,52.680085,237,32.777395,NaN,1244,800,64.315579,609,76.128917,430,53.664684,238,29.7936,NaN,1299,884,68.027506,589,66.654863,642,72.666385,348,39.321248,NaN,1355,907,66.923736,627,69.125828,644,70.960449,364,40.086278
31,Chocó,165,24,14.425476,18,76.520279,9,36.900133,3,13.420411,NaN,170,28,16.637371,21,73.843358,11,40.179816,4,14.023174,NaN,182,24,13.22484,17,72.499127,11,47.537624,5,20.036751,NaN,172,25,14.624333,16,64.629353,12,48.079249,3,12.708602,NaN,176,35,19.997197,16,44.272991,24,67.303408,4,11.576399,NaN,181,33,18.01221,17,50.945764,21,63.907473,5,14.853237,NaN,185,53,28.734242,23,43.061007,40,74.624675,9,17.685683
32,Guainía,13,2,11.875067,1,38.989606,1,76.54295,0,15.532555,NaN,14,2,16.065487,1,32.076236,2,79.91174,0,11.987976,NaN,16,3,18.940346,1,20.075454,3,91.959713,0,12.035167,NaN,15,4,24.136464,0,9.506324,3,95.226893,0,4.733217,NaN,15,3,18.86974,0,3.792153,3,97.82996,0,1.622113,NaN,15,7,46.58076,1,12.04527,7,93.814182,0,5.859452,NaN,17,5,31.45357,1,11.988014,5,96.217618,0,8.205632
33,Guaviare,28,6,22.849973,2,34.449497,5,77.229051,1,11.678548,NaN,31,8,24.645239,3,37.404363,6,74.909827,1,12.314189,NaN,30,9,30.193614,5,57.309338,6,60.641422,2,17.95076,NaN,31,11,35.727571,5,48.197288,7,68.575384,2,16.772672,NaN,32,10,30.227803,5,54.968375,6,58.879518,1,13.847893,NaN,30,13,44.997362,5,36.878787,11,80.700031,2,17.578818,NaN,35,20,57.606176,8,39.949062,16,77.849825,4,17.798887
34,Huila,349,147,42.194038,84,57.187199,95,64.648775,32,21.835974,NaN,351,127,36.124767,92,72.321741,69,54.775695,34,27.097437,NaN,351,155,44.240145,132,84.58244,72,46.32793,48,30.91037,NaN,366,188,51.519788,139,73.778421,118,62.583306,68,36.361727,NaN,374,210,56.035363,146,69.777311,109,52.060103,46,21.837414,NaN,382,259,67.747932,188,72.745829,146,56.26028,75,29.006109,NaN,390,276,70.844733,206,74.560842,175,63.452678,105,38.013521
35,La Guajira,258,52,20.290828,21,39.336253,39,74.641738,7,13.97799,NaN,282,59,20.947157,25,42.242906,42,70.8407,8,13.083606,NaN,296,64,21.45573,37,57.48419,38,60.058715,11,17.542905,NaN,295,85,28.616248,34,40.144318,63,74.4448,12,14.589118,NaN,307,87,28.304049,39,44.374312,63,72.564754,15,16.939067,NaN,318,93,29.357061,46,49.660525,63,67.042843,16,16.703368,NaN,329,99,30.111959,53,53.136385,70,71.075498,24,24.211884
36,Magdalena,366,124,33.81069,83,66.95579,84,67.793108,43,34.748898,NaN,396,146,36.860302,97,66.599799,66,45.029503,17,11.629301,NaN,404,155,38.301929,105,67.810946,63,40.854748,13,8.665694,NaN,411,201,48.796929,109,54.255045,128,63.974955,37,18.23,NaN,422,210,49.721182,110,52.303203,137,65.553539,37,17.856741,NaN,432,248,57.511122,121,48.932079,205,82.715039,79,31.647117,NaN,442,243,55.104564,121,49.7693,169,69.649333,47,19.418634
37,Meta,344,186,54.005696,124,66.760439,100,53.798019,38,20.558458,NaN,354,195,55.163141,128,65.290215,120,61.203102,52,26.493317,NaN,364,202,55.521138,132,65.260967,129,63.956408,59,29.217374,NaN,370,234,63.189784,156,66.837553,162,69.254663,84,36.092216,NaN,378,229,60.516884,167,72.775343,140,61.084999,77,33.860342,NaN,386,291,75.299738,162,55.67167,220,75.601927,91,31.273597,NaN,395,304,77.029701,169,55.644993,243,80.013625,108,35.658617
38,Nariño,510,187,36.593259,91,48.600458,135,72.100246,39,20.700704,NaN,538,198,36.819946,95,47.914497,128,64.392256,24,12.306753,NaN,534,217,40.61599,148,68.34423,117,53.989361,48,22.333591,NaN,577,242,41.859929,174,72.023413,138,57.280223,71,29.303635,NaN,588,312,53.030006,184,58.882091,210,67.148983,81,26.031073,NaN,600,325,54.197418,176,54.168454,239,73.603224,90,27.771678,NaN,611,334,54.642146,183,54.896439,218,65.241186,67,20.137625
39,Norte de Santander,460,200,43.395334,132,65.90513,141,70.539014,73,36.444144,NaN,476,215,45.120817,151,70.458048,95,44.248784,32,14.706833,NaN,508,291,57.315481,199,68.289619,185,63.633756,93,31.923375,NaN,494,313,63.43862,188,60.100663,211,67.478878,86,27.579541,NaN,504,283,56.118082,164,58.064622,171,60.596201,53,18.660823,NaN,514,283,55.112027,216,76.165099,151,53.387637,84,29.552736,NaN,524,317,60.542548,254,80.110533,167,52.761808,104,32.872341
40,Putumayo,117,19,16.623488,15,74.759405,11,56.457101,6,31.216506,NaN,125,23,18.699205,15,63.179998,12,53.035684,4,16.215682,NaN,125,38,30.623287,22,58.760381,19,49.386874,3,8.147255,NaN,146,42,29.114138,21,49.835137,25,58.78977,4,8.624907,NaN,151,58,38.692546,24,40.699092,40,68.916731,6,9.615823,NaN,156,79,50.597422,26,33.099412,62,78.840503,9,11.939915,NaN,161,62,38.646157,41,66.023436,29,47.262507,8,13.285943
41,Quindío,190,121,63.923447,95,77.848934,83,68.378015,56,46.226949,NaN,195,113,57.881491,96,84.746919,49,43.180252,32,27.927171,NaN,210,121,57.440174,103,85.85156,48,39.596033,31,25.447593,NaN,199,125,63.020566,105,83.959038,39,31.455385,19,15.414423,NaN,204,142,69.776837,113,79.418216,66,46.421978,37,25.840194,NaN,209,149,70.97817,116,77.993917,103,69.18994,70,47.183857,NaN,215,136,63.413601,114,84.050958,77,56.643882,55,40.69484
42,Risaralda,325,198,61.055758,164,82.493702,94,47.404776,59,29.898478,NaN,335,223,66.623435,166,74.355211,125,55.965166,68,30.320377,NaN,349,222,63.493734,194,87.592754,86,38.614285,58,26.207039,NaN,333,242,72.759629,191,78.570918,147,60.720984,95,39.291902,NaN,341,217,63.664465,184,84.583864,78,35.782887,44,20.366752,NaN,349,232,66.408459,196,84.616461,106,45.839309,71,30.45577,NaN,357,261,73.005137,220,84.232141,132,50.800062,91,35.032203
43,San Andrés,16,7,41.089208,4,59.930549,5,77.861453,3,37.792003,NaN,15,3,19.021212,1,43.058728,2,69.53907,0,12.597797,NaN,16,5,32.468113,1,26.780772,4,81.51917,0,8.299941,NaN,15,6,41.32762,2,28.740402,5,81.829184,1,10.569587,NaN,16,8,49.046425,3,33.263648,7,87.426542,2,20.69019,NaN,16,7,40.60645,3,51.559485,6,97.025735,3,48.58522,NaN,17,10,57.597481,7,70.406604,9,95.108886,6,65.515489
44,Santander,714,432,60.470798,326,75.423969,235,54.433116,129,29.857085,NaN,738,443,59.964615,308,69.498827,284,64.07228,149,33.571107,NaN,755,475,62.931632,365,76.747389,201,42.191546,90,18.938935,NaN,769,492,64.054715,405,82.205595,216,43.929777,129,26.135372,NaN,786,508,64.610438,362,71.358914,270,53.265614,125,24.624529,NaN,803,534,66.44951,367,68.845503,415,77.691386,248,46.536889,NaN,821,536,65.247728,384,71.721911,358,66.737893,206,38.459804
45,Sucre,247,76,30.565845,45,59.472482,47,62.229126,16,21.701608,NaN,271,62,23.056719,40,64.486306,30,48.199875,8,12.686182,NaN,274,71,26.119973,53,73.601543,25,34.830839,6,8.432382,NaN,278,104,37.468888,63,60.578751,52,49.698901,11,10.277651,NaN,285,121,42.420047,65,53.558183,81,67.051452,25,20.609635,NaN,292,123,42.215721,61,49.766549,81,65.867063,19,15.633612,NaN,299,139,46.442235,65,46.64967,111,79.932727,37,26.582397
46,Tolima,444,235,52.995975,148,62.94734,149,63.439519,62,26.386859,NaN,479,244,51.022734,152,62.163292,143,58.503094,51,20.666386,NaN,467,290,62.136443,162,55.960034,211,72.896434,84,28.856469,NaN,480,322,67.025986,195,60.662743,210,65.182043,83,25.844785,NaN,488,276,56.517047,192,69.795868,187,67.962065,104,37.757934,NaN,496,311,62.793653,209,67.083201,219,70.518135,117,37.601336,NaN,504,385,76.467153,229,59.429964,321,83.237231,164,42.667194

In [ ]:
# Eliminar filas del 1 al 10 y del 45 hacia abajo en df_ipm
indices_a_eliminar = list(range(0, 16)) + list(range(50, len(df_variables['Cuadro 5'])))
df_variables['Cuadro 5'] = df_variables['Cuadro 5'].drop(indices_a_eliminar).reset_index(drop=True)

print(f"df_variables[Cuadro 5] ahora tiene {len(df_variables['Cuadro 5'])} filas")

df_variables[Cuadro 5] ahora tiene 34 filas

In [ ]:
# Eliminar solo la fila 0
df_variables['Cuadro 5'] = df_variables['Cuadro 5'].drop([0]).reset_index(drop=True)

print(f"df_variables[Cuadro 5] final: {len(df_variables['Cuadro 5'])} filas")

df_variables[Cuadro 5] final: 33 filas

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

df_variables['Cuadro 5']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69
0,Amazonas,22,1,5.363327,0,27.452033,1,89.192105,0,16.644139,NaN,22,2,10.012139,0,7.849513,2,93.70931,0,1.558823,NaN,25,4,15.594533,1,12.767802,4,96.664712,0,9.432514,NaN,21,4,16.674161,0,0,4,100,0,0,NaN,22,8,37.560034,1,11.183842,8,93.779925,0,4.963768,NaN,27,8,29.079445,1,13.441315,7,89.484176,0,2.925491,NaN,27,11,41.313456,3,26.468764,10,92.451942,2,18.920706
1,Antioquia,2107,1168,55.447024,989,84.664267,528,45.158538,348,29.822804,NaN,2133,1259,59.042475,980,77.862226,539,42.804545,260,20.666771,NaN,2180,1264,57.966474,1157,91.53785,474,37.522659,367,29.060509,NaN,2328,1415,60.761921,1233,87.160844,422,29.812472,240,16.973315,NaN,2406,1461,60.699925,1142,78.162587,738,50.513269,419,28.675856,NaN,2485,1755,70.610256,1319,75.189123,861,49.056659,425,24.245783,NaN,2563,1715,66.913331,1521,88.712266,823,47.987991,629,36.700257
2,Arauca,92,19,20.023546,10,52.276923,13,71.813915,4,24.090838,NaN,103,27,25.777475,13,48.211189,18,65.944638,4,14.155827,NaN,108,39,36.01285,20,51.375994,26,66.765951,7,18.141945,NaN,109,47,43.167855,17,37.044161,36,77.232633,7,14.276794,NaN,113,47,41.683967,20,43.000701,34,72.874613,7,15.875315,NaN,114,42,36.738633,21,49.61617,29,68.788329,8,18.404499,NaN,125,43,34.269963,25,57.959559,32,74.647113,14,32.606672
3,Atlántico,647,352,54.407485,262,74.383471,180,51.132815,90,25.516285,NaN,679,340,50.126201,255,74.901634,156,45.837222,71,20.738856,NaN,720,422,58.628048,359,84.988933,216,51.15105,153,36.139983,NaN,754,458,60.706475,379,82.692265,175,38.311945,96,21.00421,NaN,774,413,53.310646,368,89.241108,157,37.93325,112,27.174358,NaN,795,470,59.074706,384,81.669865,284,60.429807,198,42.099672,NaN,817,481,58.857319,396,82.382344,261,54.301557,176,36.683901
4,Bogotá D.C.,2601,1983,76.246487,1760,88.709869,1075,54.195647,851,42.905516,NaN,2692,2017,74.919903,1863,92.38039,872,43.221902,718,35.602292,NaN,2692,2099,77.987176,1980,94.315373,822,39.176875,703,33.492248,NaN,2865,2336,81.524891,2080,89.063237,1010,43.241981,755,32.305217,NaN,2940,2336,79.430787,1954,83.681511,1256,53.785287,875,37.466799,NaN,3018,2335,77.3828,2059,88.17428,1128,48.297821,852,36.472101,NaN,3098,2562,82.676456,2075,81.013297,1634,63.794889,1148,44.808186
5,Bolívar,582,167,28.608228,128,77.11144,75,45.20481,37,22.31625,NaN,601,186,30.908516,148,79.546862,82,44.034361,44,23.581224,NaN,656,201,30.670127,165,81.787357,81,40.067273,44,21.85463,NaN,656,302,46.081743,216,71.405085,183,60.549985,97,31.95507,NaN,674,325,48.256676,192,59.101687,185,56.968303,52,16.06999,NaN,692,337,48.76978,213,63.122543,213,63.026026,88,26.148569,NaN,710,428,60.216858,274,64.126039,301,70.48495,148,34.610989
6,Boyacá,424,202,47.499035,108,53.493562,144,71.617269,51,25.11083,NaN,447,159,35.461137,99,62.612531,102,64.19141,43,26.803941,NaN,423,252,59.543251,135,53.453012,192,76.191317,75,29.644329,NaN,433,278,64.26758,154,55.464925,200,71.833203,76,27.298129,NaN,441,238,54.103832,138,57.819418,159,66.865052,59,24.684469,NaN,448,274,61.121876,146,53.345249,206,75.338864,79,28.684112,NaN,455,276,60.588365,176,63.823101,189,68.559285,89,32.382385
7,Caldas,340,159,46.69202,144,91.065906,69,43.613601,55,34.679507,NaN,350,162,46.319606,134,82.726002,65,39.922779,37,22.648781,NaN,367,211,57.575927,182,86.135462,73,34.741738,44,20.8772,NaN,355,237,66.784896,190,79.897203,95,39.951437,47,19.848641,NaN,363,227,62.558364,184,80.81059,96,42.421111,53,23.231701,NaN,371,224,60.279301,198,88.48388,92,41.21889,66,29.70277,NaN,380,254,66.928288,209,82.178092,183,72.04881,138,54.226902
8,Caquetá,133,45,33.949255,19,42.209194,37,82.640169,11,24.849363,NaN,134,52,38.700867,24,47.251445,35,68.30361,8,15.555054,NaN,131,56,42.464858,32,58.028737,29,52.166705,6,10.195443,NaN,139,84,60.544816,30,35.145433,71,84.212052,16,19.357485,NaN,144,73,50.859047,31,42.428106,53,72.481209,11,14.909315,NaN,148,101,67.929829,39,38.824089,86,85.794279,25,24.618368,NaN,153,95,62.046296,39,40.88465,80,84.534595,24,25.419246
9,Casanare,140,63,45.381028,30,47.683741,42,65.498324,8,13.182065,NaN,146,57,39.328868,31,54.55939,39,67.876875,13,22.436265,NaN,148,81,54.831176,50,61.601081,59,72.433893,28,34.034975,NaN,154,82,53.104324,45,55.708216,49,59.666221,13,15.374437,NaN,157,95,60.181405,45,47.335153,67,70.768932,17,18.104085,NaN,161,78,48.591871,45,57.800959,57,73.372949,24,31.173907,NaN,165,117,70.978841,52,44.511233,110,93.984592,45,38.495825
10,Cauca,456,135,29.66365,91,67.223924,78,57.47036,33,24.694284,NaN,481,148,30.835464,91,61.556537,73,49.513721,16,11.070258,NaN,480,162,33.755929,141,86.943815,47,28.840196,26,15.784011,NaN,559,177,31.664158,153,86.183407,38,21.622637,14,7.806044,NaN,574,185,32.117124,139,75.519932,102,55.393127,57,30.913059,NaN,590,265,44.916373,169,63.801389,183,69.003078,87,32.804467,NaN,604,296,49.04174,186,62.88564,194,65.471198,84,28.356838
11,Cesar,341,136,39.840421,84,61.828119,70,51.576782,18,13.404901,NaN,365,130,35.672764,86,65.989605,57,43.810942,13,9.800547,NaN,376,175,46.457606,111,63.719413,89,50.804494,25,14.523907,NaN,400,179,44.781554,105,58.477563,100,55.678728,25,14.156292,NaN,412,214,51.852477,121,56.565864,149,69.667735,56,26.233599,NaN,425,248,58.363058,122,49.225779,179,72.387666,54,21.613445,NaN,438,282,64.45018,151,53.364748,225,79.820686,94,33.185434
12,Córdoba,495,112,22.561968,86,76.935852,58,52.005662,32,28.941514,NaN,510,146,28.740435,91,62.191024,79,53.970708,24,16.161732,NaN,532,161,30.247443,91,56.352443,98,60.974218,28,17.326661,NaN,589,178,30.26603,126,70.942576,83,46.78577,32,17.728346,NaN,603,162,26.864916,100,61.519888,94,57.951319,32,19.471207,NaN,618,276,44.73057,124,44.726892,194,70.216188,41,14.94308,NaN,632,298,47.214104,155,52.017587,190,63.718361,47,15.735948
13,Cundinamarca,974,501,51.46756,380,75.731304,306,61.044135,184,36.775439,NaN,1054,513,48.660147,345,67.290598,329,64.224095,162,31.514692,NaN,1100,628,57.12009,493,78.498039,296,47.169976,161,25.668015,NaN,1190,724,60.837047,580,80.09731,381,52.680085,237,32.777395,NaN,1244,800,64.315579,609,76.128917,430,53.664684,238,29.7936,NaN,1299,884,68.027506,589,66.654863,642,72.666385,348,39.321248,NaN,1355,907,66.923736,627,69.125828,644,70.960449,364,40.086278
14,Chocó,165,24,14.425476,18,76.520279,9,36.900133,3,13.420411,NaN,170,28,16.637371,21,73.843358,11,40.179816,4,14.023174,NaN,182,24,13.22484,17,72.499127,11,47.537624,5,20.036751,NaN,172,25,14.624333,16,64.629353,12,48.079249,3,12.708602,NaN,176,35,19.997197,16,44.272991,24,67.303408,4,11.576399,NaN,181,33,18.01221,17,50.945764,21,63.907473,5,14.853237,NaN,185,53,28.734242,23,43.061007,40,74.624675,9,17.685683
15,Guainía,13,2,11.875067,1,38.989606,1,76.54295,0,15.532555,NaN,14,2,16.065487,1,32.076236,2,79.91174,0,11.987976,NaN,16,3,18.940346,1,20.075454,3,91.959713,0,12.035167,NaN,15,4,24.136464,0,9.506324,3,95.226893,0,4.733217,NaN,15,3,18.86974,0,3.792153,3,97.82996,0,1.622113,NaN,15,7,46.58076,1,12.04527,7,93.814182,0,5.859452,NaN,17,5,31.45357,1,11.988014,5,96.217618,0,8.205632
16,Guaviare,28,6,22.849973,2,34.449497,5,77.229051,1,11.678548,NaN,31,8,24.645239,3,37.404363,6,74.909827,1,12.314189,NaN,30,9,30.193614,5,57.309338,6,60.641422,2,17.95076,NaN,31,11,35.727571,5,48.197288,7,68.575384,2,16.772672,NaN,32,10,30.227803,5,54.968375,6,58.879518,1,13.847893,NaN,30,13,44.997362,5,36.878787,11,80.700031,2,17.578818,NaN,35,20,57.606176,8,39.949062,16,77.849825,4,17.798887
17,Huila,349,147,42.194038,84,57.187199,95,64.648775,32,21.835974,NaN,351,127,36.124767,92,72.321741,69,54.775695,34,27.097437,NaN,351,155,44.240145,132,84.58244,72,46.32793,48,30.91037,NaN,366,188,51.519788,139,73.778421,118,62.583306,68,36.361727,NaN,374,210,56.035363,146,69.777311,109,52.060103,46,21.837414,NaN,382,259,67.747932,188,72.745829,146,56.26028,75,29.006109,NaN,390,276,70.844733,206,74.560842,175,63.452678,105,38.013521
18,La Guajira,258,52,20.290828,21,39.336253,39,74.641738,7,13.97799,NaN,282,59,20.947157,25,42.242906,42,70.8407,8,13.083606,NaN,296,64,21.45573,37,57.48419,38,60.058715,11,17.542905,NaN,295,85,28.616248,34,40.144318,63,74.4448,12,14.589118,NaN,307,87,28.304049,39,44.374312,63,72.564754,15,16.939067,NaN,318,93,29.357061,46,49.660525,63,67.042843,16,16.703368,NaN,329,99,30.111959,53,53.136385,70,71.075498,24,24.211884
19,Magdalena,366,124,33.81069,83,66.95579,84,67.793108,43,34.748898,NaN,396,146,36.860302,97,66.599799,66,45.029503,17,11.629301,NaN,404,155,38.301929,105,67.810946,63,40.854748,13,8.665694,NaN,411,201,48.796929,109,54.255045,128,63.974955,37,18.23,NaN,422,210,49.721182,110,52.303203,137,65.553539,37,17.856741,NaN,432,248,57.511122,121,48.932079,205,82.715039,79,31.647117,NaN,442,243,55.104564,121,49.7693,169,69.649333,47,19.418634
20,Meta,344,186,54.005696,124,66.760439,100,53.798019,38,20.558458,NaN,354,195,55.163141,128,65.290215,120,61.203102,52,26.493317,NaN,364,202,55.521138,132,65.260967,129,63.956408,59,29.217374,NaN,370,234,63.189784,156,66.837553,162,69.254663,84,36.092216,NaN,378,229,60.516884,167,72.775343,140,61.084999,77,33.860342,NaN,386,291,75.299738,162,55.67167,220,75.601927,91,31.273597,NaN,395,304,77.029701,169,55.644993,243,80.013625,108,35.658617
21,Nariño,510,187,36.593259,91,48.600458,135,72.100246,39,20.700704,NaN,538,198,36.819946,95,47.914497,128,64.392256,24,12.306753,NaN,534,217,40.61599,148,68.34423,117,53.989361,48,22.333591,NaN,577,242,41.859929,174,72.023413,138,57.280223,71,29.303635,NaN,588,312,53.030006,184,58.882091,210,67.148983,81,26.031073,NaN,600,325,54.197418,176,54.168454,239,73.603224,90,27.771678,NaN,611,334,54.642146,183,54.896439,218,65.241186,67,20.137625
22,Norte de Santander,460,200,43.395334,132,65.90513,141,70.539014,73,36.444144,NaN,476,215,45.120817,151,70.458048,95,44.248784,32,14.706833,NaN,508,291,57.315481,199,68.289619,185,63.633756,93,31.923375,NaN,494,313,63.43862,188,60.100663,211,67.478878,86,27.579541,NaN,504,283,56.118082,164,58.064622,171,60.596201,53,18.660823,NaN,514,283,55.112027,216,76.165099,151,53.387637,84,29.552736,NaN,524,317,60.542548,254,80.110533,167,52.761808,104,32.872341
23,Putumayo,117,19,16.623488,15,74.759405,11,56.457101,6,31.216506,NaN,125,23,18.699205,15,63.179998,12,53.035684,4,16.215682,NaN,125,38,30.623287,22,58.760381,19,49.386874,3,8.147255,NaN,146,42,29.114138,21,49.835137,25,58.78977,4,8.624907,NaN,151,58,38.692546,24,40.699092,40,68.916731,6,9.615823,NaN,156,79,50.597422,26,33.099412,62,78.840503,9,11.939915,NaN,161,62,38.646157,41,66.023436,29,47.262507,8,13.285943
24,Quindío,190,121,63.923447,95,77.848934,83,68.378015,56,46.226949,NaN,195,113,57.881491,96,84.746919,49,43.180252,32,27.927171,NaN,210,121,57.440174,103,85.85156,48,39.596033,31,25.447593,NaN,199,125,63.020566,105,83.959038,39,31.455385,19,15.414423,NaN,204,142,69.776837,113,79.418216,66,46.421978,37,25.840194,NaN,209,149,70.97817,116,77.993917,103,69.18994,70,47.183857,NaN,215,136,63.413601,114,84.050958,77,56.643882,55,40.69484
25,Risaralda,325,198,61.055758,164,82.493702,94,47.404776,59,29.898478,NaN,335,223,66.623435,166,74.355211,125,55.965166,68,30.320377,NaN,349,222,63.493734,194,87.592754,86,38.614285,58,26.207039,NaN,333,242,72.759629,191,78.570918,147,60.720984,95,39.291902,NaN,341,217,63.664465,184,84.583864,78,35.782887,44,20.366752,NaN,349,232,66.408459,196,84.616461,106,45.839309,71,30.45577,NaN,357,261,73.005137,220,84.232141,132,50.800062,91,35.032203
26,San Andrés,16,7,41.089208,4,59.930549,5,77.861453,3,37.792003,NaN,15,3,19.021212,1,43.058728,2,69.53907,0,12.597797,NaN,16,5,32.468113,1,26.780772,4,81.51917,0,8.299941,NaN,15,6,41.32762,2,28.740402,5,81.829184,1,10.569587,NaN,16,8,49.046425,3,33.263648,7,87.426542,2,20.69019,NaN,16,7,40.60645,3,51.559485,6,97.025735,3,48.58522,NaN,17,10,57.597481,7,70.406604,9,95.108886,6,65.515489
27,Santander,714,432,60.470798,326,75.423969,235,54.433116,129,29.857085,NaN,738,443,59.964615,308,69.498827,284,64.07228,149,33.571107,NaN,755,475,62.931632,365,76.747389,201,42.191546,90,18.938935,NaN,769,492,64.054715,405,82.205595,216,43.929777,129,26.135372,NaN,786,508,64.610438,362,71.358914,270,53.265614,125,24.624529,NaN,803,534,66.44951,367,68.845503,415,77.691386,248,46.536889,NaN,821,536,65.247728,384,71.721911,358,66.737893,206,38.459804
28,Sucre,247,76,30.565845,45,59.472482,47,62.229126,16,21.701608,NaN,271,62,23.056719,40,64.486306,30,48.199875,8,12.686182,NaN,274,71,26.119973,53,73.601543,25,34.830839,6,8.432382,NaN,278,104,37.468888,63,60.578751,52,49.698901,11,10.277651,NaN,285,121,42.420047,65,53.558183,81,67.051452,25,20.609635,NaN,292,123,42.215721,61,49.766549,81,65.867063,19,15.633612,NaN,299,139,46.442235,65,46.64967,111,79.932727,37,26.582397
29,Tolima,444,235,52.995975,148,62.94734,149,63.439519,62,26.386859,NaN,479,244,51.022734,152,62.163292,143,58.503094,51,20.666386,NaN,467,290,62.136443,162,55.960034,211,72.896434,84,28.856469,NaN,480,322,67.025986,195,60.662743,210,65.182043,83,25.844785,NaN,488,276,56.517047,192,69.795868,187,67.962065,104,37.757934,NaN,496,311,62.793653,209,67.083201,219,70.518135,117,37.601336,NaN,504,385,76.467153,229,59.429964,321,83.237231,164,42.667194
30,Valle,1460,989,67.717847,747,75.543051,570,57.682253,328,33.225304,NaN,1472,1021,69.396628,775,75.833599,554,54.202195,307,30.035795,NaN,1551,1180,76.093117,989,83.781898,632,53.520392,440,37.30229,NaN,1511,1194,79.014032,958,80.262059,723,60.580886,488,40.842945,NaN,1544,1128,73.030554,850,75.366329,714,63.277919,436,38.644248,NaN,1577,1226,77.72645,941,76.787402,818,66.717256,533,43.504658,NaN,1610,1182,73.418889,961,81.323823,595,50.372614,375,31.696437
31,Vaupés,9,0,0.962221,0,26.041547,0,79.491851,0,5.533398,NaN,10,0,1.604913,0,0,0,100,0,0,NaN,11,0,3.124326,0,15.588128,0,84.411872,0,0,NaN,12,1,10.597167,0,0,1,100,0,0,NaN,14,1,4.071351,0,3.508979,1,96.956594,0,0.465573,NaN,15,2,10.07349,0,26.283169,1,81.85987,0,8.143038,NaN,15,4,26.548647,0,11.391081,4,91.225722,0,2.616803
32,Vichada,31,1,4.660032,1,45.625609,1,60.753231,0,6.37884,NaN,31,2,5.160867,1,45.809456,1,61.838058,0,7.647514,NaN,37,3,7.018976,1,30.501335,2,82.546096,0,13.047431,NaN,43,2,4.568055,1,27.529388,2,79.785709,0,7.315097,NaN,33,3,10.164213,1,18.95749,3,89.31544,0,8.272931,NaN,49,5,9.262845,1,16.416723,4,90.989762,0,7.406485,NaN,41,6,15.416443,1,9.249462,6,96.390038,0,5.6395

In [ ]:
print(df_variables['Cuadro 5'].columns.tolist())

['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69']

In [ ]:
# Colocar el nombre de las columnas en el orden que quiero que queden
df_variables['Cuadro 5'] = df_variables['Cuadro 5'][['Unnamed: 0', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 64','Unnamed: 66','Unnamed: 68']]
df_variables['Cuadro 5'].head(2)

  Unnamed: 0 Unnamed: 61 Unnamed: 62 Unnamed: 64 Unnamed: 66 Unnamed: 68
0   Amazonas          27          11           3          10           2
1  Antioquia        2563        1715        1521         823         629

In [ ]:
# Renombrar columnas
df_variables['Cuadro 4'] = df_variables['Cuadro 4'].rename(columns={
    'Unnamed: 0': 'Departamentos',
    'Unnamed: 61': 'total hogares',
    'Unnamed: 62': 'total Internet',
    'Unnamed: 64': 'total Tipo fijo',
    'Unnamed: 66': 'Total Tipo Movil',
    'Unnamed: 68': 'Total Tipo Fijo-Movil',
    })

# Verificar resultado
df_variables['Cuadro 4'].head(2)

,Departamentos,total Hogares,total Energia,total Gas Natural,Total Acueducto,Total Alcantarillado,Total Recolección de Basura
0,Amazonas,27,26,0,12,8,14
1,Antioquia,2563,2560,1751,2368,2090,2364

In [ ]:
#Encontrar duplicados
df_variables['Cuadro 5'].duplicated().sum()

np.int64(0)

In [ ]:
# Ver la cantidad de valores nulos en cada columna
df_variables['Cuadro 5'].isna().sum()

Unnamed: 0     0
Unnamed: 61    0
Unnamed: 62    0
Unnamed: 64    0
Unnamed: 66    0
Unnamed: 68    0
dtype: int64

In [ ]:
df_variables['Cuadro 5']

,Unnamed: 0,Unnamed: 61,Unnamed: 62,Unnamed: 64,Unnamed: 66,Unnamed: 68
0,Amazonas,27,11,3,10,2
1,Antioquia,2563,1715,1521,823,629
2,Arauca,125,43,25,32,14
3,Atlántico,817,481,396,261,176
4,Bogotá D.C.,3098,2562,2075,1634,1148
5,Bolívar,710,428,274,301,148
6,Boyacá,455,276,176,189,89
7,Caldas,380,254,209,183,138
8,Caquetá,153,95,39,80,24
9,Casanare,165,117,52,110,45
10,Cauca,604,296,186,194,84
11,Cesar,438,282,151,225,94
12,Córdoba,632,298,155,190,47
13,Cundinamarca,1355,907,627,644,364
14,Chocó,185,53,23,40,9
15,Guainía,17,5,1,5,0
16,Guaviare,35,20,8,16,4
17,Huila,390,276,206,175,105
18,La Guajira,329,99,53,70,24
19,Magdalena,442,243,121,169,47
20,Meta,395,304,169,243,108
21,Nariño,611,334,183,218,67
22,Norte de Santander,524,317,254,167,104
23,Putumayo,161,62,41,29,8
24,Quindío,215,136,114,77,55
25,Risaralda,357,261,220,132,91
26,San Andrés,17,10,7,9,6
27,Santander,821,536,384,358,206
28,Sucre,299,139,65,111,37
29,Tolima,504,385,229,321,164
30,Valle,1610,1182,961,595,375
31,Vaupés,15,4,0,4,0
32,Vichada,41,6,1,6,0

# 2.2.4.Tipo de tendencia ala vivienda

In [ ]:
df_variables['Cuadro 6']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Volver al inicio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Dominio,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,Total hogares,"Propia, totalmente pagada",NaN,"Propia, la están pagando",NaN,En arriendo o subarriendo,NaN,"Con permiso del propietario/a, sin pago alguno (usufructuario/a)",NaN,Posesión sin título (ocupante de hecho),NaN,Propiedad colectiva,NaN,NaN,Total hogares,"Propia, totalmente pagada",NaN,"Propia, la están pagando",NaN,En arriendo o subarriendo,NaN,"Con permiso del propietario/a, sin pago alguno (usufructuario/a)",NaN,Posesión sin título (ocupante de hecho),NaN,Propiedad colectiva,NaN,NaN,Total hogares,"Propia, totalmente pagada",NaN,"Propia, la están pagando",NaN,En arriendo o subarriendo,NaN,"Con permiso del propietario/a, sin pago alguno (usufructuario/a)",NaN,Posesión sin título (ocupante de hecho),NaN,Propiedad colectiva,NaN,NaN,Total hogares,"Propia, totalmente pagada",NaN,"Propia, la están pagando",NaN,En arriendo o subarriendo,NaN,"Con permiso del propietario/a, sin pago alguno (usufructuario/a)",NaN,Posesión sin título (ocupante de hecho),NaN,Propiedad colectiva,NaN,NaN,Total hogares,"Propia, totalmente pagada",NaN,"Propia, la están pagando",NaN,En arriendo o subarriendo,NaN,"Con permiso del propietario/a, sin pago alguno (usufructuario/a)",NaN,Posesión sin título (ocupante de hecho),NaN,Propiedad colectiva,NaN,NaN,Total hogares,"Propia, totalmente pagada",NaN,"Propia, la están pagando",NaN,En arriendo o subarriendo,NaN,"Con permiso del propietario/a, sin pago alguno (usufructuario/a)",NaN,Posesión sin título (ocupante de hecho),NaN,Propiedad colectiva,NaN,NaN,Total hogares,"Propia, totalmente pagada",NaN,"Propia, la están pagando",NaN,En arriendo o subarriendo,NaN,"Con permiso del propietario/a, sin pago alguno (usufructuario/a)",NaN,Posesión sin título (ocupante de hecho),NaN,Propiedad colectiva,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,Total,%,Total,%,Total,%,Total,%,Total,%,Total,%,NaN,NaN,Total,%,Total,%,Total,%,Total,%,Total,%,Total,%,NaN,NaN,Total,%,Total,%,Total,%,Total,%,Total,%,Total,%,NaN,NaN,Total,%,Total,%,Total,%,Total,%,Total,%,Total,%,NaN,NaN,Total,%,Total,%,Total,%,Total,%,Total,%,Total,%,NaN,NaN,Total,%,Total,%,Total,%,Total,%,Total,%,Total,%,NaN,NaN,Total,%,Total,%,Total,%,Total,%,Total,%,Total,%
13,Total nacional,15403,6764,43.915384,760,4.936889,5003,32.482777,2284,14.831984,408,2.652156,182,1.18081,NaN,15999,6649,41.559868,729,4.557167,5718,35.736724,2254,14.086826,359,2.246294,290,1.813121,NaN,16417,6126,37.314785,785,4.77895,6065,36.943564,2391,14.567542,558,3.400112,492,2.995047,NaN,17068,5921,34.69106,794,4.653417,6594,38.630685,2629,15.40526,607,3.553814,523,3.065765,NaN,17526,6117,34.902928,711,4.055223,7049,40.21986,2437,13.906503,787,4.493138,425,2.422347,NaN,18009,6368,35.358714,737,4.094437,7256,40.290797,2603,14.451042,604,3.353598,441,2.451412,NaN,18489,6659,36.016746,655,3.542742,7466,40.379804,2589,14.001308,703,3.801632,417,2.257767
14,Cabecera,11742,4871,41.486041,712,6.065095,4600,39.173899,1191,10.143989,274,2.336434,93,0.794542,NaN,12221,4776,39.076723,676,5.532979,5293,43.308788,1158,9.471569,182,1.487525,137,1.122416,NaN,12551,4442,35.389998,732,5.83491,5515,43.939954,1326,10.565681,280,2.234139,255,2.035319,NaN,13160,4391,33.36743,751,5.708494,6038,45.87836,1442,10.960629,309,2.346856,229,1.738231,NaN,13554,4495,33.161976,666,4.91433,6458,47.649172,1351,9.96972,366,2.700303,217,1.604498,NaN,13952,4654,33.355732,693,4.966314,6664,47.75966,1456,10.434115,277,1.986671,209,1.497508,NaN,14343,4928,34.359887,613,4.276182,6845,47.721127,1458,10.163507,303,2.115454,196,1.363844
15,Centros poblados y rural disperso,3660,1893,51.709138,48,1.317409,403,11.0165,1093,29.87188,134,3.665048,89,2.420025,NaN,3778,1874,49.592894,53,1.400395,425,11.240946,1096,29.017273,178,4.700927,153,4.047564,NaN,3865,1684,43.565331,52,1.349831,550,14.223514,1065,27.563171,278,7.186488,236,6.111665,NaN,3908,1530,39.148366,43,1.10046,556,14.224237,1187,30.372494,298,7.618227,295,7.536217,NaN,3972,1622,40.844005,45,1.123484,590,14.866994,1086,27.340954,421,10.611268,207,5.213295,NaN,4057,1714,42.246988,44,1.096043,593,14.605306,1147,28.265292,327,8.054474,233,5.731897,NaN,4146,1731,41.748126,42,1.005641,621,14.984834,1131,27.276961,399,9.634429,222,5.350009
16,Amazonas,22,8,35.831677,0,0.313797,3,14.409997,1,6.692381,7,30.822032,3,11.930116,NaN,22,5,24.599212,0,0.176252,4,19.278111,1,6.018098,2,6.861215,10,43.067112,NaN,25,6,23.382076,0,0.316858,5,20.63128,5,17.891925,5,19.504343,5,18.273517,NaN,21,5,21.813015,0,0.313065,3,14.309585,2,11.585233,6,29.792295,5,22.186807,NaN,22,4,20.132034,0,0.317491,4,20.314841,2,7.642862,2,7.924215,9,43.668557,NaN,27,9,34.112195,0,0.379568,8,28.387525,2,6.693432,1,3.812666,7,26.614615,NaN,27,10,37.593603,0,0.154345,4,16.445119,2,8.508608,4,13.543407,6,23.754919
17,Antioquia,2107,876,41.549115,87,4.125916,779,36.951854,318,15.083524,35,1.669532,13,0.620059,NaN,2133,928,43.49536,94,4.415472,846,39.675134,222,10.410579,19,0.88448,24,1.118976,NaN,2180,830,38.062357,81,3.710226,902,41.360093,287,13.189121,32,1.478808,48,2.199394,NaN,2328,844,36.25988,109,4.690148,1013,43.523646,272,11.698942,46,1.970199,43,1.857186,NaN,2406,906,37.661666,81,3.357509,1091,45.343044,242,10.037716,34,1.392325,53,2.207741,NaN,2485,933,37.531899,84,3.386019,1116,44.921004,242,9.754635,46,1.83966,64,2.566784,NaN,2563,934,36.432476,90,3.498242,1152,44.940944,314,12.261027,48,1.866411,26,1.000901
18,Arauca,92,45,49.04491,1,1.505645,22,24.078127,17,17.864926,6,6.622218,1,0.884174,NaN,103,41,39.729296,1,0.596565,31,29.92211,24,23.128772,6,6.146615,0,0.476643,NaN,108,40,36.652423,1,1.002627,35,32.30806,22,20.288923,9,7.902099,2,1.845868,NaN,109,33,30.696476,1,0.84613,37,34.067105,26,24.163514,9,8.033302,2,2.193472,NaN,113,39,34.321048,1,0.836815,36,32.234915,23,20.378096,13,11.460656,1,0.768469,NaN,114,38,33.339716,1,1.135118,39,34.611624,24,20.839826,11,9.389039,1,0.684678,NaN,125,37,29.569393,2,1.271427,48,38.533602,22,17.782974,14,11.367265,2,1.475339
19,Atlántico,647,333,51.412696,18,2.747844,162,24.98682,89,13.714089,35,5.381954,11,1.756597,NaN,679,331,48.697925,12,1.771067,205,30.138922,95,14.042408,21,3.132311,15,2.217367,NaN,720,351,48.778324,18,2.439422,213,29.566976,83,11.498243,20,2.729466,36,4.987567,NaN,754,338,44.798012,29,3.815838,237,31.443293,96,12.779093,34,4.449646,20,2.714118,NaN,774,354,45.727593,18,2.315028,243,31.357968,127,16.385032,30,3.926628,2,0.28775,NaN,795,318,39.941429,23,2.873451,279,35.133795,145,18.247081,21,2.621067,9,1.183176,NaN,817,351,42.913298,24,2.979369,253,30.948588,153,18.667064,30,3.648756,7,0.842926
20,Bogotá D.C.,2601,1054,40.502206,237,9.112026,1118,42.988785,163,6.25957,14,0.521083,16,0.61633,NaN,2692,891,33.085753,224,8.31229,1366,50.765832,169,6.263981,14,0.505677,29,1.066467,NaN,2692,864,32.081072,244,9.075048,1331,49.432667,176,6.550398,34,1.251499,43,1.609315,NaN,2865,898,31.342024,266,9.279599,1393,48.626848,214,7.458092,40,1.399457,54,1.89398,NaN,2940,917,31.202212,221,7.504835,1549,52.667519,196,6.65639,28,0.959909,30,1.009136,NaN,3018,927,30.702668,243,8.038569,1557,51.588365,257,8.516586,22,0.719935,13,0.433877,NaN,3098,1069,34.511032,206,6.654311,1566,50.537514,201,6.48106,18,0.579661,38,1.236423
21,Bolívar,582,300,51.534897,6,1.011085,117,20.061702,117,20.102098,35,6.028509,7,1.26171,NaN,601,300,49.869902,6,0.982518,136,22.670144,107,17.76817,38,6.286807,15,2.422459,NaN,656,246,37.525827,16,2.410098,143,21.840683,146,22.213634,61,9.235181,44,6.774577,NaN,656,217,33.125932,8,1.25498,174,26.508908,159,24.223464,77,11.713128,21,3.173587,NaN,674,240,35.555666,8,1.178511,173,25.712646,110,16.250567,101,15.022016,42,6.280594,NaN,692,257,37.173378,8,1.14762,199,28.815856,170,24.645845,41,5.900927,16,2.316374,NaN,710,297,41.772243,6,0.898016,202,28.382629,144,20.295449,55,7.699194,7,0.952468
22,Boyacá,424,184,43.394264,23,5.518275,123,28.975807,81,19.154449,7,1.696355,5,1.26085,NaN,447,190,42.391582,19,4.319657,153,34.276861,72,16.08615,7,1.640357,6,1.285394,NaN,423,174,41.085253,18,4.177836,141,33.35264,82,19.319409,6,1.462279,3,0.602584,NaN,433,164,37.80059,13,3.069065,147,34.031772,90,20.762708,4,0.972812,15,3.363053,NaN,441,162,36.835165,18,4.109628,169,38.392365,69,15.607343,11,2.600759,11,2.454739,NaN,448,164,36.617154,17,3.699145,183,40.733254,69,15.481405,13,2.826842,3,0.6422,NaN,455,200,43.843135,12,2.632635,170,37.429993,62,13.608185,7,1.522273,4,0.963779
23,Caldas,340,127,37.492934,21,6.075701,124,36.631692,53,15.573293,4,1.3123,10,2.914081,NaN,350,139,39.777388,22,6.232334,122,34.885662,55,15.742433,4,1.25874,7,2.103443,NaN,367,131,35.824743,23,6.351987,145,39.641629,58,15.833574,4,0.981312,5,1.366755,NaN,355,128,36.125416,18,4.996399,141,39.67269,58,16.254655,4,1.01597,7,1.934871,NaN,363,127,34.917531,24,6.509559,148,40.686893,56,15.289477,6,1.602925,4,0.993614,NaN,371,129,34.787955,19,5.165838,167,44.996201,44,11.901129,3,0.903279,8,2.245598,NaN,380,146,38.554821,16,4.169974,166,43.812062,35,9.217125,3,0.706492,13,3.539526
24,Caquetá,133,55,41.564486,3,1.939582,38,28.471476,29,22.000928,8,5.647043,1,0.376485,NaN,134,49,36.471363,3,2.083227,42,31.437062,31,23.286196,8,6.021456,1,0.700695,NaN,131,50,38.384707,3,2.657538,42,31.671803,29,21.841344,6,4.44363,1,1.000978,NaN,139,42,30.357416,1,1.031482,52,37.108498,35,24.890389,7,4.82547,2,1.786744,NaN,144,41,28.517837,3,1.917825,53,37.228242,35,24.726826,10,7.18004,1,0.429231,NaN,148,41,27.983813,2,1.168464,58,39.228176,37,25.086932,9,5.791322,1,0.741293,NaN,153,40,26.380055,1,0.756031,63,41.481161,36,23.525606,10,6.411997,2,1.44515
25,Casanare,140,62,44.629939,4,2.525255,48,34.618575,21,15.305774,3,2.448159,1,0.472299,NaN,146,60,41.190783,4,2.460563,56,38.341662,22,15.197161,3,2.248298,1,0.561533,NaN,148,60,40.342796,6,4.277311,53,36.094649,22,14.845715,5,3.425366,2,1.014163,NaN,154,53,34.763133,4,2.523135,64,41.880682,23,14.798532,6,3.84333,3,2.191187,NaN,157,59,37.850734,3,2.060342,66,42.065342,22,14.253997,5,3.051026,1,0.71856,NaN,161,58,35.817338,2,1.172789,70,43.606587,19,11.524725,10,6.487617,2,1.390946,NaN,165,58,35.230038,3,2.004779,73,44.538318,20,12.152815,8,5.146519,2,0.927531
26,Cauca,456,280,61.426774,13,2.78184,68,14.981196,87,19.01181,5,1.192609,3,0.605772,NaN,481,274,56.978157,11,2.286709,73,15.21333,87,18.113215,17,3.606059,18,3.80253,NaN,480,258,53.75324,9,1.870294,85,17.766637,93,19.304418,16,3.29625,19,4.009161,NaN,559,203,36.350504,13,2.292959,105,18.863848,151,27.036075,47,8.375391,40,7.081223,NaN,574,215,37.371667,10,1.805169,114,19.864916,134,23.316082,53,9.269823,48,8.372342,NaN,590,240,40.76714,11,1.796324,110,18.608919,145,24.51167,61,10.276582,24,4.039365,NaN,604,263,43.57047,10,1.575932,118,19.585203,120,19.910669,35,5.760602,58,9.597124
27,Cesar,341,157,46.108944,9,2.727364,94,27.517547,65,19.169983,13,3.814573,2,0.661589,NaN,365,150,41.068599,11,3.106274,111,30.401757,73,19.952393,19,5.132519,1,0.338458,NaN,376,130,34.614516,12,3.320241,123,32.790822,69,18.262505,29,7.669368,13,3.342549,NaN,400,125,31.285299,13,3.254697,159,39.750373,74,18.54454,17,4.373413,11,2.791678,NaN,412,130,31.661435,8,1.837203,157,38.043269,76,18.423962,24,5.891439,17,4.142692,NaN,425,159,37.476556,9,2.204788,150,35.28926,81,19.121381,20,4.66708,5,1.240935,NaN,438,155,35.409817,7,1.578184,157,35.855001,85,19.523127,23,5.185715,11,2.448157
28,Córdoba,495,276,55.857554,9,1.796205,72,14.58349,110,22.270982,25,5.020863,2,0.470907,NaN,510,283,55.496949,3,0.588529,79,15.530517,118,23.11852,21,4.098703,6,1.166782,NaN,532,290,54.510327,4,0.794863,92,17.195597,90,16.905785,30,5.653291,26,4.940137,NaN,589,281,47.686318,5,0.837037,109,18.446224,150,25.465404,35,5.941551,10,1.623467,NaN,603,242,40.04625,6,0.951962,118,19.563743,120,19.949589,113,18.722363,5,0.766094,NaN,618,260,42.09762,4,0.673461,122,19.774051,178,28.795791,53,8.602069,0,0.057009,NaN,632,278,43.925374,5,0.803699,130,20.625534,159,25.133032,50,7.982797,10,1.529564
29,Cundinamarca,974,399,40.931487,77,7.914463,372,38.202607,101,10.373072,11,1.079606,15,1.498765,NaN,1054,364,34.540643,73,6.943999,443,42.063057,143,13.544124,20,1.941858,10,0.966319,NaN,1100,358,32.551794,116,10.576041,461,41.919119,123,11.140111,17,1.512477,25,2.300458,NaN,1190,373,31.363231,105,8.865031,544,45.758275,135,11.327554,10,0.810247,22,1.875662,NaN,1244,351,28.231464,123,9.894998,590,47.43941,141,11.316761,19,1.555409,19,1.561957,NaN,1299,360,27.675338,114,8.754019,635,48.895725,126,9.662845,31,2.421096,34,2.590978,NaN,1355,383,28.255074,97,7.177493,717,52.918329,121,8.933905,14,1.008238,23,1.706962
30,Chocó,165,105,63.497747,1,0.387419,21,12.982968,24,14.425346,8,4.817127,6,3.889392,NaN,170,112,65.618635,1,0.309603,28,16.605162,20,11.760378,5,2.999472,5,2.70675,NaN,182,88,48.528999,0,0.169021,32,17.432628,34,18.755721,8,4.523034,19,10.590596,NaN,172,71,41.23986,0,0.256123,36,20.780708,31,17.881243,24,14.152369,10,5.689697,NaN,176,108,61.013798,1,0.589531,34,19.338387,29,16.720021,2,1.379899,2,0.958364,NaN,181,121,67.002137,0,0.182079,33,17.977307,24,13.444557,0,0.255563,2,1.138356,NaN,185,120,64.489066,0,0.239061,27,14.362222,21,11.140129,14,7.635461,4,2.134061
31,Guainía,13,7,55.219386,0,0.152504,2,11.842462,1,11.474948,2,16.404801,1,4.9059,NaN,14,3,24.411886,0,0.668877,3,17.784792,1,7.79063,2,16.744996,5,32.59882,NaN,16,3,21.232536,0,0.438993,3,17.924479,2,10.452196,1,5.744299,7,44.207498,NaN,15,3,18.562008,0,0.647971,3,17.116048,1,6.812796,1,7.294573,7,49.566603,NaN,15,3,16.87296,0,0.622775,3,18.15188,1,6.745772,1,6.435795,8,51.170818,NaN,15,2,14.315987,0,0.312342,2,16.124797,1,6.731269,1,6.578421,8,55.937184,NaN,17,2,10.506686,0,0.430785,2,14.057826,1,5.24976,1,8.516928,10,61.238015
32,Guaviare,28,12,43.069129,1,3.497377,8,27.288436,6,21.857734,0,1.398894,1,2.88843,NaN,31,13,42.697636,1,3.542341,9,28.730587,7,21.784234,1,3.191355,0,0.053847,NaN,30,11,35.824906,1,3.174067,9,29.781974,7,24.789163,1,4.621401,1,1.808488,NaN,31,11,36.116021,1,3.401634,9,30.145163,7,21.586816,2,6.058476,1,2.691891,NaN,32,12,35.98685,1,3.041274,10,32.250534,7,21.900633,2,5.103159,1,1.71755,NaN,30,10,33.51559,1,2.594501,11,37.932173,5,17.049197,2,5.075485,1,3.833055,NaN,35,14,41.342008,1,3.991285,11,31.512773,7,19.62161,1,2.640734,0,0.891591

In [ ]:
# Eliminar filas del 1 al 10 y del 45 hacia abajo en df_ipm
indices_a_eliminar = list(range(0, 15)) + list(range(49, len(df_variables['Cuadro 6'])))
df_variables['Cuadro 6'] = df_variables['Cuadro 6'].drop(indices_a_eliminar).reset_index(drop=True)

print(f"df_variables[Cuadro 6] ahora tiene {len(df_variables['Cuadro 6'])} filas")

df_variables[Cuadro 6] ahora tiene 34 filas

In [ ]:
# Eliminar solo la fila 0
df_variables['Cuadro 6'] = df_variables['Cuadro 6'].drop([0]).reset_index(drop=True)

print(f"df_variables[Cuadro 6] final: {len(df_variables['Cuadro 6'])} filas")

df_variables[Cuadro 6] final: 33 filas

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

df_variables['Cuadro 6']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97
0,Amazonas,22,8,35.831677,0,0.313797,3,14.409997,1,6.692381,7,30.822032,3,11.930116,NaN,22,5,24.599212,0,0.176252,4,19.278111,1,6.018098,2,6.861215,10,43.067112,NaN,25,6,23.382076,0,0.316858,5,20.63128,5,17.891925,5,19.504343,5,18.273517,NaN,21,5,21.813015,0,0.313065,3,14.309585,2,11.585233,6,29.792295,5,22.186807,NaN,22,4,20.132034,0,0.317491,4,20.314841,2,7.642862,2,7.924215,9,43.668557,NaN,27,9,34.112195,0,0.379568,8,28.387525,2,6.693432,1,3.812666,7,26.614615,NaN,27,10,37.593603,0,0.154345,4,16.445119,2,8.508608,4,13.543407,6,23.754919
1,Antioquia,2107,876,41.549115,87,4.125916,779,36.951854,318,15.083524,35,1.669532,13,0.620059,NaN,2133,928,43.49536,94,4.415472,846,39.675134,222,10.410579,19,0.88448,24,1.118976,NaN,2180,830,38.062357,81,3.710226,902,41.360093,287,13.189121,32,1.478808,48,2.199394,NaN,2328,844,36.25988,109,4.690148,1013,43.523646,272,11.698942,46,1.970199,43,1.857186,NaN,2406,906,37.661666,81,3.357509,1091,45.343044,242,10.037716,34,1.392325,53,2.207741,NaN,2485,933,37.531899,84,3.386019,1116,44.921004,242,9.754635,46,1.83966,64,2.566784,NaN,2563,934,36.432476,90,3.498242,1152,44.940944,314,12.261027,48,1.866411,26,1.000901
2,Arauca,92,45,49.04491,1,1.505645,22,24.078127,17,17.864926,6,6.622218,1,0.884174,NaN,103,41,39.729296,1,0.596565,31,29.92211,24,23.128772,6,6.146615,0,0.476643,NaN,108,40,36.652423,1,1.002627,35,32.30806,22,20.288923,9,7.902099,2,1.845868,NaN,109,33,30.696476,1,0.84613,37,34.067105,26,24.163514,9,8.033302,2,2.193472,NaN,113,39,34.321048,1,0.836815,36,32.234915,23,20.378096,13,11.460656,1,0.768469,NaN,114,38,33.339716,1,1.135118,39,34.611624,24,20.839826,11,9.389039,1,0.684678,NaN,125,37,29.569393,2,1.271427,48,38.533602,22,17.782974,14,11.367265,2,1.475339
3,Atlántico,647,333,51.412696,18,2.747844,162,24.98682,89,13.714089,35,5.381954,11,1.756597,NaN,679,331,48.697925,12,1.771067,205,30.138922,95,14.042408,21,3.132311,15,2.217367,NaN,720,351,48.778324,18,2.439422,213,29.566976,83,11.498243,20,2.729466,36,4.987567,NaN,754,338,44.798012,29,3.815838,237,31.443293,96,12.779093,34,4.449646,20,2.714118,NaN,774,354,45.727593,18,2.315028,243,31.357968,127,16.385032,30,3.926628,2,0.28775,NaN,795,318,39.941429,23,2.873451,279,35.133795,145,18.247081,21,2.621067,9,1.183176,NaN,817,351,42.913298,24,2.979369,253,30.948588,153,18.667064,30,3.648756,7,0.842926
4,Bogotá D.C.,2601,1054,40.502206,237,9.112026,1118,42.988785,163,6.25957,14,0.521083,16,0.61633,NaN,2692,891,33.085753,224,8.31229,1366,50.765832,169,6.263981,14,0.505677,29,1.066467,NaN,2692,864,32.081072,244,9.075048,1331,49.432667,176,6.550398,34,1.251499,43,1.609315,NaN,2865,898,31.342024,266,9.279599,1393,48.626848,214,7.458092,40,1.399457,54,1.89398,NaN,2940,917,31.202212,221,7.504835,1549,52.667519,196,6.65639,28,0.959909,30,1.009136,NaN,3018,927,30.702668,243,8.038569,1557,51.588365,257,8.516586,22,0.719935,13,0.433877,NaN,3098,1069,34.511032,206,6.654311,1566,50.537514,201,6.48106,18,0.579661,38,1.236423
5,Bolívar,582,300,51.534897,6,1.011085,117,20.061702,117,20.102098,35,6.028509,7,1.26171,NaN,601,300,49.869902,6,0.982518,136,22.670144,107,17.76817,38,6.286807,15,2.422459,NaN,656,246,37.525827,16,2.410098,143,21.840683,146,22.213634,61,9.235181,44,6.774577,NaN,656,217,33.125932,8,1.25498,174,26.508908,159,24.223464,77,11.713128,21,3.173587,NaN,674,240,35.555666,8,1.178511,173,25.712646,110,16.250567,101,15.022016,42,6.280594,NaN,692,257,37.173378,8,1.14762,199,28.815856,170,24.645845,41,5.900927,16,2.316374,NaN,710,297,41.772243,6,0.898016,202,28.382629,144,20.295449,55,7.699194,7,0.952468
6,Boyacá,424,184,43.394264,23,5.518275,123,28.975807,81,19.154449,7,1.696355,5,1.26085,NaN,447,190,42.391582,19,4.319657,153,34.276861,72,16.08615,7,1.640357,6,1.285394,NaN,423,174,41.085253,18,4.177836,141,33.35264,82,19.319409,6,1.462279,3,0.602584,NaN,433,164,37.80059,13,3.069065,147,34.031772,90,20.762708,4,0.972812,15,3.363053,NaN,441,162,36.835165,18,4.109628,169,38.392365,69,15.607343,11,2.600759,11,2.454739,NaN,448,164,36.617154,17,3.699145,183,40.733254,69,15.481405,13,2.826842,3,0.6422,NaN,455,200,43.843135,12,2.632635,170,37.429993,62,13.608185,7,1.522273,4,0.963779
7,Caldas,340,127,37.492934,21,6.075701,124,36.631692,53,15.573293,4,1.3123,10,2.914081,NaN,350,139,39.777388,22,6.232334,122,34.885662,55,15.742433,4,1.25874,7,2.103443,NaN,367,131,35.824743,23,6.351987,145,39.641629,58,15.833574,4,0.981312,5,1.366755,NaN,355,128,36.125416,18,4.996399,141,39.67269,58,16.254655,4,1.01597,7,1.934871,NaN,363,127,34.917531,24,6.509559,148,40.686893,56,15.289477,6,1.602925,4,0.993614,NaN,371,129,34.787955,19,5.165838,167,44.996201,44,11.901129,3,0.903279,8,2.245598,NaN,380,146,38.554821,16,4.169974,166,43.812062,35,9.217125,3,0.706492,13,3.539526
8,Caquetá,133,55,41.564486,3,1.939582,38,28.471476,29,22.000928,8,5.647043,1,0.376485,NaN,134,49,36.471363,3,2.083227,42,31.437062,31,23.286196,8,6.021456,1,0.700695,NaN,131,50,38.384707,3,2.657538,42,31.671803,29,21.841344,6,4.44363,1,1.000978,NaN,139,42,30.357416,1,1.031482,52,37.108498,35,24.890389,7,4.82547,2,1.786744,NaN,144,41,28.517837,3,1.917825,53,37.228242,35,24.726826,10,7.18004,1,0.429231,NaN,148,41,27.983813,2,1.168464,58,39.228176,37,25.086932,9,5.791322,1,0.741293,NaN,153,40,26.380055,1,0.756031,63,41.481161,36,23.525606,10,6.411997,2,1.44515
9,Casanare,140,62,44.629939,4,2.525255,48,34.618575,21,15.305774,3,2.448159,1,0.472299,NaN,146,60,41.190783,4,2.460563,56,38.341662,22,15.197161,3,2.248298,1,0.561533,NaN,148,60,40.342796,6,4.277311,53,36.094649,22,14.845715,5,3.425366,2,1.014163,NaN,154,53,34.763133,4,2.523135,64,41.880682,23,14.798532,6,3.84333,3,2.191187,NaN,157,59,37.850734,3,2.060342,66,42.065342,22,14.253997,5,3.051026,1,0.71856,NaN,161,58,35.817338,2,1.172789,70,43.606587,19,11.524725,10,6.487617,2,1.390946,NaN,165,58,35.230038,3,2.004779,73,44.538318,20,12.152815,8,5.146519,2,0.927531
10,Cauca,456,280,61.426774,13,2.78184,68,14.981196,87,19.01181,5,1.192609,3,0.605772,NaN,481,274,56.978157,11,2.286709,73,15.21333,87,18.113215,17,3.606059,18,3.80253,NaN,480,258,53.75324,9,1.870294,85,17.766637,93,19.304418,16,3.29625,19,4.009161,NaN,559,203,36.350504,13,2.292959,105,18.863848,151,27.036075,47,8.375391,40,7.081223,NaN,574,215,37.371667,10,1.805169,114,19.864916,134,23.316082,53,9.269823,48,8.372342,NaN,590,240,40.76714,11,1.796324,110,18.608919,145,24.51167,61,10.276582,24,4.039365,NaN,604,263,43.57047,10,1.575932,118,19.585203,120,19.910669,35,5.760602,58,9.597124
11,Cesar,341,157,46.108944,9,2.727364,94,27.517547,65,19.169983,13,3.814573,2,0.661589,NaN,365,150,41.068599,11,3.106274,111,30.401757,73,19.952393,19,5.132519,1,0.338458,NaN,376,130,34.614516,12,3.320241,123,32.790822,69,18.262505,29,7.669368,13,3.342549,NaN,400,125,31.285299,13,3.254697,159,39.750373,74,18.54454,17,4.373413,11,2.791678,NaN,412,130,31.661435,8,1.837203,157,38.043269,76,18.423962,24,5.891439,17,4.142692,NaN,425,159,37.476556,9,2.204788,150,35.28926,81,19.121381,20,4.66708,5,1.240935,NaN,438,155,35.409817,7,1.578184,157,35.855001,85,19.523127,23,5.185715,11,2.448157
12,Córdoba,495,276,55.857554,9,1.796205,72,14.58349,110,22.270982,25,5.020863,2,0.470907,NaN,510,283,55.496949,3,0.588529,79,15.530517,118,23.11852,21,4.098703,6,1.166782,NaN,532,290,54.510327,4,0.794863,92,17.195597,90,16.905785,30,5.653291,26,4.940137,NaN,589,281,47.686318,5,0.837037,109,18.446224,150,25.465404,35,5.941551,10,1.623467,NaN,603,242,40.04625,6,0.951962,118,19.563743,120,19.949589,113,18.722363,5,0.766094,NaN,618,260,42.09762,4,0.673461,122,19.774051,178,28.795791,53,8.602069,0,0.057009,NaN,632,278,43.925374,5,0.803699,130,20.625534,159,25.133032,50,7.982797,10,1.529564
13,Cundinamarca,974,399,40.931487,77,7.914463,372,38.202607,101,10.373072,11,1.079606,15,1.498765,NaN,1054,364,34.540643,73,6.943999,443,42.063057,143,13.544124,20,1.941858,10,0.966319,NaN,1100,358,32.551794,116,10.576041,461,41.919119,123,11.140111,17,1.512477,25,2.300458,NaN,1190,373,31.363231,105,8.865031,544,45.758275,135,11.327554,10,0.810247,22,1.875662,NaN,1244,351,28.231464,123,9.894998,590,47.43941,141,11.316761,19,1.555409,19,1.561957,NaN,1299,360,27.675338,114,8.754019,635,48.895725,126,9.662845,31,2.421096,34,2.590978,NaN,1355,383,28.255074,97,7.177493,717,52.918329,121,8.933905,14,1.008238,23,1.706962
14,Chocó,165,105,63.497747,1,0.387419,21,12.982968,24,14.425346,8,4.817127,6,3.889392,NaN,170,112,65.618635,1,0.309603,28,16.605162,20,11.760378,5,2.999472,5,2.70675,NaN,182,88,48.528999,0,0.169021,32,17.432628,34,18.755721,8,4.523034,19,10.590596,NaN,172,71,41.23986,0,0.256123,36,20.780708,31,17.881243,24,14.152369,10,5.689697,NaN,176,108,61.013798,1,0.589531,34,19.338387,29,16.720021,2,1.379899,2,0.958364,NaN,181,121,67.002137,0,0.182079,33,17.977307,24,13.444557,0,0.255563,2,1.138356,NaN,185,120,64.489066,0,0.239061,27,14.362222,21,11.140129,14,7.635461,4,2.134061
15,Guainía,13,7,55.219386,0,0.152504,2,11.842462,1,11.474948,2,16.404801,1,4.9059,NaN,14,3,24.411886,0,0.668877,3,17.784792,1,7.79063,2,16.744996,5,32.59882,NaN,16,3,21.232536,0,0.438993,3,17.924479,2,10.452196,1,5.744299,7,44.207498,NaN,15,3,18.562008,0,0.647971,3,17.116048,1,6.812796,1,7.294573,7,49.566603,NaN,15,3,16.87296,0,0.622775,3,18.15188,1,6.745772,1,6.435795,8,51.170818,NaN,15,2,14.315987,0,0.312342,2,16.124797,1,6.731269,1,6.578421,8,55.937184,NaN,17,2,10.506686,0,0.430785,2,14.057826,1,5.24976,1,8.516928,10,61.238015
16,Guaviare,28,12,43.069129,1,3.497377,8,27.288436,6,21.857734,0,1.398894,1,2.88843,NaN,31,13,42.697636,1,3.542341,9,28.730587,7,21.784234,1,3.191355,0,0.053847,NaN,30,11,35.824906,1,3.174067,9,29.781974,7,24.789163,1,4.621401,1,1.808488,NaN,31,11,36.116021,1,3.401634,9,30.145163,7,21.586816,2,6.058476,1,2.691891,NaN,32,12,35.98685,1,3.041274,10,32.250534,7,21.900633,2,5.103159,1,1.71755,NaN,30,10,33.51559,1,2.594501,11,37.932173,5,17.049197,2,5.075485,1,3.833055,NaN,35,14,41.342008,1,3.991285,11,31.512773,7,19.62161,1,2.640734,0,0.891591
17,Huila,349,173,49.412445,13,3.639022,87,24.871445,63,17.936057,9,2.603368,5,1.537663,NaN,351,163,46.620727,15,4.167923,99,28.322639,62,17.546294,7,2.043649,5,1.298769,NaN,351,141,40.201325,20,5.642247,105,29.962242,59,16.924877,20,5.647587,6,1.621722,NaN,366,147,40.110073,13,3.596946,114,31.303645,65,17.845647,20,5.495496,6,1.648194,NaN,374,149,39.806384,13,3.496787,122,32.631836,72,19.178423,11,3.038855,7,1.847715,NaN,382,150,39.182836,11,2.758652,119,31.016477,66,17.362942,29,7.459917,8,2.219176,NaN,390,154,39.482832,11,2.906456,134,34.29058,72,18.412656,15,3.750053,5,1.157424
18,La Guajira,258,113,43.670501,4,1.38834,47,18.220052,56,21.571169,6,2.178951,34,12.970987,NaN,282,79,27.850875,2,0.619391,65,23.204234,66,23.423396,13,4.538892,57,20.363211,NaN,296,56,18.843488,1,0.278617,68,22.799987,61,20.562492,59,19.955061,52,17.560354,NaN,295,42,14.297308,1,0.188688,71,24.178317,44,15.033691,18,6.249917,118,40.052079,NaN,307,66,21.560619,2,0.516356,76,24.619484,56,18.089972,43,13.881263,65,21.332305,NaN,318,91,28.726231,1,0.41548,80,25.29505,39,12.384195,39,12.294071,66,20.884973,NaN,329,67,20.455895,1,0.20449,79,24.059285,45,13.549744,68,20.727638,69,21.002947
19,Magdalena,366,155,42.262353,10,2.778054,80,21.909895,77,21.028328,41,11.313215,3,0.708155,NaN,396,204,51.382087,10,2.400177,91,22.866433,68,17.255989,18,4.653999,6,1.441315,NaN,404,188,46.475599,10,2.4507,88,21.717843,72,17.877689,27,6.697688,19,4.78048,NaN,411,169,40.995658,2,0.502402,111,27.064467,102,24.76018,24,5.74386,4,0.933432,NaN,422,168,39.730873,3,0.774139,110,26.133892,84,19.953679,50,11.894827,6,1.51259,NaN,432,184,42.509524,6,1.406077,123,28.420557,87,20.239866,21,4.877413,11,2.546563,NaN,442,169,38.372799,4,0.932557,124,28.163572,96,21.679854,25,5.720953,23,5.130266
20,Meta,344,125,36.491158,15,4.287761,145,42.092084,53,15.469891,3,0.909121,3,0.749984,NaN,354,119,33.731212,9,2.657721,151,42.760302,63,17.78422,6,1.673961,5,1.392583,NaN,364,125,34.307246,11,2.980074,159,43.838435,51,14.093578,9,2.396385,9,2.384283,NaN,370,118,31.83291,13,3.438524,159,43.121782,58,15.787649,14,3.705642,8,2.113494,NaN,378,122,32.163687,11,3.017891,176,46.419962,47,12.393285,16,4.10223,7,1.902945,NaN,386,120,31.104363,23,5.980621,175,45.347621,52,13.338083,11,2.923865,5,1.305447,NaN,395,138,34.981293,11,2.885961,183,46.465129,45,11.33136,11,2.741371,6,1.594887
21,Nariño,510,270,52.934795,15,2.882009,105,20.522978,118,23.182659,2,0.342069,1,0.13549,NaN,538,302,56.093796,20,3.762733,105,19.486473,104,19.330676,5,0.861447,3,0.464874,NaN,534,243,45.419931,16,2.918867,117,21.851508,124,23.309038,33,6.13493,2,0.365726,NaN,577,275,47.681101,11,1.986487,130,22.454667,150,25.995223,9,1.521235,2,0.361287,NaN,588,234,39.692378,9,1.445958,137,23.342684,145,24.658652,62,10.487942,2,0.372386,NaN,600,252,41.957808,11,1.822529,138,23.029029,163,27.214244,19,3.14846,17,2.827931,NaN,611,228,37.379999,11,1.860745,141,23.029474,175,28.620404,54,8.873286,1,0.236093
22,Norte de Santander,460,174,37.881463,16,3.524951,142,30.936427,87,18.818331,39,8.396848,2,0.441981,NaN,476,204,42.760265,17,3.634221,155,32.599023,83,17.398661,15,3.219258,2,0.388571,NaN,508,178,35.035583,26,5.216212,184,36.267346,97,19.206932,16,3.145336,6,1.128591,NaN,494,163,33.034292,18,3.734435,195,39.486594,90,18.292782,21,4.319602,6,1.132295,NaN,504,166,32.913602,13,2.546733,208,41.409395,94,18.667839,17,3.324331,6,1.1381,NaN,514,181,35.157742,18,3.441099,198,38.585152,88,17.194882,25,4.838376,4,0.782749,NaN,524,210,40.024338,21,3.953952,190,36.290507,73,13.913898,26,5.004494,4,0.812812
23,Putumayo,117,61,52.145083,1,1.069022,31,26.752727,20,17.35962,1,1.058832,2,1.614717,NaN,125,55,43.691083,2,1.374998,35,27.633577,32,25.54365,2,1.648218,0,0.108473,NaN,125,42,33.450169,1,1.159889,42,34.036309,26,20.80149,12,9.469609,1,1.082533,NaN,146,34,23.108409,1,0.868596,48,33.20993,41,28.237649,16,11.07453,5,3.500884,NaN,151,48,31.732485,1,0.911502,53,35.419272,35,23.115624,10,6.401528,4,2.419588,NaN,156,41,26.487177,1,0.353494,60,38.78812,42,27.254969,9,5.803625,2,1.312615,NaN,161,40,24.588922,1,0.406957,70,43.184964,30,18.901778,18,11.144694,3,1.772685
24,Quindío,190,74,39.107494,9,4.686607,71,37.534553,29,15.304818,6,3.041301,1,0.325227,NaN,195,70,36.003875,8,4.244575,87,44.503342,26,13.470594,2,1.265166,1,0.512449,NaN,210,72,34.364616,10,4.790356,92,43.704844,28,13.552546,5,2.526413,2,1.061225,NaN,199,69,34.769161,10,4.920276,87,43.952018,24,12.186001,4,2.067781,4,2.104764,NaN,204,67,32.715597,7,3.590135,94,46.053916,26,12.947945,5,2.301569,5,2.390838,NaN,209,69,33.030544,10,4.608052,99,47.253947,24,11.513187,5,2.168007,3,1.426262,NaN,215,71,33.314645,8,3.788793,101,46.972003,26,12.322811,5,2.115481,3,1.486266
25,Risaralda,325,119,36.700358,8,2.46632,141,43.254056,54,16.574302,1,0.394886,2,0.610079,NaN,335,114,34.165077,11,3.20939,144,42.940208,54,16.107145,5,1.350153,7,2.228027,NaN,349,112,31.987464,13,3.83849,165,47.284719,39,11.057427,8,2.214442,13,3.617458,NaN,333,96,28.941042,13,3.920875,163,48.903692,45,13.459374,4,1.235968,12,3.539048,NaN,341,110,32.128781,11,3.349125,165,48.515633,44,12.868637,5,1.471892,6,1.665933,NaN,349,118,33.696893,12,3.56202,172,49.197886,38,10.881957,6,1.635602,4,1.025643,NaN,357,107,29.952564,16,4.389382,170,47.614727,43,12.068467,14,4.002162,7,1.972699
26,San Andrés,16,7,43.781436,0,1.093202,6,35.400751,3,17.591086,0,0.553856,0,1.579669,NaN,15,9,57.028385,0,0.652605,5,35.284136,1,5.267085,0,0.93889,0,0.828899,NaN,16,6,40.095737,0,0.685006,7,46.423762,1,9.051118,0,2.46455,0,1.279827,NaN,15,4,29.303417,0,1.269372,7,47.693587,1,8.492444,2,12.360852,0,0.880328,NaN,16,6,40.607468,0,1.017788,6,38.31479,2,14.000292,0,0.376904,1,5.682758,NaN,16,7,44.561735,0,1.226111,6,39.471652,2,13.25203,0,0.736531,0,0.751941,NaN,17,6,34.29367,0,0.077137,8,48.964763,2,11.91584,0,0.38929,1,4.3593
27,Santander,714,301,42.130438,45,6.281458,252,35.238014,93,13.03349,16,2.177081,8,1.139519,NaN,738,292,39.572524,40,5.42665,278,37.623631,104,14.043723,15,1.989022,10,1.344449,NaN,755,290,38.404008,23,3.009248,300,39.754125,105,13.943196,16,2.070248,21,2.819174,NaN,769,275,35.734067,37,4.824454,329,42.779805,82,10.699416,22,2.864066,24,3.098192,NaN,786,254,32.333181,27,3.434392,361,45.991519,92,11.69516,41,5.209052,11,1.336695,NaN,803,285,35.546749,32,3.927563,357,44.446062,98,12.14131,15,1.880988,17,2.057327,NaN,821,262,31.916793,30,3.693668,374,45.527418,103,12.595458,33,4.054245,18,2.212417
28,Sucre,247,137,55.504681,3,1.237495,43,17.220159,50,20.252806,12,4.940256,2,0.844603,NaN,271,145,53.623915,5,1.71504,45,16.483085,65,24.163544,6,2.068599,5,1.945817,NaN,274,128,46.740588,3,1.13269,52,19.055666,57,20.973913,24,8.932316,9,3.164827,NaN,278,117,41.905659,2,0.816195,58,20.772016,66,23.620647,29,10.468184,7,2.417299,NaN,285,122,42.693638,4,1.298785,59,20.559995,69,24.155065,29,10.283718,3,1.0088,NaN,292,133,45.613424,4,1.402662,56,19.275228,56,19.266866,32,11.124163,10,3.317657,NaN,299,127,42.675517,3,0.897516,60,20.070496,68,22.770965,29,9.616007,12,3.969499
29,Tolima,444,197,44.351166,22,4.976193,140,31.657457,75,16.839664,7,1.538416,3,0.637105,NaN,479,193,40.203713,22,4.532567,156,32.63743,78,16.234198,14,2.976686,16,3.415405,NaN,467,166,35.463542,23,4.8635,171,36.593125,83,17.793801,19,4.007476,6,1.278556,NaN,480,168,35.10718,19,3.96749,180,37.500649,91,18.985233,14,2.82959,8,1.609859,NaN,488,200,40.940562,19,3.80733,189,38.811379,69,14.055781,10,1.955553,2,0.429395,NaN,496,182,36.696061,24,4.858036,194,39.187166,73,14.723524,9,1.784014,14,2.751199,NaN,504,193,38.282507,22,4.436686,177,35.19263,95,18.901777,11,2.194493,5,0.991907
30,Valle,1460,558,38.245108,91,6.226859,537,36.789876,217,14.842429,45,3.099333,12,0.796396,NaN,1472,558,37.895914,85,5.750613,589,39.986694,198,13.452139,27,1.815185,16,1.099456,NaN,1551,483,31.157832,74,4.740957,694,44.771351,253,16.337461,23,1.506519,23,1.48588,NaN,1511,448,29.640045,66,4.351564,706,46.733855,240,15.885225,37,2.449232,14,0.940079,NaN,1544,485,31.43149,65,4.234859,726,46.998828,211,13.646924,31,1.99737,26,1.690528,NaN,1577,521,33.016734,48,3.028924,731,46.342914,196,12.450929,23,1.485381,58,3.675119,NaN,1610,522,32.424741,34,2.126215,788,48.953475,209,12.99948,33,2.065555,23,1.430533
31,Vaupés,9,3,37.517672,0,0.195591,0,4.748197,0,4.888882,0,4.638898,4,48.010759,NaN,10,6,61.289077,0,0.143741,0,4.029157,0,3.748428,0,0.303409,3,30.486188,NaN,11,2,19.764803,0,0.292467,1,7.51629,1,5.496852,1,7.610201,7,59.319387,NaN,12,2,18.042117,0,0.232434,1,5.74227,1,9.472925,0,2.892705,8,63.617549,NaN,14,3,19.796589,0,0.041722,1,7.555389,1,4.437389,0,1.203497,9,66.965415,NaN,15,3,16.922022,0,0.096415,1,7.598155,1,4.867487,1,4.027291,10,66.48863,NaN,15,3,18.767103,0,0.171575,1,7.035981,1,3.671979,4,28.431459,6,41.921903

In [ ]:
print(df_variables['Cuadro 6'].columns.tolist())

['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97']

In [ ]:
# Colocar el nombre de las columnas en el orden que quiero que queden
df_variables['Cuadro 6'] = df_variables['Cuadro 6'][['Unnamed: 0', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 88','Unnamed: 90','Unnamed: 92','Unnamed: 94', 'Unnamed: 96']]
df_variables['Cuadro 6'].head(2)

,Unnamed: 0,Unnamed: 85,Unnamed: 86,Unnamed: 88,Unnamed: 90,Unnamed: 92,Unnamed: 94,Unnamed: 96
0,Amazonas,27,10,0,4,2,4,6
1,Antioquia,2563,934,90,1152,314,48,26

In [ ]:
# Renombrar columnas
df_variables['Cuadro 6'] = df_variables['Cuadro 6'].rename(columns={
    'Unnamed: 0': 'Departamentos',
    'Unnamed: 85': 'total hogares',
    'Unnamed: 86': 'Propia totalmete pagada',
    'Unnamed: 88': 'Prpia la estan pagando',
    'Unnamed: 90': 'En Arriendo o Subarriendo',
    'Unnamed: 92': 'Con permiso del propietario/sin pago',
    'Unnamed: 94': 'poosesión sin titulo',
    'Unnamed: 96': 'propiedad colectiva',
    })

# Verificar resultado
df_variables['Cuadro 6'].head(2)

,Departamentos,total hogares,Propia totalmete pagada,Prpia la estan pagando,En Arriendo o Subarriendo,Con permiso del propietario/sin pago,poosesión sin titulo,propiedad colectiva
0,Amazonas,27,10,0,4,2,4,6
1,Antioquia,2563,934,90,1152,314,48,26

In [ ]:
#Encontrar duplicados
df_variables['Cuadro 6'].duplicated().sum()

np.int64(0)

In [ ]:
# Ver la cantidad de valores nulos en cada columna
df_variables['Cuadro 6'].isna().sum()

Departamentos                           0
total hogares                           0
Propia totalmete pagada                 0
Prpia la estan pagando                  0
En Arriendo o Subarriendo               0
Con permiso del propietario/sin pago    0
poosesión sin titulo                    0
propiedad colectiva                     0
dtype: int64

In [ ]:
df_variables['Cuadro 6']

,Departamentos,total hogares,Propia totalmete pagada,Prpia la estan pagando,En Arriendo o Subarriendo,Con permiso del propietario/sin pago,poosesión sin titulo,propiedad colectiva
0,Amazonas,27,10,0,4,2,4,6
1,Antioquia,2563,934,90,1152,314,48,26
2,Arauca,125,37,2,48,22,14,2
3,Atlántico,817,351,24,253,153,30,7
4,Bogotá D.C.,3098,1069,206,1566,201,18,38
5,Bolívar,710,297,6,202,144,55,7
6,Boyacá,455,200,12,170,62,7,4
7,Caldas,380,146,16,166,35,3,13
8,Caquetá,153,40,1,63,36,10,2
9,Casanare,165,58,3,73,20,8,2
10,Cauca,604,263,10,118,120,35,58
11,Cesar,438,155,7,157,85,23,11
12,Córdoba,632,278,5,130,159,50,10
13,Cundinamarca,1355,383,97,717,121,14,23
14,Chocó,185,120,0,27,21,14,4
15,Guainía,17,2,0,2,1,1,10
16,Guaviare,35,14,1,11,7,1,0
17,Huila,390,154,11,134,72,15,5
18,La Guajira,329,67,1,79,45,68,69
19,Magdalena,442,169,4,124,96,25,23
20,Meta,395,138,11,183,45,11,6
21,Nariño,611,228,11,141,175,54,1
22,Norte de Santander,524,210,21,190,73,26,4
23,Putumayo,161,40,1,70,30,18,3
24,Quindío,215,71,8,101,26,5,3
25,Risaralda,357,107,16,170,43,14,7
26,San Andrés,17,6,0,8,2,0,1
27,Santander,821,262,30,374,103,33,18
28,Sucre,299,127,3,60,68,29,12
29,Tolima,504,193,22,177,95,11,5
30,Valle,1610,522,34,788,209,33,23
31,Vaupés,15,3,0,1,1,4,6
32,Vichada,41,5,0,5,2,22,7

#2.2.5.Percepción de la calidad del servicio de la EPS

In [ ]:
df_variables['Cuadro 11']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Volver al inicio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN,NaN,NaN
10,Dominio,Personas afiliadas que conocen su régimen de afiliación*,Calidad**,NaN,NaN,NaN,NaN,NaN,NaN,Personas afiliadas que conocen su régimen de afiliación*,Calidad**,NaN,NaN,NaN,NaN,NaN,NaN,Personas afiliadas que conocen su régimen de afiliación*,Calidad**,NaN,NaN,NaN,NaN,NaN,NaN,Personas afiliadas que conocen su régimen de afiliación*,Calidad**,NaN,NaN,NaN,NaN,NaN,NaN,Personas afiliadas que conocen su régimen de afiliación*,Calidad**,NaN,NaN,NaN,NaN,NaN,NaN,Personas afiliadas que conocen su régimen de afiliación*,Calidad**,NaN,NaN,NaN,NaN,NaN,NaN,Personas afiliadas que conocen su régimen de afiliación*,Calidad**,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,Muy buena,NaN,Buena,NaN,Mala y muy mala,NaN,NaN,NaN,Muy buena,NaN,Buena,NaN,Mala y muy mala,NaN,NaN,NaN,Muy buena,NaN,Buena,NaN,Mala y muy mala,NaN,NaN,NaN,Muy buena,NaN,Buena,NaN,Mala y muy mala,NaN,NaN,NaN,Muy buena,NaN,Buena,NaN,Mala y muy mala,NaN,NaN,NaN,Muy buena,NaN,Buena,NaN,Mala y muy mala,NaN,NaN,NaN,Muy buena,NaN,Buena,NaN,Mala y muy mala,NaN
12,NaN,Total,Total,%,Total,%,Total,%,NaN,Total,Total,%,Total,%,Total,%,NaN,Total,Total,%,Total,%,Total,%,NaN,Total,Total,%,Total,%,Total,%,NaN,Total,Total,%,Total,%,Total,%,NaN,Total,Total,%,Total,%,Total,%,NaN,Total,Total,%,Total,%,Total,%
13,Total nacional,45366,3181,7.011761,33625,74.117674,7528,16.593921,NaN,45985,3722,8.093153,34066,74.081438,7225,15.71209,NaN,46986,4737,10.082611,37072,78.90071,4458,9.488592,NaN,47493,5522,11.626935,35892,75.573413,5187,10.920995,NaN,48879,5985,12.244592,35614,72.861921,6406,13.106676,NaN,50086,5309,10.599907,36574,73.023023,7328,14.630122,NaN,50912,5270,10.351976,37859,74.362805,6990,13.729673
14,Cabecera,34265,2757,8.046059,25106,73.269164,5614,16.383246,NaN,34709,3268,9.413971,25464,73.365252,5225,15.055089,NaN,35617,4025,11.301579,27861,78.222709,3198,8.977633,NaN,36071,4760,13.197215,26810,74.325241,3869,10.726603,NaN,37199,5028,13.517346,26873,72.241771,4683,12.589647,NaN,38202,4542,11.889196,27869,72.953343,5162,13.51287,NaN,38896,4561,11.725423,28853,74.179804,4922,12.654905
15,Centros poblados y rural disperso,11101,424,3.819197,8519,76.736768,1914,17.24421,NaN,11275,454,4.027271,8602,76.286078,2000,17.734541,NaN,11369,712,6.263854,9212,81.024741,1261,11.089317,NaN,11422,762,6.667933,9082,79.515184,1318,11.534891,NaN,11681,957,8.191281,8741,74.836898,1723,14.753246,NaN,11884,767,6.455492,8705,73.247011,2165,18.221529,NaN,12015,710,5.905768,9006,74.955226,2068,17.208976
16,Amazonas,71,5,6.691589,49,68.698493,17,24.257435,NaN,72,3,3.937929,62,86.400777,5,7.202269,NaN,77,3,3.258744,67,87.489587,6,8.305827,NaN,79,2,2.138769,71,88.839318,7,8.504573,NaN,80,6,6.886835,69,86.203547,3,4.125757,NaN,82,8,9.359078,62,75.715801,10,12.395325,NaN,85,15,18.208302,61,72.194795,7,7.888711
17,Antioquia,6156,665,10.797232,4430,71.963537,885,14.381902,NaN,6074,1100,18.106802,4062,66.866357,830,13.668915,NaN,6270,1201,19.149943,4617,73.639221,414,6.603347,NaN,6295,870,13.81857,4808,76.382131,511,8.112406,NaN,6586,1186,18.011869,4769,72.414368,542,8.23299,NaN,6770,1228,18.144569,4861,71.80377,582,8.600913,NaN,6850,841,12.278636,4995,72.919064,871,12.709952
18,Arauca,234,11,4.780979,169,72.432743,47,20.219953,NaN,240,4,1.763854,208,86.491403,28,11.574896,NaN,250,22,8.671761,200,79.983039,24,9.478606,NaN,242,9,3.525609,203,84.115121,24,10.065938,NaN,269,37,13.918506,202,74.941393,27,9.924057,NaN,272,12,4.575812,208,76.500604,49,18.15744,NaN,289,23,7.950025,230,79.548284,34,11.64211
19,Atlántico,2347,133,5.665039,2018,85.97669,165,7.039294,NaN,2438,196,8.027936,2052,84.173543,177,7.271158,NaN,2561,171,6.681994,2237,87.349311,141,5.512317,NaN,2582,332,12.860784,2161,83.698601,70,2.727295,NaN,2671,463,17.339669,2079,77.841244,107,4.022334,NaN,2744,479,17.450923,2002,72.967326,228,8.292009,NaN,2781,303,10.888978,2236,80.387242,216,7.780733
20,Bogotá D.C.,6892,740,10.741363,4941,71.693937,1039,15.081464,NaN,6950,603,8.678785,4919,70.784312,1155,16.616453,NaN,6971,651,9.343339,5541,79.488273,614,8.802159,NaN,7216,1288,17.849577,4717,65.370159,963,13.348723,NaN,7254,926,12.768387,5035,69.411012,1133,15.616147,NaN,7474,756,10.119834,5345,71.518559,1224,16.372367,NaN,7614,812,10.667895,5785,75.977745,865,11.363781
21,Bolívar,1950,79,4.041966,1666,85.452529,181,9.306091,NaN,2008,111,5.532007,1675,83.43325,193,9.614929,NaN,2057,155,7.534992,1770,86.026291,103,5.030758,NaN,2093,247,11.806569,1765,84.309938,53,2.548703,NaN,2169,452,20.858574,1591,73.346851,102,4.711369,NaN,2200,366,16.616628,1582,71.906964,225,10.249145,NaN,2257,340,15.05067,1802,79.834641,107,4.7533
22,Boyacá,1171,25,2.144049,775,66.17528,344,29.376871,NaN,1176,13,1.119955,891,75.763576,258,21.941581,NaN,1202,22,1.83988,1010,84.030694,163,13.576416,NaN,1202,58,4.822515,857,71.28783,259,21.537174,NaN,1214,86,7.097271,898,73.970183,218,17.969645,NaN,1235,34,2.752789,851,68.904915,330,26.769058,NaN,1257,32,2.517747,969,77.073945,247,19.628208
23,Caldas,949,153,16.170094,633,66.742606,145,15.311886,NaN,951,118,12.423611,686,72.152932,130,13.624478,NaN,959,210,21.929658,638,66.505635,95,9.903936,NaN,973,194,19.951566,648,66.593504,118,12.091828,NaN,999,173,17.340235,655,65.632505,147,14.715498,NaN,1022,165,16.16175,754,73.79914,94,9.197219,NaN,1040,107,10.253628,795,76.492135,126,12.131201
24,Caquetá,386,7,1.890372,322,83.584976,53,13.609021,NaN,388,6,1.522322,319,82.273245,58,15.039654,NaN,396,7,1.818437,345,87.161181,39,9.980401,NaN,400,32,8.083315,345,86.294587,21,5.183445,NaN,404,12,3.008107,333,82.441159,54,13.2884,NaN,413,7,1.733028,289,70.169086,110,26.722873,NaN,427,3,0.793393,320,75.050487,96,22.450689
25,Casanare,395,10,2.637661,273,69.261905,104,26.458863,NaN,393,9,2.386806,291,74.045094,85,21.606858,NaN,396,9,2.312837,304,76.733778,66,16.736306,NaN,399,29,7.206951,287,71.800625,77,19.241851,NaN,416,12,2.915615,291,69.918278,103,24.877317,NaN,413,11,2.708764,285,69.057975,105,25.481444,NaN,425,7,1.700407,301,70.831147,110,25.828378
26,Cauca,1399,45,3.189462,1080,77.170844,253,18.07195,NaN,1415,28,1.946636,1102,77.869161,267,18.90106,NaN,1421,84,5.908817,1136,79.950851,187,13.19341,NaN,1434,151,10.564146,1075,74.954843,194,13.545215,NaN,1469,94,6.379276,1152,78.434741,206,14.044614,NaN,1504,64,4.274179,997,66.260859,425,28.260158,NaN,1523,65,4.251017,915,60.096546,518,34.046812
27,Cesar,1104,87,7.870496,878,79.525913,114,10.323612,NaN,1150,47,4.126598,931,80.999633,155,13.453229,NaN,1204,112,9.280867,1036,86.116904,52,4.316702,NaN,1201,90,7.489836,1020,84.902539,73,6.082888,NaN,1263,70,5.542906,1057,83.674452,116,9.159107,NaN,1317,76,5.742704,1098,83.386823,126,9.536359,NaN,1346,171,12.690985,1085,80.641008,83,6.178269
28,Córdoba,1724,92,5.308941,1435,83.216561,178,10.330839,NaN,1754,161,9.192789,1387,79.031637,188,10.698039,NaN,1786,104,5.82088,1585,88.748078,81,4.516624,NaN,1782,110,6.169028,1519,85.220584,122,6.840606,NaN,1818,274,15.066019,1407,77.402236,116,6.368304,NaN,1854,197,10.637074,1479,79.777595,149,8.031057,NaN,1861,105,5.617893,1598,85.83857,133,7.170291
29,Cundinamarca,2761,89,3.207457,2153,77.990982,468,16.952895,NaN,2870,102,3.568364,2232,77.773057,460,16.036681,NaN,3016,198,6.566152,2554,84.672778,217,7.185463,NaN,3128,247,7.908539,2450,78.321928,386,12.350783,NaN,3300,347,10.500389,2414,73.137179,465,14.105304,NaN,3392,234,6.895623,2624,77.36765,480,14.151324,NaN,3494,606,17.338706,2250,64.390641,571,16.347729
30,Chocó,492,8,1.696541,358,72.658044,109,22.067938,NaN,514,4,0.688434,415,80.706009,84,16.294942,NaN,526,6,1.203062,410,77.949975,99,18.842102,NaN,538,10,1.89903,442,82.067743,76,14.131439,NaN,539,16,2.977256,356,66.014756,157,29.093188,NaN,549,17,3.080162,453,82.598571,70,12.682484,NaN,561,7,1.267821,458,81.610555,90,16.048066
31,Guainía,46,1,3.242786,36,78.159409,7,16.435709,NaN,47,1,1.58457,31,65.308556,14,30.92054,NaN,46,1,1.224559,38,84.514474,6,12.761112,NaN,45,0,1.030144,39,85.868945,5,11.311973,NaN,47,0,0.794129,32,68.583926,14,29.993174,NaN,47,1,2.533073,27,57.242164,18,38.00868,NaN,48,0,0.459563,32,66.845668,15,30.7252
32,Guaviare,78,0,0.56308,51,65.300567,24,30.961668,NaN,76,1,1.129487,49,64.230408,24,31.374891,NaN,81,2,2.802688,57,71.240198,18,22.002226,NaN,80,1,1.545199,55,69.347311,20,24.903957,NaN,83,4,4.536196,48,57.766357,28,33.760418,NaN,86,3,3.287284,55,64.12392,24,27.756702,NaN,90,1,1.489183,64,71.094505,20,22.088183
33,Huila,1069,49,4.581489,790,73.860616,223,20.813367,NaN,1072,33,3.122863,839,78.290383,186,17.327504,NaN,1074,104,9.68816,852,79.323964,107,9.975189,NaN,1097,48,4.385359,920,83.891175,124,11.336392,NaN,1114,88,7.866777,842,75.655153,150,13.493159,NaN,1126,46,4.068352,873,77.475472,186,16.499581,NaN,1132,57,5.054012,869,76.760725,195,17.211266
34,La Guajira,734,47,6.338685,614,83.593448,65,8.796703,NaN,768,17,2.206895,680,88.499395,65,8.417678,NaN,863,51,5.942498,766,88.742063,39,4.562951,NaN,885,72,8.08462,789,89.069266,22,2.457291,NaN,910,64,6.99666,773,84.898025,63,6.893082,NaN,961,96,9.957777,771,80.226258,85,8.847708,NaN,995,25,2.561875,886,89.059456,81,8.101237
35,Magdalena,1249,74,5.934891,967,77.375102,180,14.426923,NaN,1269,142,11.196983,950,74.845414,151,11.901044,NaN,1351,199,14.761135,1042,77.127163,94,6.929701,NaN,1348,239,17.760831,1008,74.742302,84,6.24469,NaN,1384,148,10.671387,1130,81.612708,86,6.184719,NaN,1414,183,12.916796,1038,73.412718,137,9.670571,NaN,1459,242,16.582113,1102,75.513106,102,7.023193
36,Meta,973,21,2.120732,679,69.731812,252,25.880925,NaN,982,51,5.204098,661,67.309371,253,25.753358,NaN,1010,111,10.942114,792,78.383222,95,9.35602,NaN,1008,54,5.321798,797,79.068993,139,13.834307,NaN,1023,42,4.132956,776,75.7957,192,18.763311,NaN,1039,42,4.082444,732,70.468446,239,22.974333,NaN,1050,41,3.905872,801,76.319588,187,17.82512
37,Nariño,1556,39,2.485255,988,63.48597,487,31.298159,NaN,1577,58,3.709412,984,62.423875,497,31.544683,NaN,1555,56,3.619923,1060,68.210603,407,26.162488,NaN,1540,80,5.178813,1061,68.875116,366,23.74564,NaN,1586,62,3.927215,919,57.990479,573,36.166053,NaN,1586,31,1.925541,890,56.158958,634,40.002325,NaN,1601,40,2.503395,990,61.852393,543,33.91975
38,Norte de Santander,1327,41,3.088322,991,74.687533,250,18.810853,NaN,1368,173,12.66717,902,65.943455,262,19.146892,NaN,1407,91,6.465366,1048,74.470949,211,15.00201,NaN,1359,83,6.083899,1040,76.496929,189,13.926565,NaN,1460,68,4.629331,1125,77.03412,232,15.911392,NaN,1526,149,9.764029,1130,74.030733,217,14.222713,NaN,1561,102,6.518951,1176,75.340044,223,14.316653
39,Putumayo,337,4,1.045443,274,81.09768,54,16.052559,NaN,337,5,1.529394,249,73.826822,73,21.787296,NaN,342,18,5.2776,270,78.84605,50,14.700659,NaN,339,9,2.704522,249,73.347176,68,20.154664,NaN,341,14,4.074485,246,72.246516,71,20.726329,NaN,364,5,1.49842,273,74.89072,78,21.499004,NaN,369,9,2.323848,257,69.542889,85,22.932762
40,Quindío,502,38,7.596484,343,68.351815,104,20.798209,NaN,513,52,10.21547,351,68.371355,100,19.46211,NaN,512,82,15.917454,360,70.296035,64,12.427376,NaN,518,77,14.953956,361,69.65821,69,13.404825,NaN,542,91,16.81628,382,70.443638,61,11.243422,NaN,552,57,10.279835,419,75.862975,71,12.792441,NaN,558,79,14.104946,421,75.342994,51,9.197792
41,Risaralda,895,88,9.859277,627,69.999334,170,18.949018,NaN,905,88,9.778424,637,70.398578,164,18.148295,NaN,904,106,11.732571,646,71.402655,138,15.26088,NaN,908,130,14.337741,683,75.279323,84,9.255527,NaN,921,132,14.368594,677,73.573706,100,10.847415,NaN,949,103,10.839571,744,78.403539,92,9.657099,NaN,958,173,18.114424,600,62.683045,175,18.283579
42,San Andrés,41,3,7.698752,35,86.386795,2,5.751307,NaN,41,2,4.521867,36,86.663712,3,7.96618,NaN,41,1,2.348356,38,93.108451,1,2.395962,NaN,42,7,15.978041,31,75.58569,2,3.879962,NaN,43,4,10.231755,37,88.128007,1,1.475069,NaN,42,4,8.760158,37,87.557101,2,3.598635,NaN,43,6,13.345034,31,71.761124,6,13.670587
43,Santander,2066,180,8.731137,1523,73.687294,316,15.28126,NaN,2086,103,4.92374,1552,74.413709,390,18.684501,NaN,2155,363,16.839045,1623,75.320305,114,5.2711,NaN,2132,155,7.289231,1761,82.593453,153,7.159864,NaN,2231,385,17.274309,1552,69.549384,265,11.880846,NaN,2268,275,12.106167,1694,74.70346,270,11.904123,NaN,2298,373,16.223994,1645,71.55809,243,10.586943
44,Sucre,867,48,5.52369,677,78.070506,115,13.320081,NaN,884,46,5.166089,736,83.230632,90,10.17404,NaN,912,50,5.473284,789,86.517055,60,6.616985,NaN,931,130,13.996848,755,81.052439,35,3.79632,NaN,953,65,6.800199,810,84.980579,68,7.097013,NaN,974,81,8.340898,810,83.156348,72,7.371309,NaN,984,47,4.785722,871,88.523618,62,6.284831
45,Tolima,1257,56,4.422565,848,67.464058,303,24.104757,NaN,1272,75,5.909882,904,71.10802,249,19.588425,NaN,1258,78,6.240982,925,73.51506,223,17.748779,NaN,1279,67,5.249882,1015,79.409248,167,13.039551,NaN,1303,137,10.511664,943,72.367416,196,15.070747,NaN,1292,73,5.68927,941,72.81941,238,18.410029,NaN,1317,75,5.705355,968,73.51403,254,19.30915
46,Valle,4209,343,8.140243,2908,69.075829,845,20.071613,NaN,4257,366,8.606818,3163,74.315714,607,14.251034,NaN,4237,465,10.964555,3200,75.516314,521,12.28358,NaN,4267,695,16.290449,2834,66.420018,692,16.212224,NaN,4349,521,11.977058,2896,66.585867,798,18.354654,NaN,4478,505,11.2732,3147,70.276906,721,16.111723,NaN,4478,551,12.312234,3217,71.849401,654,14.595884
47,Vaupés,36,0,0.261601,27,74.786967,8,21.731637,NaN,40,1,1.669264,36,90.091459,3,7.741244,NaN,44,0,0.651345,42,94.77763,1,3.317208,NaN,47,0,0.234396,42,89.826226,4,7.58563,NaN,49,0,0.846966,41,84.364593,5,9.468559,NaN,52,1,1.943317,44,85.787328,5,10.324919,NaN,54,2,3.486626,48,89.023615,4,6.786409
48,Vichada,91,1,0.55942,68,74.307192,19,20.93589,NaN,98,0,0.435498,74,75.583602,21,21.121659,NaN,102,4,4.010029,73,71.804415,8,7.87322,NaN,102,4,3.946119,85,83.04054,9,8.739217,NaN,91,5,5.374899,77,85.042904,7,7.722342,NaN,91,0,0.435881,58,63.966475,32,35.517981,NaN,108,10,9.462665,82,75.847173,16,14.568683
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Fuente: DANE - Encuesta Nacional de Calidad de Vida,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Notas: \n- Datos expandidos con proyecciones de población con base en el CNPV 2018\n- Resultados en miles. La diferencia en la sumatoria de variables obedece al sistema de aproximación de dígitos.\n* La pregunta solo se formula a quienes manifiestan conocer el régimen de afiliación.\n** Los datos faltantes para completar el 100% corresponden a la opción “No sabe”.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Actualizado el 24 de abril de 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Eliminar filas del 1 al 10 y del 45 hacia abajo en df_ipm
indices_a_eliminar = list(range(0, 15)) + list(range(49, len(df_variables['Cuadro 11'])))
df_variables['Cuadro 11'] = df_variables['Cuadro 11'].drop(indices_a_eliminar).reset_index(drop=True)

print(f"df_variables[Cuadro 11] ahora tiene {len(df_variables['Cuadro 11'])} filas")

df_variables[Cuadro 11] ahora tiene 34 filas

In [ ]:
 # Eliminar solo la fila 0
df_variables['Cuadro 11'] = df_variables['Cuadro 11'].drop([0]).reset_index(drop=True)

print(f"df_variables[Cuadro 11] final: {len(df_variables['Cuadro 11'])} filas")

df_variables[Cuadro 11] final: 33 filas

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

df_variables['Cuadro 11']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55
0,Amazonas,71,5,6.691589,49,68.698493,17,24.257435,NaN,72,3,3.937929,62,86.400777,5,7.202269,NaN,77,3,3.258744,67,87.489587,6,8.305827,NaN,79,2,2.138769,71,88.839318,7,8.504573,NaN,80,6,6.886835,69,86.203547,3,4.125757,NaN,82,8,9.359078,62,75.715801,10,12.395325,NaN,85,15,18.208302,61,72.194795,7,7.888711
1,Antioquia,6156,665,10.797232,4430,71.963537,885,14.381902,NaN,6074,1100,18.106802,4062,66.866357,830,13.668915,NaN,6270,1201,19.149943,4617,73.639221,414,6.603347,NaN,6295,870,13.81857,4808,76.382131,511,8.112406,NaN,6586,1186,18.011869,4769,72.414368,542,8.23299,NaN,6770,1228,18.144569,4861,71.80377,582,8.600913,NaN,6850,841,12.278636,4995,72.919064,871,12.709952
2,Arauca,234,11,4.780979,169,72.432743,47,20.219953,NaN,240,4,1.763854,208,86.491403,28,11.574896,NaN,250,22,8.671761,200,79.983039,24,9.478606,NaN,242,9,3.525609,203,84.115121,24,10.065938,NaN,269,37,13.918506,202,74.941393,27,9.924057,NaN,272,12,4.575812,208,76.500604,49,18.15744,NaN,289,23,7.950025,230,79.548284,34,11.64211
3,Atlántico,2347,133,5.665039,2018,85.97669,165,7.039294,NaN,2438,196,8.027936,2052,84.173543,177,7.271158,NaN,2561,171,6.681994,2237,87.349311,141,5.512317,NaN,2582,332,12.860784,2161,83.698601,70,2.727295,NaN,2671,463,17.339669,2079,77.841244,107,4.022334,NaN,2744,479,17.450923,2002,72.967326,228,8.292009,NaN,2781,303,10.888978,2236,80.387242,216,7.780733
4,Bogotá D.C.,6892,740,10.741363,4941,71.693937,1039,15.081464,NaN,6950,603,8.678785,4919,70.784312,1155,16.616453,NaN,6971,651,9.343339,5541,79.488273,614,8.802159,NaN,7216,1288,17.849577,4717,65.370159,963,13.348723,NaN,7254,926,12.768387,5035,69.411012,1133,15.616147,NaN,7474,756,10.119834,5345,71.518559,1224,16.372367,NaN,7614,812,10.667895,5785,75.977745,865,11.363781
5,Bolívar,1950,79,4.041966,1666,85.452529,181,9.306091,NaN,2008,111,5.532007,1675,83.43325,193,9.614929,NaN,2057,155,7.534992,1770,86.026291,103,5.030758,NaN,2093,247,11.806569,1765,84.309938,53,2.548703,NaN,2169,452,20.858574,1591,73.346851,102,4.711369,NaN,2200,366,16.616628,1582,71.906964,225,10.249145,NaN,2257,340,15.05067,1802,79.834641,107,4.7533
6,Boyacá,1171,25,2.144049,775,66.17528,344,29.376871,NaN,1176,13,1.119955,891,75.763576,258,21.941581,NaN,1202,22,1.83988,1010,84.030694,163,13.576416,NaN,1202,58,4.822515,857,71.28783,259,21.537174,NaN,1214,86,7.097271,898,73.970183,218,17.969645,NaN,1235,34,2.752789,851,68.904915,330,26.769058,NaN,1257,32,2.517747,969,77.073945,247,19.628208
7,Caldas,949,153,16.170094,633,66.742606,145,15.311886,NaN,951,118,12.423611,686,72.152932,130,13.624478,NaN,959,210,21.929658,638,66.505635,95,9.903936,NaN,973,194,19.951566,648,66.593504,118,12.091828,NaN,999,173,17.340235,655,65.632505,147,14.715498,NaN,1022,165,16.16175,754,73.79914,94,9.197219,NaN,1040,107,10.253628,795,76.492135,126,12.131201
8,Caquetá,386,7,1.890372,322,83.584976,53,13.609021,NaN,388,6,1.522322,319,82.273245,58,15.039654,NaN,396,7,1.818437,345,87.161181,39,9.980401,NaN,400,32,8.083315,345,86.294587,21,5.183445,NaN,404,12,3.008107,333,82.441159,54,13.2884,NaN,413,7,1.733028,289,70.169086,110,26.722873,NaN,427,3,0.793393,320,75.050487,96,22.450689
9,Casanare,395,10,2.637661,273,69.261905,104,26.458863,NaN,393,9,2.386806,291,74.045094,85,21.606858,NaN,396,9,2.312837,304,76.733778,66,16.736306,NaN,399,29,7.206951,287,71.800625,77,19.241851,NaN,416,12,2.915615,291,69.918278,103,24.877317,NaN,413,11,2.708764,285,69.057975,105,25.481444,NaN,425,7,1.700407,301,70.831147,110,25.828378
10,Cauca,1399,45,3.189462,1080,77.170844,253,18.07195,NaN,1415,28,1.946636,1102,77.869161,267,18.90106,NaN,1421,84,5.908817,1136,79.950851,187,13.19341,NaN,1434,151,10.564146,1075,74.954843,194,13.545215,NaN,1469,94,6.379276,1152,78.434741,206,14.044614,NaN,1504,64,4.274179,997,66.260859,425,28.260158,NaN,1523,65,4.251017,915,60.096546,518,34.046812
11,Cesar,1104,87,7.870496,878,79.525913,114,10.323612,NaN,1150,47,4.126598,931,80.999633,155,13.453229,NaN,1204,112,9.280867,1036,86.116904,52,4.316702,NaN,1201,90,7.489836,1020,84.902539,73,6.082888,NaN,1263,70,5.542906,1057,83.674452,116,9.159107,NaN,1317,76,5.742704,1098,83.386823,126,9.536359,NaN,1346,171,12.690985,1085,80.641008,83,6.178269
12,Córdoba,1724,92,5.308941,1435,83.216561,178,10.330839,NaN,1754,161,9.192789,1387,79.031637,188,10.698039,NaN,1786,104,5.82088,1585,88.748078,81,4.516624,NaN,1782,110,6.169028,1519,85.220584,122,6.840606,NaN,1818,274,15.066019,1407,77.402236,116,6.368304,NaN,1854,197,10.637074,1479,79.777595,149,8.031057,NaN,1861,105,5.617893,1598,85.83857,133,7.170291
13,Cundinamarca,2761,89,3.207457,2153,77.990982,468,16.952895,NaN,2870,102,3.568364,2232,77.773057,460,16.036681,NaN,3016,198,6.566152,2554,84.672778,217,7.185463,NaN,3128,247,7.908539,2450,78.321928,386,12.350783,NaN,3300,347,10.500389,2414,73.137179,465,14.105304,NaN,3392,234,6.895623,2624,77.36765,480,14.151324,NaN,3494,606,17.338706,2250,64.390641,571,16.347729
14,Chocó,492,8,1.696541,358,72.658044,109,22.067938,NaN,514,4,0.688434,415,80.706009,84,16.294942,NaN,526,6,1.203062,410,77.949975,99,18.842102,NaN,538,10,1.89903,442,82.067743,76,14.131439,NaN,539,16,2.977256,356,66.014756,157,29.093188,NaN,549,17,3.080162,453,82.598571,70,12.682484,NaN,561,7,1.267821,458,81.610555,90,16.048066
15,Guainía,46,1,3.242786,36,78.159409,7,16.435709,NaN,47,1,1.58457,31,65.308556,14,30.92054,NaN,46,1,1.224559,38,84.514474,6,12.761112,NaN,45,0,1.030144,39,85.868945,5,11.311973,NaN,47,0,0.794129,32,68.583926,14,29.993174,NaN,47,1,2.533073,27,57.242164,18,38.00868,NaN,48,0,0.459563,32,66.845668,15,30.7252
16,Guaviare,78,0,0.56308,51,65.300567,24,30.961668,NaN,76,1,1.129487,49,64.230408,24,31.374891,NaN,81,2,2.802688,57,71.240198,18,22.002226,NaN,80,1,1.545199,55,69.347311,20,24.903957,NaN,83,4,4.536196,48,57.766357,28,33.760418,NaN,86,3,3.287284,55,64.12392,24,27.756702,NaN,90,1,1.489183,64,71.094505,20,22.088183
17,Huila,1069,49,4.581489,790,73.860616,223,20.813367,NaN,1072,33,3.122863,839,78.290383,186,17.327504,NaN,1074,104,9.68816,852,79.323964,107,9.975189,NaN,1097,48,4.385359,920,83.891175,124,11.336392,NaN,1114,88,7.866777,842,75.655153,150,13.493159,NaN,1126,46,4.068352,873,77.475472,186,16.499581,NaN,1132,57,5.054012,869,76.760725,195,17.211266
18,La Guajira,734,47,6.338685,614,83.593448,65,8.796703,NaN,768,17,2.206895,680,88.499395,65,8.417678,NaN,863,51,5.942498,766,88.742063,39,4.562951,NaN,885,72,8.08462,789,89.069266,22,2.457291,NaN,910,64,6.99666,773,84.898025,63,6.893082,NaN,961,96,9.957777,771,80.226258,85,8.847708,NaN,995,25,2.561875,886,89.059456,81,8.101237
19,Magdalena,1249,74,5.934891,967,77.375102,180,14.426923,NaN,1269,142,11.196983,950,74.845414,151,11.901044,NaN,1351,199,14.761135,1042,77.127163,94,6.929701,NaN,1348,239,17.760831,1008,74.742302,84,6.24469,NaN,1384,148,10.671387,1130,81.612708,86,6.184719,NaN,1414,183,12.916796,1038,73.412718,137,9.670571,NaN,1459,242,16.582113,1102,75.513106,102,7.023193
20,Meta,973,21,2.120732,679,69.731812,252,25.880925,NaN,982,51,5.204098,661,67.309371,253,25.753358,NaN,1010,111,10.942114,792,78.383222,95,9.35602,NaN,1008,54,5.321798,797,79.068993,139,13.834307,NaN,1023,42,4.132956,776,75.7957,192,18.763311,NaN,1039,42,4.082444,732,70.468446,239,22.974333,NaN,1050,41,3.905872,801,76.319588,187,17.82512
21,Nariño,1556,39,2.485255,988,63.48597,487,31.298159,NaN,1577,58,3.709412,984,62.423875,497,31.544683,NaN,1555,56,3.619923,1060,68.210603,407,26.162488,NaN,1540,80,5.178813,1061,68.875116,366,23.74564,NaN,1586,62,3.927215,919,57.990479,573,36.166053,NaN,1586,31,1.925541,890,56.158958,634,40.002325,NaN,1601,40,2.503395,990,61.852393,543,33.91975
22,Norte de Santander,1327,41,3.088322,991,74.687533,250,18.810853,NaN,1368,173,12.66717,902,65.943455,262,19.146892,NaN,1407,91,6.465366,1048,74.470949,211,15.00201,NaN,1359,83,6.083899,1040,76.496929,189,13.926565,NaN,1460,68,4.629331,1125,77.03412,232,15.911392,NaN,1526,149,9.764029,1130,74.030733,217,14.222713,NaN,1561,102,6.518951,1176,75.340044,223,14.316653
23,Putumayo,337,4,1.045443,274,81.09768,54,16.052559,NaN,337,5,1.529394,249,73.826822,73,21.787296,NaN,342,18,5.2776,270,78.84605,50,14.700659,NaN,339,9,2.704522,249,73.347176,68,20.154664,NaN,341,14,4.074485,246,72.246516,71,20.726329,NaN,364,5,1.49842,273,74.89072,78,21.499004,NaN,369,9,2.323848,257,69.542889,85,22.932762
24,Quindío,502,38,7.596484,343,68.351815,104,20.798209,NaN,513,52,10.21547,351,68.371355,100,19.46211,NaN,512,82,15.917454,360,70.296035,64,12.427376,NaN,518,77,14.953956,361,69.65821,69,13.404825,NaN,542,91,16.81628,382,70.443638,61,11.243422,NaN,552,57,10.279835,419,75.862975,71,12.792441,NaN,558,79,14.104946,421,75.342994,51,9.197792
25,Risaralda,895,88,9.859277,627,69.999334,170,18.949018,NaN,905,88,9.778424,637,70.398578,164,18.148295,NaN,904,106,11.732571,646,71.402655,138,15.26088,NaN,908,130,14.337741,683,75.279323,84,9.255527,NaN,921,132,14.368594,677,73.573706,100,10.847415,NaN,949,103,10.839571,744,78.403539,92,9.657099,NaN,958,173,18.114424,600,62.683045,175,18.283579
26,San Andrés,41,3,7.698752,35,86.386795,2,5.751307,NaN,41,2,4.521867,36,86.663712,3,7.96618,NaN,41,1,2.348356,38,93.108451,1,2.395962,NaN,42,7,15.978041,31,75.58569,2,3.879962,NaN,43,4,10.231755,37,88.128007,1,1.475069,NaN,42,4,8.760158,37,87.557101,2,3.598635,NaN,43,6,13.345034,31,71.761124,6,13.670587
27,Santander,2066,180,8.731137,1523,73.687294,316,15.28126,NaN,2086,103,4.92374,1552,74.413709,390,18.684501,NaN,2155,363,16.839045,1623,75.320305,114,5.2711,NaN,2132,155,7.289231,1761,82.593453,153,7.159864,NaN,2231,385,17.274309,1552,69.549384,265,11.880846,NaN,2268,275,12.106167,1694,74.70346,270,11.904123,NaN,2298,373,16.223994,1645,71.55809,243,10.586943
28,Sucre,867,48,5.52369,677,78.070506,115,13.320081,NaN,884,46,5.166089,736,83.230632,90,10.17404,NaN,912,50,5.473284,789,86.517055,60,6.616985,NaN,931,130,13.996848,755,81.052439,35,3.79632,NaN,953,65,6.800199,810,84.980579,68,7.097013,NaN,974,81,8.340898,810,83.156348,72,7.371309,NaN,984,47,4.785722,871,88.523618,62,6.284831
29,Tolima,1257,56,4.422565,848,67.464058,303,24.104757,NaN,1272,75,5.909882,904,71.10802,249,19.588425,NaN,1258,78,6.240982,925,73.51506,223,17.748779,NaN,1279,67,5.249882,1015,79.409248,167,13.039551,NaN,1303,137,10.511664,943,72.367416,196,15.070747,NaN,1292,73,5.68927,941,72.81941,238,18.410029,NaN,1317,75,5.705355,968,73.51403,254,19.30915
30,Valle,4209,343,8.140243,2908,69.075829,845,20.071613,NaN,4257,366,8.606818,3163,74.315714,607,14.251034,NaN,4237,465,10.964555,3200,75.516314,521,12.28358,NaN,4267,695,16.290449,2834,66.420018,692,16.212224,NaN,4349,521,11.977058,2896,66.585867,798,18.354654,NaN,4478,505,11.2732,3147,70.276906,721,16.111723,NaN,4478,551,12.312234,3217,71.849401,654,14.595884
31,Vaupés,36,0,0.261601,27,74.786967,8,21.731637,NaN,40,1,1.669264,36,90.091459,3,7.741244,NaN,44,0,0.651345,42,94.77763,1,3.317208,NaN,47,0,0.234396,42,89.826226,4,7.58563,NaN,49,0,0.846966,41,84.364593,5,9.468559,NaN,52,1,1.943317,44,85.787328,5,10.324919,NaN,54,2,3.486626,48,89.023615,4,6.786409
32,Vichada,91,1,0.55942,68,74.307192,19,20.93589,NaN,98,0,0.435498,74,75.583602,21,21.121659,NaN,102,4,4.010029,73,71.804415,8,7.87322,NaN,102,4,3.946119,85,83.04054,9,8.739217,NaN,91,5,5.374899,77,85.042904,7,7.722342,NaN,91,0,0.435881,58,63.966475,32,35.517981,NaN,108,10,9.462665,82,75.847173,16,14.568683

In [ ]:
print(df_variables['Cuadro 11'].columns.tolist())

['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55']

In [ ]:
# Colocar el nombre de las columnas en el orden que quiero que queden
df_variables['Cuadro 11'] = df_variables['Cuadro 11'][['Unnamed: 0', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 52','Unnamed: 54']]
df_variables['Cuadro 11'].head(2)

  Unnamed: 0 Unnamed: 49 Unnamed: 50 Unnamed: 52 Unnamed: 54
0   Amazonas          85          15          61           7
1  Antioquia        6850         841        4995         871

In [ ]:
# Renombrar columnas
df_variables['Cuadro 11'] = df_variables['Cuadro 11'].rename(columns={
    'Unnamed: 0': 'Departamentos',
    'Unnamed: 49': 'Personas afiliadas',
    'Unnamed: 50': 'muy buena',
    'Unnamed: 52': 'Buena',
    'Unnamed: 54': 'mala'
})

# Verificar resultado
df_variables['Cuadro 11'].head(2)

  Departamentos Personas afiliadas muy buena Buena mala
0      Amazonas                 85        15    61    7
1     Antioquia               6850       841  4995  871

In [ ]:
#Encontrar duplicados
df_variables['Cuadro 11'].duplicated().sum()

np.int64(0)

In [ ]:
# Ver la cantidad de valores nulos en cada columna
df_variables['Cuadro 11'].isna().sum()

Departamentos         0
Personas afiliadas    0
muy buena             0
Buena                 0
mala                  0
dtype: int64

# 3.Estadisticas descriptivas

# 3.1.IPM